import fs from 'fs';

const items = [
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Zgodnie z definicją WHO z 1948 roku, zdrowie to:', o: ['Całkowity dobrostan fizyczny, psychiczny i społeczny, a nie wyłącznie brak choroby lub niedomagania', 'Wyłącznie brak stwierdzonej choroby w badaniach laboratoryjnych', 'Zdolność do wykonywania pracy zarobkowej bez ograniczeń', 'Subiektywne poczucie braku dolegliwości, niezależnie od wyników badań', 'Stan całkowitej sprawności fizycznej porównywalnej ze sportowcem'], a: 0, rationale: 'Klasyczna definicja WHO z 1948 roku opisuje zdrowie jako CAŁKOWITY dobrostan fizyczny, psychiczny i społeczny, a NIE wyłącznie brak choroby lub niedomagania — to szerokie, holistyczne ujęcie, celowo wykraczające poza czysto medyczne rozumienie zdrowia. Opcja B zawęża definicję tylko do wymiaru obiektywnego (badania), pomijając psychiczny i społeczny dobrostan — dokładnie to, przed czym przestrzega definicja WHO ("a nie wyłącznie brak choroby"). Opcja C myli zdrowie ze zdolnością do pracy — to tylko jeden z możliwych elementów oceny społecznej, nie cała definicja. Opcja D ogranicza się do subiektywnego kryterium oceny zdrowia, pomijając dwa pozostałe (obiektywne, społeczne) oraz sam trójwymiarowy dobrostan z definicji WHO. Opcja E błędnie utożsamia zdrowie z maksymalną sprawnością fizyczną, co nie jest zgodne z holistyczną definicją WHO.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Jaki jest orientacyjny procentowy udział POSZCZEGÓLNYCH czynników wpływających na zdrowie człowieka wg klasycznego podziału (styl życia / środowisko / genetyka / ochrona zdrowia)?', o: ['Styl życia 50%, środowisko 20%, genetyka 20%, ochrona zdrowia 10%', 'Styl życia 10%, środowisko 10%, genetyka 10%, ochrona zdrowia 70%', 'Styl życia 25%, środowisko 25%, genetyka 25%, ochrona zdrowia 25%', 'Styl życia 90%, środowisko 5%, genetyka 3%, ochrona zdrowia 2%', 'Styl życia 20%, środowisko 50%, genetyka 20%, ochrona zdrowia 10%'], a: 0, rationale: 'Klasyczny podział czynników determinujących zdrowie człowieka to: styl życia 50% (największy pojedynczy wpływ — odżywianie, aktywność, nałogi), środowisko fizyczne/społeczne życia-pracy-nauki 20%, czynniki genetyczne 20%, oraz działanie ochrony zdrowia (opieka medyczna) tylko 10% — ten ostatni punkt jest często zaskakujący dla studentów, bo intuicyjnie przecenia się rolę samej medycyny względem stylu życia. Opcja B rażąco przecenia rolę ochrony zdrowia (70%) kosztem stylu życia — dokładne odwrócenie proporcji z klasycznego podziału. Opcja C (równy podział po 25%) ignoruje rzeczywistą, nierówną hierarchię czynników — styl życia ma zdecydowanie największy udział, nie równy pozostałym. Opcja D przesadnie zawyża rolę stylu życia (90%) kosztem pozostałych czynników, tracąc realistyczne proporcje. Opcja E błędnie zamienia miejscami wartości dla stylu życia i środowiska względem prawidłowego podziału.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Ile dni trwa okres noworodkowy (w ramach okresu postnatalnego ontogenezy człowieka)?', answers: ['pierwsze 28 dni życia', '28 dni'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Do kiedy trwa okres niemowlęcy w ontogenezie człowieka?', answers: ['do końca 1. roku życia', 'do końca pierwszego roku życia'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Na jakie dwie fazy dzieli się prenatalny (śródmaciczny) okres ontogenezy człowieka?', answers: ['faza zarodkowa i faza płodowa', 'zarodkowa (do końca 8. tygodnia) i płodowa (od 9. tygodnia do narodzin)'] },
];

const raw = JSON.parse(fs.readFileSync('fakultety_raw.json', 'utf8'));
items.forEach(item => raw.push(item));
fs.writeFileSync('fakultety_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'pytan. nowa dlugosc fakultety_raw.json:', raw.length);
