import fs from 'fs';

const items = [
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'W analizie SWOT, "Mocne strony" i "Słabe strony" to czynniki:', o: ['Wewnętrzne', 'Zewnętrzne', 'Historyczne', 'Normatywne', 'Międzyprzedmiotowe'], a: 0, rationale: 'Mocne strony (Strengths) i słabe strony (Weaknesses) to czynniki WEWNĘTRZNE organizacji — dotyczą jej własnych zasobów, kompetencji i ograniczeń, na które organizacja ma bezpośredni wpływ. Szanse i zagrożenia są w SWOT czynnikami zewnętrznymi (opcja B) — pochodzą z otoczenia organizacji, nie z niej samej, więc opcja B opisuje przeciwną parę elementów analizy. Historyczny, normatywny i międzyprzedmiotowy (opcje C, D, E) to nie kategorie czynników SWOT, lecz trzy RODZAJE PUNKTÓW ODNIESIENIA używanych przy ocenie stanu obecnego organizacji w analizie SWOT — zupełnie inna klasyfikacja z tego samego materiału, ale odpowiadająca na inne pytanie.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Czym różni się kierunek analizy TOWS od klasycznego SWOT?', o: ['TOWS analizuje "z zewnątrz do wewnątrz" (od otoczenia do organizacji), a SWOT "od wewnątrz na zewnątrz"', 'TOWS dotyczy wyłącznie sektora publicznego, a SWOT wyłącznie prywatnego', 'TOWS jest starszą, przestarzałą wersją SWOT, aktualnie niestosowaną', 'TOWS analizuje tylko czynniki finansowe, a SWOT tylko czynniki personalne', 'Nie ma żadnej różnicy — to dwie nazwy tej samej dokładnie procedury'], a: 0, rationale: 'SWOT analizuje sytuację "od wewnątrz na zewnątrz" (zaczynając od mocnych/słabych stron organizacji i sprawdzając, jak wpływają na wykorzystanie szans/zagrożeń), natomiast TOWS odwraca tę kolejność i analizuje "z zewnątrz do wewnątrz" (zaczynając od szans/zagrożeń otoczenia i sprawdzając, jak wpływają na mocne/słabe strony organizacji) — sam akronim TOWS to odwrócona kolejność liter SWOT, co dobrze oddaje tę zmianę perspektywy. Opcja B błędnie sugeruje podział sektorowy, którego w materiale nie ma — obie metody dotyczą analizy strategicznej niezależnie od sektora. Opcja C jest nieprawdziwa — TOWS to nie przestarzała wersja, tylko alternatywna, równoległa perspektywa tej samej analizy. Opcja D błędnie zawęża obie metody do wąskich, pojedynczych obszarów tematycznych, podczas gdy obie obejmują pełen zakres czynników organizacyjnych i środowiskowych. Opcja E jest sprzeczna z samą istotą materiału, który wyraźnie rozróżnia oba kierunki analizy jako odmienne podejścia.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', mode: 'typed', q: 'Wymień "pięć sił konkurencji Portera" analizowanych w bliższym otoczeniu firmy w ramach analizy SWOT.', answers: ['wejście na rynek, groźba substytutów, siła przetargowa klientów, siła przetargowa dostawców, rywalizacja obecnych konkurentów', 'groźba nowych wejść, groźba substytutów, siła przetargowa nabywców, siła przetargowa dostawców, rywalizacja w sektorze'] },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Strategię AGRESYWNĄ (maxi-maxi) w analizie SWOT zaleca się organizacji, w której przypadku:', o: ['W otoczeniu przeważają szanse, a wewnątrz organizacji mocne strony', 'W otoczeniu przeważają zagrożenia, a wewnątrz organizacji słabe strony', 'W otoczeniu przeważają szanse, a wewnątrz organizacji słabe strony', 'W otoczeniu przeważają zagrożenia, a wewnątrz organizacji mocne strony', 'Nie ma znaczenia układ szans/zagrożeń ani mocnych/słabych stron'], a: 0, rationale: 'Strategia agresywna (maxi-maxi) dotyczy organizacji, w których w otoczeniu PRZEWAŻAJĄ SZANSE, a wewnątrz organizacji przeważają MOCNE STRONY — zaleca się wtedy silną ekspansję i zdywersyfikowany rozwój, bo warunki są optymalne z obu stron. Opcja B (zagrożenia + słabe strony) to dokładny opis sytuacji strategii DEFENSYWNEJ (mini-mini), przeciwieństwa agresywnej. Opcja C (szanse + słabe strony) to sytuacja strategii KONKURENCYJNEJ (mini-maxi) — trzeba maksymalnie wykorzystać szanse, jednocześnie eliminując słabości. Opcja D (zagrożenia + mocne strony) to sytuacja strategii KONSERWATYWNEJ (maxi-mini) — trzeba wykorzystać mocne strony do przezwyciężenia niekorzystnego otoczenia. Opcja E jest nieprawdziwa — to właśnie konkretny UKŁAD czynników (szanse/zagrożenia × mocne/słabe strony) determinuje, którą z czterech strategii SWOT należy zastosować.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Strategię DEFENSYWNĄ (mini-mini) w analizie SWOT charakteryzuje sytuacja, w której organizacja:', o: ['Ma przewagę słabych stron i działa w niekorzystnym otoczeniu (zagrożenia) — to "gra o przetrwanie"', 'Ma przewagę mocnych stron i działa w otoczeniu pełnym szans — zaleca się ekspansję', 'Ma przewagę mocnych stron, ale otoczenie jest niekorzystne (zagrożenia)', 'Ma przewagę słabych stron, ale otoczenie sprzyja (szanse)', 'Ma zrównoważony bilans mocnych i słabych stron przy neutralnym otoczeniu'], a: 0, rationale: 'Strategia defensywna (mini-mini) dotyczy przedsiębiorstwa z przewagą słabych stron, działającego w niekorzystnym otoczeniu (przewaga zagrożeń) — to sytuacja "gry o przetrwanie", w której rozważa się np. połączenie z inną firmą lub likwidację. Opcja B opisuje dokładnie sytuację strategii AGRESYWNEJ (maxi-maxi) — przeciwieństwo defensywnej. Opcja C (mocne strony + zagrożenia) to sytuacja strategii KONSERWATYWNEJ (maxi-mini), nie defensywnej. Opcja D (słabe strony + szanse) to sytuacja strategii KONKURENCYJNEJ (mini-maxi), również inna niż defensywna. Opcja E opisuje sytuację niejednoznaczną/zrównoważoną, która nie odpowiada żadnej z czterech klasycznych, "skrajnych" strategii SWOT opartych na przewadze jednego czynnika nad drugim.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', mode: 'typed', q: 'Jakie są trzy rodzaje "punktów odniesienia" stosowanych przy ocenie stanu obecnego organizacji w analizie SWOT?', answers: ['historyczny, normatywny, międzyprzedmiotowy', 'punkt historyczny, normatywny i międzyprzedmiotowy'] },
];

const raw = JSON.parse(fs.readFileSync('fakultety_raw.json', 'utf8'));
items.forEach(item => raw.push(item));
fs.writeFileSync('fakultety_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'pytan. nowa dlugosc fakultety_raw.json:', raw.length);
