import fs from 'fs';

const items = [
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Który podmiot NIE MOŻE utworzyć Publicznego Zakładu Opieki Zdrowotnej (PZOZ)?', o: ['Kościół lub związek wyznaniowy', 'Minister lub centralny organ administracji rządowej', 'Wojewoda', 'Jednostka samorządu terytorialnego', 'Publiczna uczelnia medyczna'], a: 0, rationale: 'Kościół lub związek wyznaniowy może utworzyć wyłącznie Niepubliczny Zakład Opieki Zdrowotnej (NZOZ), nie publiczny — to jeden z podmiotów wymienionych wprost jako założyciele NZOZ. Minister/centralny organ administracji rządowej (opcja B), wojewoda (opcja C), jednostka samorządu terytorialnego (opcja D) i publiczna uczelnia medyczna (opcja E) to WSZYSTKIE podmioty uprawnione do tworzenia PUBLICZNYCH zakładów opieki zdrowotnej — wymienione wprost w katalogu założycieli PZOZ.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Samodzielny Publiczny Zakład Opieki Zdrowotnej (SPZOZ) uzyskuje osobowość prawną w momencie:', o: ['Wpisania do Krajowego Rejestru Sądowego', 'Podpisania umowy z NFZ', 'Zatrudnienia pierwszego pracownika', 'Ogłoszenia w Monitorze Polskim', 'Uzyskania akredytacji Ministerstwa Zdrowia'], a: 0, rationale: 'SPZOZ podlega obowiązkowi rejestracji w Krajowym Rejestrze Sądowym (KRS), a z chwilą wpisania do tego rejestru uzyskuje osobowość prawną — może wtedy podejmować działania we własnym zakresie i na własny rachunek. Podpisanie umowy z NFZ (opcja B) dotyczy KONTRAKTOWANIA świadczeń, czyli finansowania działalności, nie samego powstania osobowości prawnej podmiotu. Zatrudnienie pierwszego pracownika (opcja C) nie jest formalnym momentem nabycia osobowości prawnej w polskim prawie. Ogłoszenie w Monitorze Polskim (opcja D) i akredytacja Ministerstwa Zdrowia (opcja E) to procedury niezwiązane bezpośrednio z nabyciem osobowości prawnej SPZOZ — kluczowy jest wyłącznie wpis do KRS.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', mode: 'typed', q: 'Jaki jest współczynnik korygujący roczną stawkę kapitacyjną dla grupy wiekowej DO 6. roku życia?', answers: ['2,8', '2.8'] },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', mode: 'typed', q: 'Jaki jest współczynnik korygujący roczną stawkę kapitacyjną dla grupy wiekowej POWYŻEJ 75. roku życia?', answers: ['3,1', '3.1'] },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Który sposób rozliczania świadczeń zdrowotnych polega na przeznaczeniu ustalonej kwoty na objęcie opieką JEDNEGO świadczeniobiorcy przez okres JEDNEGO ROKU, niezależnie od faktycznej liczby udzielonych mu świadczeń?', o: ['Kapitacyjna stawka roczna', 'Cena jednostkowa jednostki rozliczeniowej', 'Ryczałt dobowy', 'Opłata za usługę (fee-for-service)', 'Rozliczenie kosztorysowe'], a: 0, rationale: 'Kapitacyjna stawka roczna to kwota przeznaczona na objęcie opieką JEDNEGO świadczeniobiorcy w okresie JEDNEGO ROKU w ustalonym zakresie świadczeń — świadczeniodawca otrzymuje tę samą stawkę niezależnie od tego, ile razy dany pacjent faktycznie skorzysta z opieki (stąd współczynniki korygujące wg grup wiekowych, bo różne grupy generują różne przeciętne obciążenie). Cena jednostkowa jednostki rozliczeniowej (opcja B) to rozliczenie za KONKRETNĄ, wykonaną usługę/procedurę, przeciwieństwo stawki "z góry" niezależnej od liczby świadczeń. Ryczałt dobowy (opcja C) i rozliczenie kosztorysowe (opcja E) to inne modele finansowania, niezwiązane z rocznym okresem per pacjent. Opłata za usługę / fee-for-service (opcja D) to model dokładnie odwrotny do kapitacji — płatność zależy WPROST od liczby i rodzaju wykonanych świadczeń, nie jest stała.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Od kiedy (zgodnie z materiałem) dokumentacja medyczna MOŻE być prowadzona WYŁĄCZNIE w formie elektronicznej (nie papierowej)?', o: ['Od 1 stycznia 2018 r.', 'Od 1 stycznia 2000 r.', 'Od 1 stycznia 2010 r.', 'Od 1 stycznia 2025 r.', 'Nigdy — dokumentacja papierowa jest zawsze dopuszczalna równolegle'], a: 0, rationale: 'Do 31 grudnia 2017 r. dokumentacja medyczna mogła być prowadzona w postaci papierowej lub elektronicznej — po tej dacie, czyli od 1 stycznia 2018 r., dokumentacja może być prowadzona wyłącznie w formie elektronicznej. Pozostałe daty (2000, 2010, 2025 — opcje B, C, D) nie odpowiadają granicznej dacie podanej w materiale. Opcja E jest sprzeczna wprost z treścią przepisu, który jasno wskazuje graniczną datę przejścia na wyłącznie elektroniczną formę dokumentacji.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Do których z poniższych specjalistów pacjent NIE POTRZEBUJE skierowania?', o: ['Ginekolog-położnik, dentysta, wenerolog, onkolog, psychiatra', 'Kardiolog, endokrynolog, diabetolog, pulmonolog, alergolog', 'Neurolog, nefrolog, hepatolog, gastroenterolog, reumatolog', 'Chirurg ogólny, chirurg naczyniowy, ortopeda, urolog, laryngolog', 'Dermatolog, okulista, immunolog, hematolog, geriatra'], a: 0, rationale: 'Skierowanie nie jest wymagane do: ginekologa i położnika, dentysty, wenerologa, onkologa oraz psychiatry — to zamknięty katalog specjalistów wymieniony w materiale, do których pacjent może zgłosić się bezpośrednio, bez skierowania od lekarza POZ. Pozostałe opcje (B, C, D, E) wymieniają innych specjalistów (kardiolog, neurolog, chirurg, dermatolog itd.), do których w standardowym trybie skierowanie JEST wymagane — nie znajdują się na liście wyjątków podanej w materiale.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Osoby chore na które schorzenie/stan są zwolnione z obowiązku posiadania skierowania (niezależnie od specjalizacji lekarza, do którego się zgłaszają)?', o: ['Gruźlica, zakażenie wirusem HIV', 'Nadciśnienie tętnicze', 'Cukrzyca typu 2', 'Astma oskrzelowa', 'Choroba niedokrwienna serca'], a: 0, rationale: 'Skierowanie nie jest wymagane od osób chorych na gruźlicę oraz zakażonych wirusem HIV (a także inwalidów wojennych/osób represjonowanych i uzależnionych — w zakresie lecznictwa odwykowego) — to szczególna kategoria zwolnień związana z priorytetowym, ułatwionym dostępem do diagnostyki/leczenia chorób o istotnym znaczeniu epidemiologicznym i społecznym. Nadciśnienie tętnicze (opcja B), cukrzyca typu 2 (opcja C), astma oskrzelowa (opcja D) i choroba niedokrwienna serca (opcja E) to schorzenia objęte w materiale programem OPIEKI KOORDYNOWANEJ w POZ, ale nie są wymienione jako podstawa zwolnienia ze skierowania do specjalisty.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'Które grupy osób mają prawo do BEZPŁATNYCH świadczeń zdrowotnych NIEZALEŻNIE od posiadanego ubezpieczenia?', o: ['Osoby, które nie ukończyły 18. roku życia oraz kobiety w okresie ciąży, porodu i połogu', 'Wyłącznie emeryci i renciści', 'Wyłącznie osoby zatrudnione na umowę o pracę', 'Wyłącznie funkcjonariusze służb mundurowych', 'Wyłącznie studenci uczelni medycznych'], a: 0, rationale: 'Do bezpłatnych świadczeń zdrowotnych bez względu na ubezpieczenie uprawnione są m.in. osoby, które nie ukończyły 18. roku życia, kobiety w okresie ciąży, porodu i połogu, a także osoby uzależnione poddające się leczeniu odwykowemu oraz osoby chore psychicznie w zakresie opieki psychiatrycznej — to szeroki katalog grup szczególnie chronionych. Opcje B, C, D i E błędnie zawężają uprawnienie do jednej wąskiej grupy zawodowej/społecznej (emeryci, pracownicy etatowi, mundurowi, studenci medycyny), podczas gdy prawdziwy katalog uprawnionych w materiale opiera się na kryteriach wieku, stanu fizjologicznego (ciąża) i konkretnych stanów zdrowotnych, nie na statusie zawodowym.' },
  { category: 'Kompetencje generyczne — Zdrowie publiczne', q: 'W ramach jakich CZTERECH grup schorzeń realizowana jest w Polsce tzw. OPIEKA KOORDYNOWANA w POZ?', o: ['Choroby układu krążenia; cukrzyca; astma i POChP; niedoczynność tarczycy i guzki tarczycy', 'Nowotwory; choroby zakaźne; choroby psychiczne; choroby oczu', 'Choroby skóry; choroby układu moczowego; choroby stawów; choroby wątroby', 'Choroby zębów; choroby uszu; choroby oczu; choroby układu nerwowego', 'Wyłącznie cukrzyca i otyłość'], a: 0, rationale: 'Opieka koordynowana w POZ obejmuje cztery zakresy: (1) diagnostykę i leczenie nadciśnienia tętniczego, niewydolności serca, przewlekłej choroby niedokrwiennej serca oraz migotania przedsionków, (2) diagnostykę i leczenie cukrzycy, (3) diagnostykę i leczenie astmy oskrzelowej i POChP, (4) diagnostykę i leczenie niedoczynności tarczycy oraz diagnostykę guzków tarczycy. Pozostałe opcje (B, C, D, E) wymieniają grupy schorzeń NIEOBJĘTE tym konkretnym programem opieki koordynowanej w POZ opisanym w materiale — to fikcyjne lub niekompletne (opcja E) zestawienia niezgodne z rzeczywistym, czteroczęściowym katalogiem.' },
];

const raw = JSON.parse(fs.readFileSync('fakultety_raw.json', 'utf8'));
items.forEach(item => raw.push(item));
fs.writeFileSync('fakultety_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'pytan. nowa dlugosc fakultety_raw.json:', raw.length);
