import fs from 'fs';

const items = [
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Który wskaźnik epidemiologiczny opisuje liczbę zgonów Z POWODU DANEJ CHOROBY w stosunku do liczby osób CHORYCH na tę chorobę?', o: ['Śmiertelność', 'Umieralność ogólna', 'Zapadalność', 'Chorobowość', 'Zapadalność skumulowana'], a: 0, rationale: 'Śmiertelność to liczba zgonów z powodu danej choroby w stosunku do liczby CHORYCH na tę chorobę — miara "ile procent chorych umiera". Umieralność ogólna (opcja B) to liczba zgonów w stosunku do liczby CAŁEJ LUDNOŚCI danego terenu, nie tylko chorych — inny mianownik. Zapadalność (opcja C) to liczba NOWYCH zachorowań w stosunku do liczby ludności — mierzy częstość NOWYCH przypadków, nie zgonów. Chorobowość (opcja D) to ogólna liczba wszystkich przypadków choroby (nowych i starych) w populacji w danym momencie — też nie dotyczy zgonów. Zapadalność skumulowana (opcja E) to wariant zapadalności liczony w dłuższym okresie, nadal dotyczy nowych zachorowań, nie zgonów.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Który wskaźnik epidemiologiczny opisuje liczbę NOWYCH zachorowań na daną chorobę w stosunku do liczby ludności?', o: ['Zapadalność', 'Śmiertelność', 'Umieralność ogólna', 'Chorobowość', 'Nosicielstwo'], a: 0, rationale: 'Zapadalność (incidencja) to liczba nowych zachorowań na określoną chorobę w stosunku do liczby ludności — kluczowy wskaźnik dynamiki epidemii. Śmiertelność (opcja B) dotyczy zgonów wśród już chorych, nie nowych zachorowań. Umieralność ogólna (opcja C) dotyczy WSZYSTKICH zgonów (niezależnie od przyczyny) w populacji, nie nowych zachorowań na konkretną chorobę. Chorobowość (opcja D) to liczba WSZYSTKICH (nowych i starych) przypadków w danym momencie — miara "stanu", nie "napływu" nowych przypadków jak zapadalność. Nosicielstwo (opcja E) to zupełnie inne pojęcie — dotyczy osób będących bezobjawowym źródłem zakażenia, nie statystyki zachorowań w populacji.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Które choroby zalicza się do CHORÓB KWARANTANNOWYCH?', o: ['Cholera, dżuma, żółta gorączka, ospa prawdziwa, gorączka krwotoczna, dur wysypkowy', 'Grypa, przeziębienie, angina paciorkowcowa', 'Odra, świnka, różyczka', 'Borelioza, kleszczowe zapalenie mózgu', 'Salmonelloza, czerwonka, WZW A'], a: 0, rationale: 'Choroby kwarantannowe to grupa najbardziej niebezpiecznych, wysoce epidemicznych infekcji podlegających międzynarodowym przepisom sanitarnym: cholera, dżuma, żółta gorączka, ospa prawdziwa, gorączki krwotoczne oraz dur wysypkowy (plamisty). Opcje B, C, D i E wymieniają choroby zakaźne o różnym stopniu zaraźliwości i ciężkości, ale ŻADNA z nich nie należy do klasycznej listy chorób kwarantannowych — to choroby "zwykłe" zakaźne/wektorowe, objęte innymi, mniej rygorystycznymi trybami nadzoru epidemiologicznego niż kwarantanna międzynarodowa.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Jaki jest mechanizm zakażenia DUREM PLAMISTYM (wysypkowym) przenoszonym przez wszy?', o: ['Wtarcie kału zakażonej wszy w uszkodzoną skórę', 'Wstrzyknięcie drobnoustrojów przez ukłucie wszy, jak przy komarze', 'Spożycie pokarmu zanieczyszczonego odchodami wszy', 'Wdychanie drogą kropelkową od zakażonego człowieka', 'Bezpośredni kontakt skóra-skóra z osobą zakażoną'], a: 0, rationale: 'W durze plamistym (wysypkowym) do zakażenia dochodzi przez wtarcie KAŁU zakażonej wszy w uszkodzoną (podrapaną) skórę — sama wesz PODCZAS ukłucia nie przekazuje zarazka bezpośrednio przez ślinę (jak np. komar), lecz zakażenie następuje wtórnie przez zadrapanie miejsca ukłucia zanieczyszczonego odchodami wszy. Opcja B błędnie opisuje mechanizm typowy dla przenoszenia przez KOMARY (np. w zimnicy/malarii), nie przez wszy w durze plamistym. Opcja C (droga pokarmowa) to mechanizm typowy dla chorób takich jak cholera, nie duru plamistego przenoszonego przez wszy. Opcja D (droga kropelkowa) i E (kontakt skórny) to zupełnie inne drogi transmisji, niezwiązane z mechanizmem przenoszenia przez wszy.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Jaki jest rezerwuar i wektor DŻUMY?', o: ['Rezerwuar: szczury; wektor: pchły', 'Rezerwuar: komary; wektor: ptaki', 'Rezerwuar: człowiek; wektor: wszy', 'Rezerwuar: gryzonie leśne; wektor: kleszcze', 'Rezerwuar: ptaki wodne; wektor: komary'], a: 0, rationale: 'Dżuma szerzy się głównie wśród szczurów, które są jej naturalnym rezerwuarem, a wektorem przenoszącym bakterię (Yersinia pestis) między szczurami i na człowieka są pchły. Opcja B (komary, ptaki) to układ typowy dla niektórych chorób arbowirusowych, nie dżumy. Opcja C (człowiek, wszy) opisuje raczej mechanizm duru plamistego, nie dżumy (choć w postaci płucnej dżuma może się szerzyć też drogą kropelkową między ludźmi, to nie jest to główny, klasyczny łańcuch rezerwuar-wektor tej choroby). Opcja D (gryzonie leśne, kleszcze) i E (ptaki wodne, komary) opisują układy typowe dla innych chorób odzwierzęcych (np. boreliozy czy niektórych gorączek krwotocznych), nie dżumy.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Ospa prawdziwa (variola) występuje w dwóch postaciach różniących się wielkością wykwitów i śmiertelnością — jak się nazywają?', answers: ['variola major i variola minor', 'Variola major i Variola minor'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Powyżej jakiego natężenia hałasu (z częstotliwościami średnimi i wysokimi) uznaje się go za SZKODLIWY dla zdrowia?', o: ['70-80 dB', '20-30 dB', '40-50 dB', '120-140 dB', '10-15 dB'], a: 0, rationale: 'Hałas o natężeniu powyżej 70-80 dB, zwłaszcza z częstotliwościami średnimi i wysokimi, uznaje się za szkodliwy dla zdrowia. 20-30 dB (opcja B) to poziom bardzo cichego otoczenia (np. szept), znacznie poniżej progu szkodliwości. 40-50 dB (opcja C) to typowy poziom hałasu w biurze czy warsztacie precyzyjnym — akceptowalne normy pracy, nie próg szkodliwości. 120-140 dB (opcja D) to poziom skrajnie wysoki, odpowiadający np. startowi silnika odrzutowego — znacznie powyżej progu szkodliwości, a nie sam próg. 10-15 dB (opcja E) to niemal całkowita cisza, wielokrotnie poniżej jakiegokolwiek progu szkodliwości.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Jaka jest dopuszczalna norma hałasu w pomieszczeniach biurowych?', answers: ['40 dB', '40dB'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Jaka jest dopuszczalna norma hałasu w warsztatach prac precyzyjnych?', answers: ['50 dB', '50dB'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Jaka jest dopuszczalna norma hałasu w halach fabrycznych?', answers: ['85 dB', '85dB'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Jaka jest ROCZNA dawka graniczna promieniowania jonizującego (dawka skuteczna) dla osób zatrudnionych w warunkach narażenia zawodowego?', o: ['20 mSv w roku kalendarzowym (możliwe przekroczenie do 50 mSv, jeśli suma z 5 lat nie przekroczy 100 mSv)', '1 mSv w roku kalendarzowym bezwzględnie', '100 mSv w roku kalendarzowym bez żadnych ograniczeń', '5 mSv w roku kalendarzowym, bez możliwości przekroczenia', '500 mSv w roku kalendarzowym'], a: 0, rationale: 'Standardowa roczna dawka graniczna dla pracowników zawodowo narażonych na promieniowanie jonizujące wynosi 20 mSv, przy czym może być ona przekroczona w danym roku do 50 mSv, pod warunkiem że suma dawek z kolejnych 5 lat kalendarzowych nie przekroczy 100 mSv — to elastyczny, ale ograniczony mechanizm. 1 mSv (opcja B) to graniczna dawka dla PŁODU kobiety ciężarnej narażonej zawodowo, nie dla samego pracownika — to inny, znacznie bardziej rygorystyczny limit dotyczący ochrony nienarodzonego dziecka. 100 mSv "bez ograniczeń" (opcja C) błędnie przedstawia wartość będącą w rzeczywistości pięcioletnim SUMARYCZNYM limitem jako roczną, dowolnie osiągalną normę. 5 mSv (opcja D) zaniża rzeczywisty roczny limit czterokrotnie. 500 mSv (opcja E) rażąco zawyża limit, dwudziestopięciokrotnie ponad rzeczywistą normę roczną.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Jaka jest maksymalna dopuszczalna dawka promieniowania jonizującego dla PŁODU kobiety ciężarnej narażonej zawodowo (w ciągu całej ciąży)?', answers: ['1 mSv', '1mSv'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Jak nazywa się reguła mówiąca, że wrażliwość komórek na promieniowanie jonizujące jest wprost proporcjonalna do ich aktywności proliferacyjnej i odwrotnie proporcjonalna do stopnia zróżnicowania?', answers: ['reguła Bergoniego i Tribondeau', 'prawo Bergoniego-Tribondeau'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Które narządy należą do NAJBARDZIEJ wrażliwych na promieniowanie jonizujące?', o: ['Szpik kostny, tarczyca, gruczoł piersiowy u kobiet, płuca', 'Skóra, paznokcie, włosy', 'Kości długie kończyn, chrząstki stawowe', 'Mięśnie szkieletowe, ścięgna', 'Rogówka oka i twardówka'], a: 0, rationale: 'Do narządów najbardziej wrażliwych na promieniowanie jonizujące należą: szpik kostny (intensywnie dzielące się komórki krwiotwórcze), tarczyca, gruczoł piersiowy u kobiet oraz płuca — te tkanki mają wysoką aktywność proliferacyjną i/lub niski stopień zróżnicowania (zgodnie z regułą Bergoniego-Tribondeau). Skóra, paznokcie i włosy (opcja B) mają umiarkowaną, nie najwyższą wrażliwość. Kości długie i chrząstki stawowe (opcja C) to tkanki o niskiej aktywności proliferacyjnej u dorosłych — stosunkowo mało wrażliwe. Mięśnie szkieletowe i ścięgna (opcja D) to tkanki wysoko zróżnicowane, o niskiej wrażliwości na promieniowanie. Rogówka i twardówka oka (opcja E) — soczewka oka faktycznie jest wrażliwa (zaćma popromienna), ale rogówka/twardówka nie należą do klasycznie wymienianych najbardziej wrażliwych narządów.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Jaka jest przybliżona wartość SAR (Specific Absorption Rate) uznawana za graniczną dla wywołania znaczącego efektu cieplnego dla całego ciała?', answers: ['4 W/kg', '4W/kg'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Jaki jest podział stopni ODWODNIENIA organizmu wg niedoboru procentowego zawartości wody ogólnej?', o: ['Łagodne: 5%, średnie: 10%, ciężkie: 15%', 'Łagodne: 1%, średnie: 5%, ciężkie: 10%', 'Łagodne: 10%, średnie: 20%, ciężkie: 30%', 'Łagodne: 2%, średnie: 8%, ciężkie: 20%', 'Łagodne: 15%, średnie: 25%, ciężkie: 35%'], a: 0, rationale: 'Klasyczny podział stopni odwodnienia wg niedoboru procentowego całkowitej zawartości wody w organizmie to: łagodne 5%, średnie 10%, ciężkie 15%. Pozostałe opcje (B, C, D, E) podają inne, niepasujące do siebie kombinacje wartości procentowych — żadna nie odpowiada przyjętemu w materiale schematowi 5/10/15%.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Ile mililitrów wody powstaje z metabolizmu (utlenienia) 100 gramów TŁUSZCZÓW (woda oksydacyjna)?', answers: ['109 ml', '109'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Ile wynosi zalecane dzienne spożycie białka dla DOROSŁEGO MĘŻCZYZNY (na kg masy ciała)?', o: ['0,57 g/kg m.c.', '2,5 g/kg m.c.', '0,1 g/kg m.c.', '1,5 g/kg m.c.', '5 g/kg m.c.'], a: 0, rationale: 'Zalecane dzienne spożycie białka dla dorosłego mężczyzny wynosi 0,57 g/kg masy ciała (dla kobiety nieco mniej, 0,52 g/kg m.c.) — to standardowe wartości referencyjne dla populacji ogólnej, nie dla sportowców czy stanów zwiększonego zapotrzebowania. 2,5 g/kg (opcja B) i 1,5 g/kg (opcja D) to wartości znacznie zawyżone, bliższe zaleceniom dla intensywnie trenujących sportowców siłowych, nie przeciętnego dorosłego. 0,1 g/kg (opcja C) rażąco zaniża normę, poniżej jakiegokolwiek bezpiecznego minimum białkowego. 5 g/kg (opcja E) to wartość ekstremalnie, nierealistycznie zawyżona, znacznie przekraczająca jakiekolwiek zalecenia żywieniowe.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'O ile kcal/dobę zwiększa się zalecana kaloryczność diety kobiety ciężarnej w III TRYMESTRZE ciąży?', answers: ['475 kcal', '475'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'O ile kcal/dobę zwiększa się zalecana kaloryczność diety kobiety w okresie LAKTACJI?', answers: ['505 kcal', '505'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Przy jakich lekach/substancjach przyjmowanych przez matkę karmienie piersią jest PRZECIWWSKAZANE?', o: ['Lit, doksepina, leki psychotropowe', 'Paracetamol w standardowej dawce', 'Witaminy z grupy B', 'Preparaty żelaza doustne', 'Kwas foliowy'], a: 0, rationale: 'Karmienie piersią jest przeciwwskazane, jeśli matka jest leczona litem, doksepiną lub innymi lekami psychotropowymi — substancje te przenikają do mleka matki w ilościach mogących zaszkodzić dziecku. Paracetamol w standardowej dawce (opcja B) jest ogólnie uznawany za bezpieczny w okresie laktacji. Witaminy z grupy B (opcja C), preparaty żelaza (opcja D) i kwas foliowy (opcja E) to standardowo zalecane, a nie przeciwwskazane suplementy w okresie ciąży i laktacji.' },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Ile lat przechowywane są informacje o niepożądanych odczynach poszczepiennych (NOP)?', answers: ['10 lat', '10'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Przez ile godzin ważne jest zaświadczenie o stanie zdrowia wydane przed szczepieniem?', answers: ['24 godziny', '24h', '24 h'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'Ile lat trwa kadencja Państwowego Inspektora Sanitarnego?', answers: ['5 lat', '5'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'W którym roku odnotowano OSTATNI przypadek tężca noworodków w Polsce?', answers: ['1983', 'w 1983 roku'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', mode: 'typed', q: 'W którym roku wprowadzono w Polsce obowiązkowe szczepienia przeciw błonicy?', answers: ['1960', 'w 1960 roku'] },
  { category: 'Kompetencje generyczne — Higiena i epidemiologia', q: 'Kiedy zgodnie z polskim kalendarzem szczepień podaje się szczepienie BCG (przeciwgruźlicze) noworodkom?', o: ['W pierwszej dobie życia', 'W 2. miesiącu życia', 'W 6. miesiącu życia', 'W 12. miesiącu życia', 'Dopiero w wieku szkolnym'], a: 0, rationale: 'Szczepienie BCG (przeciwko gruźlicy) jest w Polsce obowiązkowe dla noworodków i podawane jest w pierwszej dobie życia, jeszcze na oddziale noworodkowym — to jedno z najwcześniej podawanych szczepień w kalendarzu. Podanie w 2. miesiącu (opcja B) odpowiada raczej rozpoczęciu szczepień z tzw. "szóstki" (błonica-tężec-krztusiec-Hib-WZW B-polio), nie BCG. 6. miesiąc (opcja C) i 12. miesiąc (opcja D) to zbyt późne terminy — BCG podaje się od razu po urodzeniu, właśnie po to, by ochronić niemowlę jak najwcześniej. Wiek szkolny (opcja E) jest zdecydowanie zbyt późny — noworodek byłby przez lata nieosłonięty przed gruźlicą.' },
];

const raw = JSON.parse(fs.readFileSync('fakultety_raw.json', 'utf8'));
items.forEach(item => raw.push(item));
fs.writeFileSync('fakultety_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'pytan. nowa dlugosc fakultety_raw.json:', raw.length);
