import fs from 'fs';

const items = [
  // ===== Z wejściówek (typed, otwarte pytania z odpowiedzią) =====
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Rozwiń skrót EBM.', answers: ['evidence based medicine', 'medycyna oparta na faktach', 'medycyna oparta na dowodach'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Rozwiń akronim PICOS (5 elementów precyzyjnego pytania badawczego) — podaj co oznacza litera P.', answers: ['patients', 'pacjenci', 'grupa pacjentów'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'W akronimie PICOS litera I oznacza:', answers: ['intervention', 'interwencja', 'metoda postępowania'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'W akronimie PICOS litera O oznacza:', answers: ['outcome', 'punkt końcowy', 'sposób mierzenia efektów'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Co to jest confounding bias (błąd zmiennej zakłócającej)?', answers: ['błąd interpretacji wynikający z istnienia czynnika wpływającego jednocześnie na zmienną badaną i punkt końcowy', 'zmienna zakłócająca wpływa na obie badane zmienne, imitując fałszywy związek przyczynowy'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Jak nazywa się próba, w której ani lekarz, ani pacjent, ani osoba analizująca wyniki nie wie, do której grupy trafił pacjent?', answers: ['próba potrójnie ślepa', 'potrójnie ślepa próba', 'triple blind', 'badanie potrójnie zaślepione'] },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Które badanie ma NAJNIŻSZĄ jakość dowodów naukowych w hierarchii EBM spośród wymienionych?', o: ['Opis przypadku (case study)', 'Randomizowane badanie kontrolowane (RCT)', 'Przegląd systematyczny z metaanalizą', 'Badanie kohortowe', 'Badanie kliniczno-kontrolne'], a: 0, rationale: 'Opis przypadku (case study/case report) znajduje się na samym dole hierarchii dowodów naukowych EBM — dotyczy pojedynczego pacjenta lub małej serii, bez grupy kontrolnej i bez możliwości wnioskowania o związkach przyczynowych. Przegląd systematyczny z metaanalizą (opcja C) jest na szczycie hierarchii — łączy wyniki wielu badań RCT. RCT (opcja B) jest złotym standardem pojedynczego badania interwencyjnego, wyżej niż opisy przypadków. Badanie kohortowe (opcja D) i kliniczno-kontrolne (opcja E) to badania obserwacyjne — słabsze niż RCT, ale silniejsze dowodowo niż pojedynczy opis przypadku, bo mają grupę porównawczą.' },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Jaki rodzaj błędu (bias) wynika z niedokładnego przypomnienia sobie przez pacjenta narażenia lub punktów końcowych ze względu na długi czas, jaki minął od ich wystąpienia?', answers: ['recall bias', 'błąd przypominania', 'błąd pamięci'] },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Jaki jest typowy stosunek średniej i mediany w ROZKŁADZIE NORMALNYM cechy ciągłej?', o: ['Średnia = mediana', 'Średnia > mediana zawsze', 'Średnia < mediana zawsze', 'Nie ma między nimi żadnej relacji w rozkładzie normalnym', 'Mediana zawsze równa się odchyleniu standardowemu'], a: 0, rationale: 'W idealnym rozkładzie normalnym (symetrycznym) średnia arytmetyczna i mediana są sobie równe — to jedna z definiujących cech tego rozkładu. Nierówność średnia≠mediana (opcje B, C) jest typowa dla rozkładów SKOŚNYCH (asymetrycznych), nie normalnych — np. przy prawoskośnym rozkładzie średnia > mediana. Opcja D jest nieprawdziwa — w rozkładzie normalnym ta relacja jest ściśle określona (równość), a nie przypadkowa. Opcja E miesza dwa zupełnie różne pojęcia — medianę (miara położenia/tendencji centralnej) i odchylenie standardowe (miara rozproszenia) — nie ma między nimi takiej zależności.' },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Która miara tendencji centralnej jest BARDZIEJ ODPORNA (oporna) na wartości odstające (skrajne)?', o: ['Mediana', 'Średnia arytmetyczna', 'Obie są jednakowo odporne na wartości odstające', 'Odchylenie standardowe', 'Żadna z miar tendencji centralnej nie jest odporna na wartości odstające'], a: 0, rationale: 'Mediana (wartość środkowa uporządkowanego zbioru) jest znacznie bardziej odporna na wartości odstające niż średnia arytmetyczna, bo pojedyncza ekstremalna wartość nie zmienia jej istotnie — liczy się tylko pozycja w kolejności, nie sama wartość skrajna. Średnia arytmetyczna (opcja B) jest WRAŻLIWA na wartości odstające, bo każda wartość, także skrajna, bezpośrednio wpływa na jej wynik przez sumowanie. Opcja C jest nieprawdziwa — to właśnie różnica w odporności na wartości odstające jest kluczową różnicą między tymi dwiema miarami. Odchylenie standardowe (opcja D) to w ogóle nie miara tendencji centralnej, tylko miara rozproszenia danych — nieprawidłowa kategoria. Opcja E jest sprzeczna z faktem, że mediana z definicji jest właśnie miarą odporną (resistant statistic).' },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Jaka jest hipoteza alternatywna testu Shapiro-Wilka?', answers: ['rozkład zmiennej odbiega od rozkładu normalnego', 'rozkład nie jest normalny', 'badana zmienna nie ma rozkładu normalnego'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Jakiego testu statystycznego używamy do zbadania NORMALNOŚCI rozkładu zmiennej ciągłej?', answers: ['test Shapiro-Wilka', 'Shapiro-Wilk'] },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Jakich testów statystycznych można użyć do porównania DWÓCH GRUP NIEZALEŻNYCH zmiennych ciągłych?', o: ['Test t-Studenta (dla par niezależnych) i test Manna-Whitneya (Wilcoxona)', 'Test chi-kwadrat i test Fishera', 'ANOVA i test post hoc', 'Korelacja Pearsona i korelacja Spearmana', 'Test Shapiro-Wilka i test Kołmogorowa-Smirnowa'], a: 0, rationale: 'Do porównania dwóch niezależnych grup zmiennych ciągłych stosuje się test t-Studenta dla prób niezależnych (gdy dane mają rozkład normalny) lub jego nieparametryczny odpowiednik — test U Manna-Whitneya (nazywany też testem Wilcoxona dla prób niezależnych), gdy założenie normalności nie jest spełnione. Opcja B (chi-kwadrat, Fisher) to testy do zmiennych KATEGORIALNYCH/jakościowych, nie ciągłych. Opcja C (ANOVA) służy do porównania WIĘCEJ NIŻ DWÓCH grup, nie dokładnie dwóch. Opcja D (korelacje Pearsona/Spearmana) mierzą ZWIĄZEK między dwiema zmiennymi ciągłymi u tych samych obiektów, a nie porównanie dwóch niezależnych grup. Opcja E (Shapiro-Wilk, Kołmogorow-Smirnow) to testy sprawdzające NORMALNOŚĆ rozkładu, a nie porównujące dwie grupy między sobą.' },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Kiedy stosuje się (nieparametryczny) test U Manna-Whitneya zamiast testu t-Studenta?', answers: ['gdy dane nie mają rozkładu normalnego', 'gdy założenie o normalności rozkładu nie jest spełnione', 'przy braku rozkładu normalnego zmiennej'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Rozwiń skrót NNT i wyjaśnij krótko, co oznacza.', answers: ['number needed to treat - liczba pacjentów, których trzeba leczyć, aby zapobiec jednemu niekorzystnemu punktowi końcowemu', 'liczba osób do leczenia, żeby uzyskać jeden dodatkowy pozytywny efekt'] },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Porównując dwa leki na podstawie wskaźnika NNT (number needed to treat), który lek uznajemy za LEPSZY (skuteczniejszy)?', o: ['Ten o NIŻSZEJ wartości NNT', 'Ten o WYŻSZEJ wartości NNT', 'Zawsze ten o NNT równym dokładnie 1', 'NNT nie pozwala porównywać skuteczności leków', 'Ten, którego NNT jest ujemne'], a: 0, rationale: 'Niższa wartość NNT oznacza, że trzeba leczyć MNIEJ pacjentów, aby uzyskać jeden dodatkowy korzystny efekt — a więc lek jest skuteczniejszy. Wyższe NNT (opcja B) oznacza mniejszą skuteczność — trzeba leczyć więcej osób dla tego samego efektu, więc to przeciwieństwo prawidłowej interpretacji. Opcja C błędnie sugeruje jeden magiczny próg (NNT=1) jako kryterium — w praktyce porównuje się WARTOŚCI NNT dwóch leków względem siebie, nie do jednej stałej liczby. Opcja D jest nieprawdziwa — NNT to właśnie narzędzie stworzone do porównywania praktycznej skuteczności interwencji. Opcja E jest bezsensowna klinicznie — NNT jako liczba pacjentów do leczenia nie przyjmuje wartości ujemnych w typowej interpretacji korzyści terapeutycznej.' },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Do czego służy metoda Kaplana-Meiera?', answers: ['do szacowania/przedstawiania funkcji przeżycia w czasie', 'do oceny prawdopodobieństwa przeżycia (analizy przeżycia)', 'do graficznej reprezentacji skumulowanego prawdopodobieństwa przeżycia w czasie'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Po co stosuje się poprawkę Bonferroniego?', answers: ['do korekty poziomu istotności przy porównaniach wielokrotnych, żeby zmniejszyć ryzyko błędu I rodzaju', 'zapobiega fałszywie dodatnim wynikom przy wielokrotnym testowaniu hipotez'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Kiedy stosuje się ANOVA (analizę wariancji)?', answers: ['do porównania średnich w więcej niż dwóch grupach', 'gdy porównujemy trzy lub więcej grup niezależnych zmiennych ciągłych'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Do czego służy test post hoc (wykonywany po ANOVA)?', answers: ['do sprawdzenia, KTÓRE konkretnie grupy różnią się istotnie między sobą po wykazaniu istotności w ANOVA', 'do porównań parami między grupami po stwierdzeniu ogólnej istotności w analizie wariancji'] },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Jakiej analizy wieloczynnikowej użyłbyś, żeby sprawdzić WSPÓLNY, niezależny wpływ wieku, BMI i płci na wystąpienie cukrzycy (cechy binarnej: choruje/nie choruje)?', o: ['Regresja logistyczna', 'Regresja liniowa', 'Test t-Studenta', 'ANOVA jednoczynnikowa', 'Korelacja Pearsona'], a: 0, rationale: 'Regresja logistyczna to metoda analizy wieloczynnikowej stosowana, gdy zmienna zależna jest BINARNA (dychotomiczna, np. choruje/nie choruje na cukrzycę) i chcemy ocenić niezależny wpływ kilku zmiennych niezależnych (wiek, BMI, płeć) jednocześnie. Regresja liniowa (opcja B) wymaga zmiennej zależnej CIĄGŁEJ, nie binarnej — niepoprawna do przewidywania choroby jako "tak/nie". Test t-Studenta (opcja C) porównuje średnie w dwóch grupach, nie ocenia jednoczesnego wpływu wielu zmiennych niezależnych. ANOVA jednoczynnikowa (opcja D) analizuje wpływ TYLKO JEDNEGO czynnika grupującego na zmienną ciągłą — nie pasuje ani do wielu czynników, ani do zmiennej binarnej. Korelacja Pearsona (opcja E) mierzy siłę związku między DWIEMA zmiennymi ciągłymi, nie analizuje wielu czynników jednocześnie ani zmiennej binarnej.' },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Technika analityczna pozwalająca ocenić wpływ wielu czynników na czas do wystąpienia punktu końcowego, z uwzględnieniem obserwacji uciętych (cenzurowanych), to:', o: ['Regresja Coxa', 'Regresja logistyczna', 'Test log-rank', 'Klasteryzacja metodą k-średnich', 'Sztuczna sieć neuronowa'], a: 0, rationale: 'Regresja Coxa (proporcjonalnych hazardów) to standardowa metoda wieloczynnikowej analizy przeżycia, uwzględniająca obserwacje ucięte (cenzurowane) — czyli pacjentów, u których zdarzenie nie wystąpiło w trakcie obserwacji. Regresja logistyczna (opcja B) NIE uwzględnia CZASU do zdarzenia ani cenzurowania — ocenia tylko, czy zdarzenie wystąpiło, bez informacji "kiedy". Test log-rank (opcja C) porównuje krzywe przeżycia MIĘDZY GRUPAMI (np. dwoma ramionami badania), ale nie ocenia wpływu WIELU czynników jednocześnie jak regresja Coxa. Klasteryzacja k-średnich (opcja D) to technika nienadzorowanego grupowania danych, niezwiązana z analizą czasu do zdarzenia. Sztuczna sieć neuronowa (opcja E) to ogólna technika uczenia maszynowego, nie standardowa, klasyczna metoda analizy przeżycia w biostatystyce medycznej.' },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'W jednoczynnikowej analizie regresji Coxa uzyskano HR=1,2 z przedziałem ufności 95% CI: 0,98–1,37. Jak należy zinterpretować ten wynik?', o: ['Wynik NIE jest istotny statystycznie, ponieważ przedział ufności obejmuje wartość 1', 'Wynik jest istotny statystycznie, bo HR jest większe od 1', 'Wynik jest istotny statystycznie, bo przedział ufności jest wąski', 'Nie można nic powiedzieć o istotności bez znajomości wartości p', 'Wynik jest istotny statystycznie tylko jeśli HR przekracza 2,0'], a: 0, rationale: 'Gdy 95% przedział ufności dla hazard ratio (HR) OBEJMUJE wartość 1 (czyli dolna granica <1, a górna >1, tak jak tu: 0,98–1,37), oznacza to, że wynik NIE jest istotny statystycznie — nie można wykluczyć braku efektu (HR=1 oznacza brak różnicy ryzyka między grupami). Sama wartość HR>1 (opcja B) nie wystarcza do stwierdzenia istotności — trzeba sprawdzić, czy przedział ufności nie zawiera 1, a tu zawiera. Opcja C błędnie ocenia "wąskość" przedziału jako kryterium istotności — kluczowe jest to, CZY przedział przekracza wartość 1, nie jego szerokość. Opcja D jest nieprawdziwe — przedział ufności SAM W SOBIE (bez osobnej wartości p) już pozwala ocenić istotność statystyczną na poziomie odpowiadającym p<0,05. Opcja E wymyśla arbitralny, nieprawdziwy próg HR=2,0 jako kryterium istotności — istotność statystyczna zależy od przedziału ufności względem 1, nie od konkretnej wartości granicznej HR.' },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Czym jest błąd (statystyczny) II rodzaju?', answers: ['błędne przyjęcie hipotezy zerowej, gdy w rzeczywistości jest ona fałszywa', 'nieodrzucenie hipotezy zerowej mimo że jest nieprawdziwa (fałszywie ujemny wynik)'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Czym jest moc statystyczna (1-β) badania?', answers: ['prawdopodobieństwo poprawnego odrzucenia fałszywej hipotezy zerowej', 'zdolność testu do wykrycia rzeczywistego efektu, jeśli on istnieje'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Jakiego rodzaju skali statystycznej NIE można dzielić i nie musi mieć wartości 0 absolutnego — interwałowa czy ilorazowa (stosunkowa)?', answers: ['interwałowa', 'skala interwałowa'] },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Podaj po jednym przykładzie zmiennej: nominalnej, porządkowej i ciągłej.', answers: ['płeć (nominalna), skala Apgar (porządkowa), BMI (ciągła)', 'kolor oczu (nominalna), skala Apgar (porządkowa), stężenie glukozy (ciągła)'] },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Które badanie dostarcza NAJLEPSZEJ jakości dowodów naukowych?', o: ['Metaanaliza badań randomizowanych', 'Pojedyncze badanie kliniczno-kontrolne', 'Opis serii przypadków', 'Pojedyncze badanie kohortowe', 'Opinia eksperta bez podstaw badawczych'], a: 0, rationale: 'Metaanaliza łącząca wyniki wielu badań randomizowanych (RCT) stoi na samym szczycie hierarchii dowodów naukowych EBM — łączy statystyczną moc wielu niezależnych, dobrze zaprojektowanych badań. Pojedyncze badanie kliniczno-kontrolne (opcja B) i kohortowe (opcja D) to badania obserwacyjne, z definicji słabsze dowodowo niż zsumowane RCT. Opis serii przypadków (opcja C) i opinia eksperta (opcja E) znajdują się na samym dole hierarchii — brak grupy kontrolnej, brak randomizacji, wysokie ryzyko błędu systematycznego.' },
  { category: 'Kompetencje generyczne — Biostatystyka', mode: 'typed', q: 'Jaki rodzaj zakłócenia (bias) polega na tym, że wykrycie choroby jest wcześniejsze dzięki badaniom przesiewowym, co sztucznie wydłuża pozorny czas przeżycia od rozpoznania, bez realnego wpływu na czas zgonu?', answers: ['lead time bias', 'błąd wyprzedzenia czasowego'] },
  { category: 'Kompetencje generyczne — Biostatystyka', q: 'Które DWIE spośród poniższych technik pozwalają walczyć z NADMIERNYM DOPASOWANIEM (overfitting) modelu?', o: ['Walidacja na niezależnym zbiorze danych oraz redukcja liczby zmiennych w modelu', 'Zwiększenie liczby zmiennych w modelu oraz zmniejszenie wielkości próby', 'Usunięcie walidacji krzyżowej oraz zwiększenie złożoności modelu', 'Ignorowanie wyników walidacji oraz trenowanie tylko na całym dostępnym zbiorze danych', 'Zmniejszenie liczebności grupy kontrolnej oraz pominięcie testów statystycznych'], a: 0, rationale: 'Walidacja na niezależnym zbiorze danych (np. walidacja V-krotna/k-fold, lub zbiór zebrany w innym ośrodku) oraz redukcja zbioru zmiennych (selekcja tylko istotnych predyktorów) to standardowe, sprawdzone metody ograniczania nadmiernego dopasowania modelu do danych treningowych. Opcja B proponuje dokładnie odwrotne działania — zwiększenie liczby zmiennych PRZY mniejszej próbie to klasyczna PRZYCZYNA overfittingu, nie sposób jego zapobiegania. Opcja C (usunięcie walidacji krzyżowej, zwiększenie złożoności) to również działania POGŁĘBIAJĄCE problem nadmiernego dopasowania, nie zapobiegające mu. Opcja D (ignorowanie walidacji, trening na całości danych bez podziału) to typowy błąd metodologiczny prowadzący prosto do przeuczenia modelu. Opcja E (mniejsza grupa kontrolna, brak testów statystycznych) nie ma nic wspólnego z zapobieganiem nadmiernemu dopasowaniu — to ogólne osłabienie jakości metodologicznej badania.' },
];

const raw = JSON.parse(fs.readFileSync('fakultety_raw.json', 'utf8'));
items.forEach(item => raw.push(item));
fs.writeFileSync('fakultety_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'pytan. nowa dlugosc fakultety_raw.json:', raw.length);
