import fs from 'fs';

const items = [
  { category: 'Kompetencje generyczne — Socjologia', q: 'Wnioskowanie od szczegółu do ogółu to:', o: ['Obdukcja', 'Enumeracja', 'Abdukcja', 'Indukcja', 'Dedukcja'], a: 3, rationale: 'Indukcja to rozumowanie prowadzące od SZCZEGÓŁU do OGÓŁU — na podstawie obserwacji pojedynczych przypadków formułuje się ogólny wniosek/prawidłowość. Obdukcja (opcja A) to zupełnie inne pojęcie — medyczno-prawne badanie zwłok/obrażeń, niezwiązane z logiką wnioskowania. Enumeracja (opcja B) to wyliczanie/wymienianie elementów zbioru, nie kierunek wnioskowania logicznego. Abdukcja (opcja C) to rozumowanie polegające na wysuwaniu najbardziej prawdopodobnego wyjaśnienia obserwacji (rozumowanie explanacyjne), różne od klasycznej indukcji. Dedukcja (opcja E) to kierunek dokładnie PRZECIWNY — wnioskowanie od ogółu (prawa ogólnego) do szczegółu (konkretnego przypadku).' },
  { category: 'Kompetencje generyczne — Socjologia', q: 'Religia, która wpływa w sposób NIEUŚWIADOMIONY na codzienne postępowanie danej zbiorowości, to element kultury:', o: ['Widzialnej', 'Materialnej', 'Niewidzialnej', 'Wysokiej', 'Głębokiej'], a: 4, rationale: 'Kultura głęboka to warstwa kultury działająca w sposób NIEUŚWIADOMIONY — normy, wartości i wierzenia (w tym religia) wpływające na zachowanie zbiorowości bez pełnej świadomości tego wpływu przez jej członków. Kultura widzialna (opcja A) i materialna (opcja B) odnoszą się do jawnych, obserwowalnych wytworów (przedmioty, zachowania, symbole) — przeciwieństwo nieuświadomionego wpływu. Kultura niewidzialna (opcja C) bywa pojęciem bliskim kulturze głębokiej, ale w klasyfikacji zastosowanej w tym materiale to WŁAŚNIE "głęboka" była wskazana jako prawidłowa odpowiedź, nie "niewidzialna" — to rozróżnienie terminologiczne, na które trzeba uważać na egzaminie. Kultura wysoka (opcja D) to zupełnie inne pojęcie — dotyczy elitarnych, wyrafinowanych wytworów kultury (sztuka, literatura), nie mechanizmu nieuświadomionego wpływu na zachowanie.' },
  { category: 'Kompetencje generyczne — Socjologia', q: 'Które ze stwierdzeń NIE pasuje do MEDYCZNEGO modelu niepełnosprawności?', o: ['Nie może dostać się do budynku przez brak windy', 'Oczekuje pomocy ze strony innych', 'Nie może chodzić', 'Jest niewidomy', 'Przykuty do wózka'], a: 0, rationale: 'Medyczny model niepełnosprawności skupia się na CIELE i deficycie SAMEJ OSOBY (choroba, uszkodzenie, ograniczenie funkcji) jako źródle niepełnosprawności. Stwierdzenie "nie może dostać się do budynku przez brak windy" opisuje BARIERĘ ŚRODOWISKOWĄ (brak dostosowania budynku) jako przyczynę ograniczenia — to jest właśnie istota SPOŁECZNEGO (nie medycznego) modelu niepełnosprawności, gdzie problemem jest niedostosowane otoczenie, a nie sama osoba. Pozostałe opcje (B, C, D, E) opisują ograniczenia wynikające bezpośrednio z ciała/funkcji osoby (niemożność chodzenia, ślepota, zależność od wózka, oczekiwanie pomocy) — dokładnie pasują do medycznego, "deficytowego" ujęcia niepełnosprawności.' },
  { category: 'Kompetencje generyczne — Socjologia', q: 'Ograniczenie słuchu uniemożliwiające efektywną komunikację to:', o: ['Szum znaczeniowy', 'Szum semantyczny', 'Szum fizyczny', 'Szum medialny', 'Szum psychiczny'], a: 2, rationale: 'Szum fizyczny to zakłócenie komunikacji wynikające z fizycznej przeszkody w kanale przekazu — w tym przypadku ograniczenie słuchu odbiorcy, uniemożliwiające mu odebranie sygnału dźwiękowego. Szum semantyczny (opcje A i B — to w istocie synonimy tego samego pojęcia w teorii komunikacji) dotyczy zakłóceń wynikających z RÓŻNEGO ROZUMIENIA znaczenia słów/symboli przez nadawcę i odbiorcę, nie z fizycznej niesprawności zmysłu. Szum medialny (opcja D) nie jest standardowym, klasycznym pojęciem z teorii szumów komunikacyjnych w tym kontekście. Szum psychiczny (opcja E) dotyczyłby zakłóceń wynikających ze stanu emocjonalnego/nastawienia rozmówców, nie fizycznego ograniczenia zmysłu słuchu.' },
  { category: 'Kompetencje generyczne — Socjologia', q: 'Posługiwanie się przestrzenią (dystansem interpersonalnym) w komunikacji niewerbalnej to:', o: ['Wokalika', 'Haptyka', 'Kinezyka', 'Chronemika', 'Proksemika'], a: 4, rationale: 'Proksemika to dział komunikacji niewerbalnej zajmujący się posługiwaniem się PRZESTRZENIĄ i dystansem interpersonalnym między rozmówcami. Wokalika (opcja A) dotyczy niewerbalnych aspektów GŁOSU (ton, tempo, głośność mowy), nie przestrzeni. Haptyka (opcja B) dotyczy komunikacji przez DOTYK (np. uścisk dłoni, poklepanie), inny kanał niż przestrzeń. Kinezyka (opcja C) dotyczy RUCHÓW CIAŁA, gestów i mimiki, nie samego dystansu przestrzennego. Chronemika (opcja D) dotyczy sposobu posługiwania się CZASEM w komunikacji (np. punktualność, długość pauz), zupełnie inny wymiar niż przestrzeń fizyczna.' },
  { category: 'Kompetencje generyczne — Socjologia', q: 'Anthony Giddens to przedstawiciel:', o: ['Etnometodologii', 'Funkcjonalizmu', 'Strukturalizmu', 'Interakcjonizmu symbolicznego', 'Teorii konfliktu'], a: 2, rationale: 'Anthony Giddens (twórca m.in. teorii strukturacji) jest zaliczany do przedstawicieli nurtu strukturalistycznego w socjologii — jego teoria strukturacji łączy analizę struktur społecznych z działaniem jednostek. Etnometodologia (opcja A) to nurt związany raczej z Haroldem Garfinkelem, badający codzienne metody konstruowania sensu w interakcjach. Funkcjonalizm (opcja B) kojarzony jest głównie z Talcottem Parsonsem i Robertem Mertonem, analizującymi społeczeństwo przez pryzmat funkcji jego elementów. Interakcjonizm symboliczny (opcja D) wiąże się przede wszystkim z George’em Herbertem Meadem i Herbertem Blumerem, skupiającymi się na znaczeniach tworzonych w interakcji. Teoria konfliktu (opcja E) kojarzona jest klasycznie z Karlem Marksem i późniejszymi teoretykami konfliktu społecznego, nie bezpośrednio z Giddensem.' },
];

const raw = JSON.parse(fs.readFileSync('fakultety_raw.json', 'utf8'));
items.forEach(item => raw.push(item));
fs.writeFileSync('fakultety_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'pytan. nowa dlugosc fakultety_raw.json:', raw.length);
