# -*- coding: utf-8 -*-
# Farmakologia (Rok 3) - nowy przedmiot od zera, pierwsza runda.
# Źródło: GIEŁDY TEGOROCZNE/Farmakologia/Teoria/"FARMAKOLOGIA TEORIA TERMIN I
# 26.06.2026.pdf" (sesja letnia) - bardzo bogaty, zaawansowany bank pytań (2 tury,
# ~150 pozycji), wysoka jakość recall z jasnymi odpowiedziami.
# UWAGA: pominięto celowo materiały z KOLOKWIA/Oficyny we własnym folderze
# przedmiotu ("odpowiedzi do pytań studentów", "Pytania do Oficyn") - to są
# administracyjne Q&A o ZASADACH PISANIA RECEPT na tym konkretnym kursie
# (konwencje formatowania, punktacja), NIE portable wiedza farmakologiczna
# nadająca się na pytania testowe. Pominięto też PODRĘCZNIKI (1,17GB) i SKRYPTY
# (157MB) - prawdopodobnie zeskanowane/komercyjne, wymagałyby osobnej rundy
# z przeglądem wizualnym.
import json

ITEMS = [
    # --- Farmakokinetyka — podstawy ---
    {"category": "Farmakokinetyka — podstawy", "q": "Jeśli okres półtrwania (T1/2) leku wynosi 30h, to po jakim czasie lek praktycznie zniknie z organizmu?",
     "mode": "typed", "answers": ["po ok. 120-150h (potrzeba ok. 5 okresów półtrwania do eliminacji)"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Lek podawany dożylnie ma okres półtrwania 6h. Po jakim czasie osiągnie stężenie stacjonarne (stan stacjonarny)?",
     "mode": "typed", "answers": ["po ok. 24-30h (ok. 5 okresów półtrwania)"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Dlaczego lek będący słabym kwasem najlepiej wchłania się w żołądku?",
     "mode": "typed", "answers": ["w kwaśnym pH żołądka występuje w formie niezjonizowanej, lepiej przenikającej przez błony"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Co oznacza bardzo niska pozorna objętość dystrybucji (Vd) leku?",
     "mode": "typed", "answers": ["lek pozostaje głównie w osoczu krwi, słabo przenika do tkanek"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Jak wpłynie zaawansowany stan zapalny na działanie leków miejscowo znieczulających?",
     "mode": "typed", "answers": ["obniżone pH w miejscu zapalenia zwiększa udział formy zjonizowanej (kationowej), co pogarsza przenikanie leku przez błony i osłabia jego działanie"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Jakie etapy LADME dotyczą gentamycyny podanej dożylnie?",
     "mode": "typed", "answers": ["dystrybucja i wydalanie (pomija się wchłanianie i metabolizm — podanie i.v., lek nie jest metabolizowany)"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Dlaczego nie wolno rozgryzać ani kruszyć tabletek morfiny o kontrolowanym uwalnianiu?",
     "mode": "typed", "answers": ["prowadzi to do jednorazowego uwolnienia całej dawki leku, co może wywołać groźną depresję ośrodka oddechowego"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Czym różnią się tabletki o natychmiastowym uwalnianiu od tabletek o przedłużonym uwalnianiu pod względem farmakokinetyki?",
     "mode": "typed", "answers": ["tabletki o przedłużonym uwalnianiu mają wolniejsze wchłanianie/eliminację pozorną (dłużej utrzymują stężenie terapeutyczne)"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Ciągłe (przewlekłe) podawanie agonisty receptora α1 prowadzi do:",
     "mode": "typed", "answers": ["desensytyzacji (down-regulacji) receptorów"]},

    # --- Antybiotyki i chemioterapeutyki przeciwbakteryjne ---
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Dlaczego do imipenemu dodaje się cylastatynę?",
     "mode": "typed", "answers": ["cylastatyna hamuje dehydropeptydazę nerkową, zapobiegając rozkładowi imipenemu w nerkach i zwiększając jego skuteczność"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Która cefalosporyna wiąże żelazo i dzięki temu wnika do wnętrza bakterii (mechanizm \"konia trojańskiego\")?",
     "mode": "typed", "answers": ["cefiderokol"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Która penicylina może być podawana domięśniowo raz na 7-14 dni?",
     "mode": "typed", "answers": ["penicylina benzatynowa (benzylpenicylina benzatynowa)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Na co działa antybiotyk aztreonam?",
     "mode": "typed", "answers": ["tylko na bakterie Gram-ujemne tlenowe (nie działa na Gram-dodatnie ani beztlenowce)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Jaki antybiotyk jest skuteczny na Acinetobacter baumannii dzięki własnej aktywności przeciwbakteryjnej (poza rolą inhibitora beta-laktamaz)?",
     "mode": "typed", "answers": ["sulbaktam"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Wskaż antybiotyki o działaniu BÓJCZYM (nie tylko bakteriostatycznym).",
     "mode": "typed", "answers": ["cefalosporyny, wankomycyna, fosfomycyna (a także np. aminoglikozydy, penicyliny)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Które antybiotyki mogą nasilać objawy miastenii (myasthenia gravis)?",
     "mode": "typed", "answers": ["aminoglikozydy (np. gentamycyna) i klindamycyna (blokują przewodnictwo nerwowo-mięśniowe)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Który antybiotyk może wywołać zespół serotoninowy (działając jako inhibitor MAO)?",
     "mode": "typed", "answers": ["linezolid"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Który antybiotyk działa na podjednostkę rybosomalną 30S i jest skuteczny wobec bakterii Gram-dodatnich, będąc glicylocykliną (pochodną tetracyklin)?",
     "mode": "typed", "answers": ["tygecyklina"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Które antybiotyki przeciwnowotworowe (antracykliny/glikopeptydy) powstają z bakterii z rodzaju Streptomyces?",
     "mode": "typed", "answers": ["bleomycyna, idarubicyna"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "W jakim mechanizmie zachodzi synergizm amfoterycyny B z flucytozyną?",
     "mode": "typed", "answers": ["amfoterycyna B uszkadza błonę komórkową grzyba, ułatwiając wnikanie flucytozyny do komórki"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Jaki jest mechanizm działania terbinafiny?",
     "mode": "typed", "answers": ["inhibitor epoksydazy skwalenu — prowadzi do gromadzenia skwalenu toksycznego dla grzyba"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Jaki jest mechanizm działania flukonazolu?",
     "mode": "typed", "answers": ["hamowanie demetylazy lanosterolu (enzymu cytochromu P450 grzyba)"]},

    # --- Leki przeciwwirusowe ---
    {"category": "Leki przeciwwirusowe (HIV i inne)", "q": "Jaki jest mechanizm działania NRTI (nukleozydowych inhibitorów odwrotnej transkryptazy)?",
     "mode": "typed", "answers": ["po wniknięciu do komórki ulegają trifosforylacji i działają jako fałszywe substraty hamujące odwrotną transkryptazę, blokując powstawanie prowirusowego DNA"]},
    {"category": "Leki przeciwwirusowe (HIV i inne)", "q": "Co wyróżnia tenofowir spośród innych NRTI pod względem budowy?",
     "mode": "typed", "answers": ["posiada już jedną grupę fosforanową (jest analogiem nukleotydowym), więc wymaga tylko dwóch kolejnych fosforylacji zamiast trzech"]},
    {"category": "Leki przeciwwirusowe (HIV i inne)", "q": "Który lek jest inhibitorem integrazy HIV?",
     "mode": "typed", "answers": ["raltegrawir"]},

    # --- Układ sercowo-naczyniowy ---
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Który lek beta-adrenolityczny wykazuje wewnętrzną aktywność sympatykomimetyczną (ISA)?",
     "mode": "typed", "answers": ["acebutolol"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Który beta-bloker ma najkrótszy okres półtrwania?",
     "mode": "typed", "answers": ["esmolol"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaki jest mechanizm działania sotalolu i amiodaronu (leki antyarytmiczne klasy III)?",
     "mode": "typed", "answers": ["blokada kanałów potasowych"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jakie działania niepożądane charakterystyczne dla amiodaronu?",
     "mode": "typed", "answers": ["złogi rogówkowe oraz nadwrażliwość na światło (fotouczulenie)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaki lek jednocześnie zmniejsza zapotrzebowanie serca na tlen i zwalnia przewodzenie przedsionkowo-komorowe?",
     "mode": "typed", "answers": ["werapamil"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Do jakiej grupy leków (pod względem mechanizmu) jest najbliżej molsydominie?",
     "mode": "typed", "answers": ["azotanów (donory tlenku azotu)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaki jest mechanizm działania mannitolu w obrzęku mózgu?",
     "mode": "typed", "answers": ["zwiększa osmolalność krwi w naczyniach, przesuwając płyn z tkanki mózgowej do naczyń"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Dlaczego inhibitory konwertazy angiotensyny (IKA) nie powinny być podawane w obustronnym zwężeniu tętnic nerkowych?",
     "mode": "typed", "answers": ["powodują rozkurcz tętniczki odprowadzającej kłębuszka, co przy critycznym zwężeniu tętnicy nerkowej gwałtownie obniża GFR"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaki jest mechanizm działania urapidylu (efekt obwodowy)?",
     "mode": "typed", "answers": ["blokowanie receptorów α1-adrenergicznych"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jak zadziała duża dawka dopaminy (ok. 10 µg/kg/min)?",
     "mode": "typed", "answers": ["wywoła silny skurcz naczyń przez przeważające działanie na receptory α1"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Co się stanie, gdy podamy fenylefrynę dożylnie?",
     "mode": "typed", "answers": ["wystąpi odruchowa bradykardia (poprzez nerw błędny) w odpowiedzi na wzrost ciśnienia"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Co się stanie, jeśli podamy adrenalinę po wcześniejszym zablokowaniu receptorów α (\"epinephrine reversal\")?",
     "mode": "typed", "answers": ["zadziała głównie na receptory β2, wywołując rozszerzenie naczyń i spadek ciśnienia zamiast wzrostu"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaki jest mechanizm działania lewosimendanu?",
     "mode": "typed", "answers": ["uwrażliwia troponinę C na wapń (a także otwiera kanały potasowe ATP-zależne w naczyniach)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaki jest mechanizm działania sakubitrylu i walsartanu (lek złożony w niewydolności serca)?",
     "mode": "typed", "answers": ["sakubitryl hamuje neprylizynę (rozkładającą peptydy natriuretyczne), a walsartan blokuje receptor AT1 dla angiotensyny II"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Który lek na dławicę piersiową wymaga szczególnej ostrożności przy jednoczesnym stosowaniu klarytromycyny (silnego inhibitora CYP3A4)?",
     "mode": "typed", "answers": ["ranolazyna"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Iloprost — scharakteryzuj jego działanie.",
     "mode": "typed", "answers": ["jest analogiem prostacykliny, hamuje agregację płytek krwi, rozszerza naczynia i jest stosowany w nadciśnieniu płucnym"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jakie leki stosuje się w chromaniu przestankowym?",
     "mode": "typed", "answers": ["cylostazol i pentoksyfilina"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jakie leki poprawiają przewlekle ukrwienie mózgu?",
     "mode": "typed", "answers": ["nicergolina i winpocetyna"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaki jest mechanizm działania leku trombolitycznego stosowanego w zatorowości płucnej (np. alteplazy)?",
     "mode": "typed", "answers": ["aktywuje przemianę plazminogenu w plazminę, rozpuszczając skrzeplinę"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaki jest bezpośredni punkt uchwytu dabigatranu?",
     "mode": "typed", "answers": ["trombina (czynnik IIa) — bezpośredni inhibitor trombiny"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Jaka jest odtrutka na dabigatran i czym ona jest?",
     "mode": "typed", "answers": ["idarucyzumab — fragment przeciwciała monoklonalnego wiążący dabigatran"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Pacjentowi ma zostać podana warfaryna. Jakim lekiem zabezpieczamy go na kilka pierwszych dni terapii (\"pomost\")?",
     "mode": "typed", "answers": ["enoksaparyną (heparyną drobnocząsteczkową)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Po podaniu heparyny niefrakcjonowanej doszło do małopłytkowości poheparynowej (HIT). Na jaki lek zamienimy antykoagulację?",
     "mode": "typed", "answers": ["argatroban"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Pacjent po operacji z masywnym krwawieniem i małą liczbą płytek — czym zahamujesz krwawienie?",
     "mode": "typed", "answers": ["kwasem traneksamowym"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Który lek obniża stężenie triglicerydów przy prawidłowym LDL poprzez stymulację receptora PPAR-α?",
     "mode": "typed", "answers": ["fibrat (lek z grupy fibratów)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Pacjent przyjmujący statynę i ezetymib potrzebuje dodatkowego leku obniżającego frakcję LDL. Jaki lek i jaki mechanizm?",
     "mode": "typed", "answers": ["inhibitor PCSK9 (proproteinowej konwertazy subtylizyny/keksyny typu 9)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Który lek przeciwzakrzepowy jest odwracalnym, krótkodziałającym antagonistą receptora P2Y12, podawanym dożylnie?",
     "mode": "typed", "answers": ["kangrelor"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Statyna razem z daptomycyną — jakie ryzyko?",
     "mode": "typed", "answers": ["rabdomioliza i miopatia (addytywna toksyczność mięśniowa)"]},

    # --- Endokrynologia i cukrzyca ---
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jaki jest mechanizm działania flozyn (inhibitorów SGLT2)?",
     "mode": "typed", "answers": ["hamują reabsorpcję glukozy w kanaliku bliższym (proksymalnym) nerki"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jaka insulina jest stosowana jako bazalna i nie wymaga podawania przed posiłkiem?",
     "mode": "typed", "answers": ["insulina glargine"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jaka insulina jest typową insuliną doposiłkową, krótko działającą (analog szybkodziałający)?",
     "mode": "typed", "answers": ["insulina aspart"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jaki jest mechanizm działania metforminy obniżający produkcję glukozy w wątrobie (niezależnie od insuliny)?",
     "mode": "typed", "answers": ["hamowanie łańcucha oddechowego (kompleksu I mitochondrialnego) i aktywacja kinazy AMPK"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Który lek przeciwcukrzycowy (gliptyna) ma punktem uchwytu enzym DPP-4?",
     "mode": "typed", "answers": ["sitagliptyna (i inne gliptyny)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Który lek przeciwcukrzycowy zwiększa ryzyko infekcji górnych dróg oddechowych (zapalenia nosogardzieli)?",
     "mode": "typed", "answers": ["gliptyny (inhibitory DPP-4)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Którego leku przeciwcukrzycowego nie można podać choremu z niewydolnością serca i obrzękami?",
     "mode": "typed", "answers": ["pioglitazonu (tiazolidynediony nasilają retencję płynów)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Pacjent z ciężką hipoglikemią, u którego nie można podać węglowodanów doustnie — co podajemy?",
     "mode": "typed", "answers": ["glukagon"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "6-letnia dziewczynka z zespołem nadnerczowo-płciowym — jaki lek podać w celu uzupełnienia niedoboru mineralokortykoidów?",
     "mode": "typed", "answers": ["fludrokortyzon"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Pacjent z hiponatremią w przebiegu niewydolności nadnerczy — co podamy?",
     "mode": "typed", "answers": ["fludrokortyzon"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Który glikokortykosteroid o średnio-długim działaniu jest prolekiem?",
     "mode": "typed", "answers": ["prednizon (aktywowany w wątrobie do prednizolonu)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jaki jest mechanizm osteoporozy polekowej wywołanej glikokortykosteroidami?",
     "mode": "typed", "answers": ["zaburzenie gospodarki wapniowej — zmniejszone jelitowe wchłanianie wapnia i zwiększone jego wydalanie nerkowe"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jaki jest mechanizm działania teryparatydu w leczeniu osteoporozy?",
     "mode": "typed", "answers": ["pobudza osteoblasty do tworzenia nowej kości (działanie anaboliczne)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jaki jest mechanizm działania alendronianu (bisfosfonianu)?",
     "mode": "typed", "answers": ["wiąże się z hydroksyapatytem kości, hamując resorpcję kostną przez osteoklasty"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jak należy przyjmować alendronian (bisfosfonian doustny)?",
     "mode": "typed", "answers": ["na czczo, popić dużą ilością wody, a następnie pozostać w pozycji siedzącej lub stojącej przez min. 30 minut"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Który lek jest nieodwracalnym, steroidowym inhibitorem aromatazy?",
     "mode": "typed", "answers": ["eksemestan"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jaki jest mechanizm działania lewotyroksyny — po jakim czasie zaczyna działać klinicznie?",
     "mode": "typed", "answers": ["efekt kliniczny pojawia się po ok. 1-2 tygodniach"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Dlaczego nie można łączyć mitotanu ze spironolaktonem?",
     "mode": "typed", "answers": ["mitotan hamuje (osłabia) działanie spironolaktonu"]},

    # --- Nerki i gospodarka wodno-elektrolitowa ---
    {"category": "Nerki i gospodarka wodno-elektrolitowa — leki", "q": "Który lek jest selektywnym antagonistą receptora wazopresyny V2, stosowanym w hiponatremii?",
     "mode": "typed", "answers": ["tolwaptan"]},
    {"category": "Nerki i gospodarka wodno-elektrolitowa — leki", "q": "Jaki jest mechanizm działania leków pętlowych (np. furosemidu) w masywnych obrzękach?",
     "mode": "typed", "answers": ["hamowanie kotransportera Na+/K+/2Cl- w ramieniu wstępującym pętli Henlego"]},
    {"category": "Nerki i gospodarka wodno-elektrolitowa — leki", "q": "Który lek nasila utratę potasu podczas terapii furosemidem?",
     "mode": "typed", "answers": ["glikokortykosteroidy (np. prednizon) — nasilają kaliurezę"]},
    {"category": "Nerki i gospodarka wodno-elektrolitowa — leki", "q": "Furosemid podawany razem z jakim lekiem grozi uszkodzeniem narządu zmysłu (ototoksyczność)?",
     "mode": "typed", "answers": ["z aminoglikozydami (np. gentamycyną) — synergistyczna ototoksyczność"]},

    # --- Reumatologia i NLPZ ---
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Wskaż zdanie FAŁSZYWE o NLPZ: czy benzydamina jest podawana doustnie?",
     "mode": "typed", "answers": ["nie — benzydamina stosowana jest tylko miejscowo (twierdzenie o podaniu doustnym jest fałszywe)"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Który NLPZ jest preferencyjnym inhibitorem COX-2, długo działającym, gromadzącym się w stawach, o działaniu chondroprotekcyjnym i zmiatającym wolne rodniki?",
     "mode": "typed", "answers": ["meloksykam (chondroprotekcyjne działanie łączone też z nimesulidem w niektórych źródłach, ale klasyczna odpowiedź to meloksykam)"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Jaka jest maksymalna dobowa dawka ketoprofenu?",
     "mode": "typed", "answers": ["0,2 g (200 mg)"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Co się stanie po połączeniu ibuprofenu z ASA (kwasem acetylosalicylowym)?",
     "mode": "typed", "answers": ["ibuprofen konkurencyjnie blokuje dostęp ASA do centrum aktywnego COX-1, osłabiając nieodwracalne działanie przeciwpłytkowe ASA"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Wskaż zdanie FAŁSZYWE o paracetamolu.",
     "mode": "typed", "answers": ["paracetamol silnie hamuje syntezę prostaglandyn na obwodzie (to jest fałszywe — paracetamol działa głównie ośrodkowo, obwodowo bardzo słabo)"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Jaka jest maksymalna dobowa dawka paracetamolu u dzieci?",
     "mode": "typed", "answers": ["ok. 60 mg/kg m.c./dobę"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Który lek na RZS (reumatoidalne zapalenie stawów) ma także działanie przeciwpasożytnicze?",
     "mode": "typed", "answers": ["chlorochina"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Który lek stosowany długotrwale może prowadzić do utraty wzroku (retinopatii)?",
     "mode": "typed", "answers": ["chlorochina"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Jaki jest mechanizm działania tofacitinibu?",
     "mode": "typed", "answers": ["inhibitor kinaz JAK (Janus kinase)"]},

    # --- Ból i znieczulenie ---
    {"category": "Ból, opioidy i znieczulenie", "q": "Jaką zaletę ma tzw. efekt pułapowy (\"ceiling effect\") buprenorfiny?",
     "mode": "typed", "answers": ["efekt pułapowy dotyczy depresji oddechowej — po osiągnięciu pewnej dawki działanie to nie pogłębia się dalej"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jaki jest najsilniejszy opioid stosowany w znieczuleniu ogólnym?",
     "mode": "typed", "answers": ["sufentanyl"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jaki opioid podaje się donosowo w bólach przebijających u chorych onkologicznych?",
     "mode": "typed", "answers": ["fentanyl"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Który lek jest całkowitym antagonistą receptorów opioidowych o dobrej dostępności biologicznej po podaniu doustnym?",
     "mode": "typed", "answers": ["naltrekson"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jaki lek podaje się podskórnie na zaparcia wywołane opioidami (bez znoszenia efektu przeciwbólowego)?",
     "mode": "typed", "answers": ["metylnaltrekson"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Dlaczego dodaje się adrenalinę do lidokainy w znieczuleniu miejscowym?",
     "mode": "typed", "answers": ["zmniejsza wchłanianie lidokainy do krążenia ogólnego, przedłużając jej działanie miejscowe"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jakie jest ryzyko stosowania środków znieczulających miejscowo z adrenaliną w okolicach dystalnych (np. palce)?",
     "mode": "typed", "answers": ["martwica dystalnych części ciała wskutek silnego skurczu naczyń"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jak metabolizowane są leki znieczulenia miejscowego typu amidowego?",
     "mode": "typed", "answers": ["w wątrobie (enzymy mikrosomalne)"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Który lek zwiotczający mięśnie jest krótko działającym niedepolaryzującym środkiem stosowanym w znieczuleniu ogólnym?",
     "mode": "typed", "answers": ["miwakurium"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Działania którego leku zwiotczającego mięśnie NIE odwróci neostygmina?",
     "mode": "typed", "answers": ["suksametonium (lek depolaryzujący — neostygmina nie odwraca jego działania, a w bloku fazy II może je nasilić)"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jaki jest antagonista receptora NMDA o działaniu niekompetycyjnym, stosowany jako lek przeciwdepresyjny/anestetyk?",
     "mode": "typed", "answers": ["esketamina (a także memantyna w innym zastosowaniu)"]},

    # --- Układ oddechowy ---
    {"category": "Układ oddechowy — leki", "q": "Jak glikokortykosteroidy wpływają na receptory β2 w oskrzelach?",
     "mode": "typed", "answers": ["zwiększają liczbę (ekspresję) receptorów β2-adrenergicznych"]},
    {"category": "Układ oddechowy — leki", "q": "Który lek mukolityczny jest metabolizowany w wątrobie do aktywnej formy?",
     "mode": "typed", "answers": ["erdosteina"]},
    {"category": "Układ oddechowy — leki", "q": "Który lek mukolityczny pobudza wydzielanie sialomucyn (zwiększa nawodnienie śluzu)?",
     "mode": "typed", "answers": ["karbocysteina"]},
    {"category": "Układ oddechowy — leki", "q": "Jakie jest wskazanie do stosowania glikopironium podawanego DOUSTNIE?",
     "mode": "typed", "answers": ["nadmierne ślinienie się (ślinotok/sialorrhea)"]},
    {"category": "Układ oddechowy — leki", "q": "Jakie jest wskazanie do stosowania glikopironium w postaci KREMU?",
     "mode": "typed", "answers": ["nadpotliwość pach"]},

    # --- Przewód pokarmowy ---
    {"category": "Przewód pokarmowy — leki", "q": "Jakie jest działanie niepożądane długotrwałego (przewlekłego) stosowania inhibitorów pompy protonowej (IPP)?",
     "mode": "typed", "answers": ["niedobór witaminy B12, zwiększone ryzyko złamań/osteoporozy, hipomagnezemia"]},
    {"category": "Przewód pokarmowy — leki", "q": "Czym różni się itopryd od metoklopramidu?",
     "mode": "typed", "answers": ["itopryd nie przenika przez barierę krew-mózg (mniej działań pozapiramidowych niż metoklopramid)"]},
    {"category": "Przewód pokarmowy — leki", "q": "Jak działa laktuloza w jelicie?",
     "mode": "typed", "answers": ["jest syntetycznym dwucukrem (z galaktozy i fruktozy), rozkładanym w jelicie do kwasów organicznych i dwutlenku węgla; przeciwwskazana w galaktozemii"]},
    {"category": "Przewód pokarmowy — leki", "q": "Który środek przeczyszczający zadziała najszybciej?",
     "mode": "typed", "answers": ["fosforany podane doodbytniczo"]},
    {"category": "Przewód pokarmowy — leki", "q": "Jaki lek podamy pacjentowi z zespołem jelita drażliwego/zaparciami stosującemu jednocześnie itrakonazol, wiedząc że itrakonazol wymaga kwaśnego pH żołądka do wchłaniania — jaki lek pogorszy to wchłanianie?",
     "mode": "typed", "answers": ["inhibitor pompy protonowej (np. dekslanzoprazol) — alkalizując żołądek, zmniejsza wchłanianie itrakonazolu"]},

    # --- Układ nerwowy — leki psychotropowe i neurologiczne ---
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki jest mechanizm działania memantyny (lek na chorobę Alzheimera)?",
     "mode": "typed", "answers": ["niekompetycyjny antagonista receptora NMDA"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki jest mechanizm działania selegiliny?",
     "mode": "typed", "answers": ["nieodwracalny inhibitor MAO-B (stosowana w chorobie Parkinsona)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Który lek na chorobę Parkinsona jest dostępny w postaci plastrów przezskórnych?",
     "mode": "typed", "answers": ["rotygotyna"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Dlaczego lewodopę podaje się razem z karbidopą?",
     "mode": "typed", "answers": ["karbidopa blokuje obwodowy rozkład (dekarboksylację) lewodopy, zwiększając jej dostępność dla OUN i zmniejszając działania niepożądane obwodowe"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jak neuroleptyki atypowe (drugiej generacji) łagodzą objawy negatywne schizofrenii?",
     "mode": "typed", "answers": ["blokują receptory serotoninowe 5-HT2A w korze przedczołowej, pośrednio zwiększając uwalnianie dopaminy w tym rejonie"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Co jest prawdziwe o dyskinezach późnych (tardive dyskinesia)?",
     "mode": "typed", "answers": ["są skutkiem długotrwałej blokady receptorów D2 przez neuroleptyki (nadwrażliwość poreceptorowa)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki jest mechanizm powstawania ginekomastii wywołanej lekami przeciwpsychotycznymi?",
     "mode": "typed", "answers": ["blokada receptorów D2 w szlaku guzkowo-lejkowym (tuberoinfundibularnym), co znosi hamowanie wydzielania prolaktyny"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Który lek może powodować agranulocytozę jako istotne działanie niepożądane (spośród leków przeciwpłytkowych)?",
     "mode": "typed", "answers": ["tiklopidyna"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Które benzodiazepiny są zarejestrowane w Polsce do KRÓTKOTRWAŁEGO leczenia bezsenności?",
     "mode": "typed", "answers": ["estazolam"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Który lek anksjolityczny (niebenzodiazepinowy) może być stosowany długotrwale?",
     "mode": "typed", "answers": ["buspiron"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Który lek nasenny działa poprzez blokadę receptorów oreksynowych i jest pomocny przy wybudzaniu się w nocy?",
     "mode": "typed", "answers": ["daridoreksant"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki lek zastosujemy u agresywnego dziecka jako lek przeciwpsychotyczny?",
     "mode": "typed", "answers": ["rysperydon"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki jest mechanizm tachykardii po amitryptylinie?",
     "mode": "typed", "answers": ["odruchowa (kompensacyjna) tachykardia w odpowiedzi na hipotensję wywołaną blokadą receptorów α1"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Co podamy w ciężkim zatruciu trójpierścieniowymi lekami przeciwdepresyjnymi (TLPD) na ich działanie kardiotoksyczne?",
     "mode": "typed", "answers": ["wodorowęglan sodu"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jak wydalany jest lorazepam?",
     "mode": "typed", "answers": ["po sprzęgnięciu z kwasem glukuronowym, wydalany przez nerki"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki lek stosujemy w profilaktyce migreny?",
     "mode": "typed", "answers": ["topiramat"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki lek stosuje się doraźnie w ataku migreny?",
     "mode": "typed", "answers": ["tryptan (np. sumatryptan)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki lek jest skuteczny jednocześnie w bólu neuropatycznym i depresji?",
     "mode": "typed", "answers": ["duloksetyna"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki lek pomoże pacjentowi z zaburzeniami lękowymi, cukrzycą i bólem neuropatycznym jednocześnie?",
     "mode": "typed", "answers": ["pregabalina"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Na co działa modafinil?",
     "mode": "typed", "answers": ["narkolepsję (i towarzyszącą katapleksję)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki jest mechanizm działania naltreksonu w leczeniu uzależnienia od alkoholu?",
     "mode": "typed", "answers": ["blokuje ośrodek nagrody (receptory opioidowe), zmniejszając potrzebę spożywania alkoholu"]},

    # --- Alergologia ---
    {"category": "Alergologia — leki przeciwhistaminowe", "q": "Który lek przeciwhistaminowy podawany donosowo hamuje degranulację mastocytów?",
     "mode": "typed", "answers": ["ketotifen"]},
    {"category": "Alergologia — leki przeciwhistaminowe", "q": "Który lek przeciwhistaminowy stabilizuje komórki tuczne i jest stosowany miejscowo w alergicznym zapaleniu spojówek?",
     "mode": "typed", "answers": ["epinastyna"]},
    {"category": "Alergologia — leki przeciwhistaminowe", "q": "Jak SSRI (selektywne inhibitory wychwytu zwrotnego serotoniny) wpływają na krew?",
     "mode": "typed", "answers": ["zaburzają agregację płytek krwi, zwiększając ryzyko krwawień"]},

    # --- Pasożyty ---
    {"category": "Leki przeciwpasożytnicze", "q": "Jaki jest mechanizm działania pyrantelu?",
     "mode": "typed", "answers": ["działa jako agonista receptorów nikotynowych na płytce nerwowo-mięśniowej pasożyta, powodując depolaryzujący paraliż robaka"]},
    {"category": "Leki przeciwpasożytnicze", "q": "Co jest prawdziwe o albendazolu?",
     "mode": "typed", "answers": ["w wątrobie jest przekształcany do aktywnego sulfotlenku"]},

    # --- Onkologia — leki przeciwnowotworowe ---
    {"category": "Onkologia — leki przeciwnowotworowe", "q": "Który lek cytostatyczny (antybiotyk przeciwnowotworowy) nadaje moczowi czerwony kolor?",
     "mode": "typed", "answers": ["doksorubicyna"]},
    {"category": "Onkologia — leki przeciwnowotworowe", "q": "Który lek cytostatyczny może powodować krwotoczne zapalenie pęcherza moczowego?",
     "mode": "typed", "answers": ["cyklofosfamid"]},
    {"category": "Onkologia — leki przeciwnowotworowe", "q": "Jaki jest mechanizm działania alkaloidów barwinka (winkrystyny, winblastyny)?",
     "mode": "typed", "answers": ["hamowanie tworzenia (polimeryzacji) mikrotubul, blokując podział komórkowy w mitozie"]},
]

with open('farmakologia_raw.json', 'w', encoding='utf-8') as f:
    json.dump(ITEMS, f, ensure_ascii=False, indent=2)

by_cat = {}
for it in ITEMS:
    by_cat[it['category']] = by_cat.get(it['category'], 0) + 1
for c, n in sorted(by_cat.items()):
    print(n, '-', c)
print('TOTAL', len(ITEMS))
