# -*- coding: utf-8 -*-
# Farmakologia (Rok 3) - RUNDA 2. Źródła: pozostałe pliki GIEŁDY TEGOROCZNE/
# Farmakologia (obie sesje): Kolokwium I (Recepty/ukł.współczulny), Kolokwium II
# (Pokarmowy/Ból/GKS/Astma/POChP), Kolokwium III (krew/serce/cukrzyca),
# Kolokwium IV (antybiotyki/OUN), 2 kolokwia poprawkowe, Oficyny. Format inny niż
# runda 1 (pytania otwarte/tabelki zamiast czystego ABCDE), ale bardzo bogata
# treść merytoryczna - przekształcona na pytania typu "typed".
import json

NEW_ITEMS = [
    # --- Farmakokinetyka — podstawy (uzupełnienie) ---
    {"category": "Farmakokinetyka — podstawy", "q": "Efedryna (słaba zasada) — gdzie najszybciej się wchłania i dlaczego?",
     "mode": "typed", "answers": ["w jelicie cienkim — panuje tam zasadowe pH, więc lek występuje w formie niezjonizowanej, dobrze przenikającej błony"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Efedryna — w jakim pH moczu najszybciej się wydala i dlaczego?",
     "mode": "typed", "answers": ["w kwaśnym pH moczu — jako słaba zasada ulega protonacji (formie zjonizowanej), która nie reabsorbuje się zwrotnie w kanalikach nerkowych"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Czym jest tachyfilaksja i jakiego leku klasycznie dotyczy?",
     "mode": "typed", "answers": ["szybko narastająca tolerancja/spadek skuteczności leku przy powtarzanych dawkach w krótkim czasie — klasycznie dotyczy efedryny/pseudoefedryny (wyczerpanie zapasów noradrenaliny)"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Czym jest zjawisko up-regulation receptorów i podaj przykład leku, który je wywołuje.",
     "mode": "typed", "answers": ["uwrażliwienie (zwiększenie liczby) receptorów w odpowiedzi na przewlekłe stosowanie antagonisty, np. propranololu"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Cyklosporyna jest metabolizowana przez CYP3A4. Co się stanie, jeśli połączymy ją z inhibitorem tego enzymu (np. erytromycyną lub werapamilem)?",
     "mode": "typed", "answers": ["zwiększenie stężenia cyklosporyny w osoczu (ryzyko toksyczności)"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Lek wiąże się w 80% z białkami osocza. Co dzieje się z pozostałymi 20%?",
     "mode": "typed", "answers": ["pozostają w postaci wolnej (niezwiązanej) — to one są farmakologicznie aktywne i mogą przenikać do tkanek"]},
    {"category": "Farmakokinetyka — podstawy", "q": "Jakie etapy LADME (bez skrótów) dotyczą leku podanego domięśniowo w porównaniu do dożylnego?",
     "mode": "typed", "answers": ["podanie domięśniowe obejmuje wszystkie etapy (uwalnianie, wchłanianie, dystrybucję, metabolizm, wydalanie); dożylne pomija uwalnianie i wchłanianie"]},

    # --- Autonomiczny układ nerwowy — leki (nowa kategoria, dużo treści z Kolokwium I) ---
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Jaki jest mechanizm działania noradrenaliny powodujący skurcz naczyń (pełny szlak sygnałowy)?",
     "mode": "typed", "answers": ["noradrenalina → receptor α1 → białko Gq → fosfolipaza C → wzrost IP3/DAG → wzrost Ca2+ wewnątrzkomórkowego → skurcz mięśni gładkich naczyń"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Jaki jest mechanizm działania dobutaminy?",
     "mode": "typed", "answers": ["agonista receptora β1-adrenergicznego → białko Gs → cyklaza adenylanowa → wzrost cAMP"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Wymień 4 przeciwwskazania do stosowania atropiny.",
     "mode": "typed", "answers": ["jaskra, przerost gruczołu krokowego (BPH), zaparcia atoniczne, tachyarytmie"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Ksylometazolina (aerozol donosowy) — dlaczego nie należy jej stosować dłużej niż 5 dni?",
     "mode": "typed", "answers": ["ryzyko polekowego nieżytu nosa (rhinitis medicamentosa) wskutek down-regulacji receptorów α po przewlekłym stosowaniu"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Które leki są selektywnymi agonistami receptora β2 (bez istotnego działania na β1)?",
     "mode": "typed", "answers": ["salbutamol, salmeterol (formoterol i fenoterol są pełnymi agonistami o wysokiej, ale nie absolutnej, selektywności β2)"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Który beta-bloker kardioselektywny ma dodatkowe działanie naczyniorozszerzające i jaki jest jego mechanizm?",
     "mode": "typed", "answers": ["nebiwolol — zwiększa syntezę tlenku azotu (NO), który rozszerza naczynia"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Który beta-bloker NIEkardioselektywny ma dodatkowe działanie naczyniorozszerzające (poprzez blokadę α1)?",
     "mode": "typed", "answers": ["karwedilol (działa na receptory β1, β2 i α1)"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Wymień 4 działania niepożądane metoprololu wynikające z jego (niepełnej) selektywności β1.",
     "mode": "typed", "answers": ["bradykardia, bloki przedsionkowo-komorowe, zmniejszona kurczliwość serca, hipotonia"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Jaki jest mechanizm działania midodryny i do czego się ją stosuje?",
     "mode": "typed", "answers": ["selektywny agonista receptora α1 — stosowana w niedociśnieniu ortostatycznym, nie zwiększa wolemii"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Etylefryna — jaki mechanizm tachykardii ją odróżnia od doksazosyny?",
     "mode": "typed", "answers": ["etylefryna wywołuje tachykardię BEZPOŚREDNIO (działanie agonistyczne na receptory β1 serca), a doksazosyna powoduje tachykardię ODRUCHOWĄ (wtórną do rozszerzenia naczyń przez blokadę α1)"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "W rozszerzeniu źrenicy: gdzie działa agonista receptora α1 (np. fenylefryna), a gdzie antagonista receptora M3 (np. atropina/tropikamid)?",
     "mode": "typed", "answers": ["fenylefryna działa na mięsień rozwieracz źrenicy, atropina/tropikamid na mięsień zwieracz źrenicy (m. rzęskowy)"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Wymień 4 cholinolityki i ich odmienne zastosowania kliniczne.",
     "mode": "typed", "answers": ["atropina (zatrucie muskaryną), butylobromek skopolaminy (kolki), tropikamid (rozszerzenie źrenicy do badania oka), biperiden/triheksyfenidyl (choroba Parkinsona), solifenacyna (pęcherz nadreaktywny)"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Jaki jest mechanizm działania mirabegronu i jego typowe działanie niepożądane?",
     "mode": "typed", "answers": ["agonista receptora β3 w mięśniu wypieraczu pęcherza moczowego (pęcherz nadreaktywny); może powodować zakażenia układu moczowego"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Jaki jest mechanizm działania solifenacyny?",
     "mode": "typed", "answers": ["antagonista receptorów muskarynowych w mięśniu wypieraczu pęcherza moczowego — stosowana w pęcherzu nadreaktywnym"]},
    {"category": "Autonomiczny układ nerwowy — leki", "q": "Jakie są 4 typowe działania niepożądane β2-mimetyków?",
     "mode": "typed", "answers": ["drżenia mięśniowe, tachykardia/palpitacje, hipokaliemia, bóle głowy (możliwa też hiperglikemia)"]},

    # --- Przewód pokarmowy — leki (uzupełnienie) ---
    {"category": "Przewód pokarmowy — leki", "q": "Który lek prokinetyczny działa wyłącznie obwodowo (nie przenika przez barierę krew-mózg)?",
     "mode": "typed", "answers": ["cyzapryd"]},
    {"category": "Przewód pokarmowy — leki", "q": "Który lek jest selektywnym inhibitorem PDE4 o działaniu spazmolitycznym na jelita?",
     "mode": "typed", "answers": ["drotaweryna / alweryna"]},
    {"category": "Przewód pokarmowy — leki", "q": "Który lek jest inhibitorem enkefalinazy jelitowej (stosowany w biegunce)?",
     "mode": "typed", "answers": ["racekadotryl"]},
    {"category": "Przewód pokarmowy — leki", "q": "Który środek przeczyszczający drażni jelito cienkie?",
     "mode": "typed", "answers": ["olej rycynowy"]},
    {"category": "Przewód pokarmowy — leki", "q": "Jakich leków przeciwbiegunkowych (opioidopodobnych) NIE należy stosować w biegunce zakaźnej?",
     "mode": "typed", "answers": ["loperamid i difenoksylat (opóźniają eliminację patogenu z przewodu pokarmowego)"]},
    {"category": "Przewód pokarmowy — leki", "q": "Trimebutyna — jaki jest jej mechanizm i zastosowanie?",
     "mode": "typed", "answers": ["agonista obwodowych receptorów opioidowych w przewodzie pokarmowym — moduluje motorykę jelit, stosowana w zespole jelita drażliwego (IBS)"]},
    {"category": "Przewód pokarmowy — leki", "q": "Dlaczego inhibitory pompy protonowej (IPP) podaje się 30-60 minut przed posiłkiem?",
     "mode": "typed", "answers": ["lek musi się wchłonąć i dotrzeć do komórek okładzinowych, gdzie ulega aktywacji w kwaśnym środowisku kanalików — musi już działać, gdy posiłek maksymalnie pobudzi pompy protonowe"]},
    {"category": "Przewód pokarmowy — leki", "q": "Który IPP można przyjmować niezależnie od posiłku dzięki swojej farmakokinetyce?",
     "mode": "typed", "answers": ["dekslanzoprazol"]},
    {"category": "Przewód pokarmowy — leki", "q": "Jakie leki wchodzą w skład poczwórnej terapii eradykacyjnej Helicobacter pylori?",
     "mode": "typed", "answers": ["IPP + metronidazol + bizmut + tetracyklina, lub: IPP + metronidazol + amoksycylina + klarytromycyna"]},
    {"category": "Przewód pokarmowy — leki", "q": "Metamizol — w jakim wskazaniu stosowany jest pozajelitowo jako lek przeciwbólowy o działaniu spazmolitycznym?",
     "mode": "typed", "answers": ["kolka nerkowa"]},

    # --- Ból, opioidy i znieczulenie (uzupełnienie) ---
    {"category": "Ból, opioidy i znieczulenie", "q": "Jaka jest triada objawów zatrucia morfiną i jakie antidotum stosujemy?",
     "mode": "typed", "answers": ["depresja oddechowa, śpiączka, szpilkowate (miotyczne) źrenice; antidotum: nalokson"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Nalokson i oksykodon — jaki jest mechanizm każdego z nich i po co się je łączy w jednym preparacie?",
     "mode": "typed", "answers": ["nalokson — antagonista receptorów opioidowych (mi, kappa, delta); oksykodon — agonista receptorów mi/kappa; połączenie łagodzi zaparcia opioidowe (nalokson działa głównie obwodowo w jelitach przy niskiej biodostępności ogólnoustrojowej)"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jak rozwija się tolerancja na różne działania niepożądane opioidów?",
     "mode": "typed", "answers": ["szybko: euforia, wymioty; umiarkowanie szybko: bradykardia, depresja oddechowa; wolno lub wcale: zaparcia, zwężenie źrenic (miosis)"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Który opioid może wywołać zespół serotoninowy przy łączeniu z innymi lekami serotoninergicznymi i dlaczego?",
     "mode": "typed", "answers": ["tramadol — jest jednocześnie agonistą receptora mi i inhibitorem wychwytu zwrotnego serotoniny/noradrenaliny (SNRI)"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jakie są 2 przykłady zastosowania opioidów poza działaniem przeciwbólowym?",
     "mode": "typed", "answers": ["leczenie duszności (np. morfina w paliatywnej duszności), leczenie kaszlu (kodeina jako lek przeciwkaszlowy)"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Buprenorfina i nalokson — jaki jest mechanizm każdego (receptor)?",
     "mode": "typed", "answers": ["buprenorfina — częściowy agonista receptora mi; nalokson — antagonista receptorów opioidowych"]},
    {"category": "Ból, opioidy i znieczulenie", "q": "Jaki jest lek przeciwkaszlowy działający WYŁĄCZNIE obwodowo?",
     "mode": "typed", "answers": ["lewodropropizyna (lub inne obwodowo działające, np. moguisteina) — w odróżnieniu od ośrodkowych jak dekstrometorfan/kodeina"]},

    # --- Reumatologia i NLPZ (uzupełnienie) ---
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Etorykoksyb — do jakiej grupy NLPZ należy i jaki charakterystyczny efekt niepożądany ma na układ krążenia?",
     "mode": "typed", "answers": ["selektywny inhibitor COX-2; działanie prozakrzepowe — hamuje syntezę prostacykliny, przez co przeważa prozakrzepowe działanie tromboksanu"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Jak diklofenak wpływa na ciśnienie tętnicze i jaki jest tego mechanizm?",
     "mode": "typed", "answers": ["podnosi ciśnienie tętnicze poprzez zatrzymanie sodu i wody (hamowanie prostaglandyn nerkowych rozszerzających naczynia nerkowe)"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Podaj przykłady NLPZ w niestandardowych postaciach: plaster, tabletki do ssania, krople do uszu, krople do oczu.",
     "mode": "typed", "answers": ["plaster — diklofenak; tabletki do ssania — flurbiprofen; krople do uszu — salicylan choliny; krople do oczu — indometacyna"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Które leki przeciwbólowe/NLPZ wywołują: wstrząs anafilaktyczny, utratę wzroku, uszkodzenie wątroby (każdy inny)?",
     "mode": "typed", "answers": ["wstrząs anafilaktyczny — metamizol; utrata wzroku — indometacyna (retinopatia); uszkodzenie wątroby — nimesulid"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Który NLPZ powoduje fototoksyczność jako charakterystyczne działanie niepożądane?",
     "mode": "typed", "answers": ["ketoprofen"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Który NLPZ może powodować zaburzenia słuchu (ototoksyczność)?",
     "mode": "typed", "answers": ["indometacyna"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Piroksykam — do jakiej grupy NLPZ należy i w jakim wskazaniu reumatologicznym jest lekiem II rzutu?",
     "mode": "typed", "answers": ["NLPZ preferencyjny wobec COX (oksykam), lek II rzutu w reumatoidalnym zapaleniu stawów (RZS)"]},
    {"category": "Reumatologia, NLPZ i leki przeciwbólowe niesteroidowe", "q": "Kwas acetylosalicylowy (ASA) — jaki jest jego dokładny mechanizm i punkt uchwytu w działaniu przeciwpłytkowym?",
     "mode": "typed", "answers": ["nieodwracalny inhibitor cyklooksygenazy COX-1 w płytkach krwi"]},

    # --- Endokrynologia i cukrzyca (uzupełnienie) ---
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Liraglutyd — jaki jest mechanizm, zależność od glukozy i dodatkowe wskazanie poza cukrzycą?",
     "mode": "typed", "answers": ["agonista receptora GLP-1; działanie zależne od poziomu glukozy; dodatkowe wskazanie: otyłość"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Empagliflozyna/dapagliflozyna — pełna nazwa punktu uchwytu i 2 działania niepożądane?",
     "mode": "typed", "answers": ["kotransporter sodowo-glukozowy typu 2 (SGLT2) w kanaliku bliższym nerki; DN: zwiększenie LDL, zakażenia układu moczowo-płciowego, wielomocz (poliuria)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Metformina vs pochodne sulfonylomocznika — jak różni się ich zależność od glukozy/insuliny i wpływ na masę ciała?",
     "mode": "typed", "answers": ["metformina uwrażliwia na insulinę i zmniejsza masę ciała; sulfonylomoczniki działają niezależnie od poziomu glukozy (stymulują wydzielanie insuliny) i zwiększają masę ciała"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Jakie jest niekorzystne działanie metaboliczne wynikające z kumulacji metforminy w organizmie?",
     "mode": "typed", "answers": ["kwasica mleczanowa (kwasica metaboliczna mleczanowa)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Glimepiryd — jaki jest jego mechanizm w odniesieniu do zależności od stężenia glukozy?",
     "mode": "typed", "answers": ["pochodna sulfonylomocznika — pobudza wydzielanie insuliny NIEZALEŻNIE od aktualnego stężenia glukozy (ryzyko hipoglikemii)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Wildagliptyna — do jakiej grupy leków przeciwcukrzycowych należy i jaki jest jej punkt uchwytu?",
     "mode": "typed", "answers": ["gliptyna — inhibitor DPP-4 (dipeptydylopeptydazy 4)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Akarboza — jaki jest jej mechanizm działania?",
     "mode": "typed", "answers": ["inhibitor alfa-glukozydazy jelitowej (spowalnia rozkład i wchłanianie węglowodanów)"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Które insuliny są szybko działającymi analogami stosowanymi doposiłkowo?",
     "mode": "typed", "answers": ["lispro, aspart, glulizynowa"]},
    {"category": "Endokrynologia i leki przeciwcukrzycowe", "q": "Tirzepatyd — na jakie dwa hormony inkretynowe działa?",
     "mode": "typed", "answers": ["GLP-1 (glukagonopodobny peptyd 1) i GIP (żołądkowy peptyd hamujący/insulinotropowy)"]},

    # --- Krew i krzepnięcie (nowa, duża kategoria z Kolokwium III) ---
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Warfaryna — jaki jest jej dokładny punkt uchwytu (pełna nazwa)?",
     "mode": "typed", "answers": ["reduktaza epoksydu witaminy K"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Jaka jest odtrutka na warfarynę/acenokumarol?",
     "mode": "typed", "answers": ["witamina K (fitomenadion)"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Charakterystyczne działanie niepożądane warfaryny (niezwiązane z krwawieniem)?",
     "mode": "typed", "answers": ["zespół purpurowych stóp (purple toe syndrome)"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Charakterystyczne działanie niepożądane heparyny niefrakcjonowanej (niezwiązane z krwawieniem)?",
     "mode": "typed", "answers": ["łysienie telogenowe (a także małopłytkowość poheparynowa - HIT)"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Klopidogrel działa tylko in vivo, nie in vitro (w probówce po pobraniu krwi) — dlaczego?",
     "mode": "typed", "answers": ["jest prolekiem — wymaga metabolizmu wątrobowego (przez CYP), którego nie zapewnimy w probówce"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Tikagrelor i kangrelor — czym różnią się od klopidogrela pod względem mechanizmu wiązania z receptorem P2Y12?",
     "mode": "typed", "answers": ["są ODWRACALNYMI antagonistami P2Y12 (klopidogrel wiąże się nieodwracalnie); tikagrelor to doustny prolek, kangrelor lek aktywny podawany dożylnie"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Abciksymab — jaki jest jego mechanizm działania?",
     "mode": "typed", "answers": ["inhibitor receptora GPIIb/IIIa na płytkach krwi"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Fondaparynuks — czym jest strukturalnie?",
     "mode": "typed", "answers": ["syntetycznym pentasacharydem (selektywny inhibitor czynnika Xa)"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Hirudyna — jaki jest jej mechanizm działania?",
     "mode": "typed", "answers": ["pozajelitowy bezpośredni inhibitor trombiny"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Jaka jest odtrutka (antidotum) na riwaroksaban/apiksaban (inhibitory czynnika Xa)?",
     "mode": "typed", "answers": ["andeksanet alfa"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Który lek przeciwzakrzepowy jest lekiem z wyboru u kobiet w ciąży?",
     "mode": "typed", "answers": ["enoksaparyna (heparyna drobnocząsteczkowa)"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Który lek hamuje fibrynolizę, a który ją wspomaga (po jednym przykładzie)?",
     "mode": "typed", "answers": ["hamujący: kwas traneksamowy / kwas ε-aminokapronowy; wspomagający: alteplaza (także streptokinaza, tenekteplaza, urokinaza)"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Milrinon — jaki jest jego mechanizm działania?",
     "mode": "typed", "answers": ["inhibitor fosfodiesterazy 3 (PDE3) — stosowany w ostrej niewydolności serca"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Fibraty (np. ciprofibrat, fenofibrat) — jaki jest ich mechanizm działania?",
     "mode": "typed", "answers": ["agoniści receptora PPAR-α (obniżają głównie triglicerydy)"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Ezetymib — jaki jest jego mechanizm działania?",
     "mode": "typed", "answers": ["hamuje wchłanianie cholesterolu w jelicie cienkim"]},
    {"category": "Krew, krzepnięcie i leki hipolipemizujące", "q": "Który IKA ma najmniejsze ryzyko interakcji lekowych (nie wymaga aktywacji wątrobowej)?",
     "mode": "typed", "answers": ["lizynopryl (lek aktywny, nie jest prolekiem, wydalany głównie przez nerki)"]},

    # --- Układ sercowo-naczyniowy (uzupełnienie) ---
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Werapamil — jaki jest jego bezpośredni punkt uchwytu?",
     "mode": "typed", "answers": ["kanały wapniowe typu L"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Werapamil — jakie są 2 działania niepożądane na serce i 1 na przewód pokarmowy?",
     "mode": "typed", "answers": ["serce: bradykardia, bloki przedsionkowo-komorowe; przewód pokarmowy: zaparcia"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Dlaczego nie zaleca się łączenia werapamilu z beta-blokerem?",
     "mode": "typed", "answers": ["nakładają się ujemne tropizmy chronotropowy i dromotropowy — ryzyko ciężkiej bradykardii i bloku AV"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Dlaczego nie zaleca się łączenia IKA z sartanem?",
     "mode": "typed", "answers": ["brak dodatkowej korzyści terapeutycznej przy jednoczesnym zwiększonym ryzyku działań niepożądanych (hiperkaliemia, niewydolność nerek)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Dlaczego IKA są przeciwwskazane w obustronnym zwężeniu tętnic nerkowych?",
     "mode": "typed", "answers": ["rozkurczają tętniczkę odprowadzającą kłębuszka, co przy krytycznym zwężeniu tętnicy nerkowej gwałtownie obniża GFR (ryzyko ostrego uszkodzenia nerek)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Amlodypina — dlaczego powoduje obrzęki kończyn dolnych i jaki lek dodatkowy ogranicza ten efekt?",
     "mode": "typed", "answers": ["rozszerza wybiórczo tętniczki (nie żyły), co zwiększa ciśnienie hydrostatyczne w kapilarach; dodanie IKA/sartanu (rozszerzającego też odpływ żylny) zmniejsza obrzęki"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Diuretyki tiazydowe i pętlowe — jakie mają 2 wspólne działania niepożądane (elektrolitowe)?",
     "mode": "typed", "answers": ["hipokaliemia i hiponatremia"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Diuretyki pętlowe — jakie mają 2 działania niepożądane SPECYFICZNE (nie dzielone z tiazydami)?",
     "mode": "typed", "answers": ["ototoksyczność i hipokalcemia (tiazydy dają hiperkalcemię)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Spironolakton i eplerenon — jakie mają wspólne działanie niepożądane, i jakie 2 są specyficzne tylko dla spironolaktonu?",
     "mode": "typed", "answers": ["wspólne: hiperkaliemia; specyficzne dla spironolaktonu: ginekomastia, zaburzenia miesiączkowania (działanie antyandrogenowe)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Torasemid — czym różni się mechanistycznie od innych diuretyków pętlowych?",
     "mode": "typed", "answers": ["dodatkowo hamuje wydzielanie aldosteronu (poza klasycznym działaniem na kotransporter Na+/K+/2Cl-)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Beta-blokery — jakie są 3 mechanizmy ich działania hipotensyjnego?",
     "mode": "typed", "answers": ["hamowanie β1 w aparacie przykłębuszkowym (spadek wydzielania reniny), hamowanie β1 w sercu (spadek pojemności minutowej), efekt chronotropowy ujemny (zmniejszenie zapotrzebowania serca na tlen)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Które leki sercowo-naczyniowe zwiększają glikemię (2 grupy) i jakie mają wspólne metaboliczne działanie niepożądane?",
     "mode": "typed", "answers": ["beta-blokery i diuretyki tiazydowe/pętlowe — mogą powodować hiperurykemię i zaburzenia gospodarki lipidowej (a tiazydy dodatkowo hiperglikemię)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Który lek na nadciśnienie w ciąży pobudza receptory imidazolowe bez powodowania retencji sodu i wody (w dawkach terapeutycznych)?",
     "mode": "typed", "answers": ["moksonidyna (uwaga: w ciąży klasycznie stosuje się metyldopę — moksonidyna to przykład leku o działaniu na receptor imidazolowy ogólnie)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Digoksyna — jaki jest jej wpływ na kurczliwość i częstość pracy serca, oraz charakterystyczne działanie niepożądane dotyczące wzroku?",
     "mode": "typed", "answers": ["działanie inotropowo dodatnie przy jednoczesnym zmniejszeniu częstości pracy serca; DN: zaburzenia widzenia barw — widzenie na żółto (ksantopsja)"]},
    {"category": "Układ sercowo-naczyniowy — leki", "q": "Dobesylan wapnia — jakie ma 2 wskazania?",
     "mode": "typed", "answers": ["nefropatia cukrzycowa i żylaki odbytu (hemoroidy) / niewydolność żylna"]},

    # --- Antybiotyki i chemioterapeutyki przeciwbakteryjne (uzupełnienie z Kolokwium IV) ---
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Ciprofloksacyna — jakie charakterystyczne działanie niepożądane dotyczy chrząstki/stawów?",
     "mode": "typed", "answers": ["chondrotoksyczność — hamowanie wzrostu chrząstki stawowej (dlatego ostrożność u dzieci)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Klarytromycyna — jakie ma charakterystyczne działanie niepożądane kardiologiczne?",
     "mode": "typed", "answers": ["wydłużenie odstępu QT"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Klindamycyna, kolistyna i aminoglikozydy — jakie mają wspólne działanie niepożądane dotyczące przewodnictwa nerwowo-mięśniowego?",
     "mode": "typed", "answers": ["mogą powodować blokadę przewodnictwa nerwowo-mięśniowego (nasilają działanie leków zwiotczających, mogą nasilać miastenię)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Które penicyliny działają na Pseudomonas aeruginosa?",
     "mode": "typed", "answers": ["tikarcylina, piperacylina, mezlocylina"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Amantadyna — na jaki typ wirusa grypy działa wyłącznie?",
     "mode": "typed", "answers": ["wyłącznie na grypę typu A"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Cefuroksym — jakiej generacji cefalosporyną jest i na jakie bakterie działa (np. MSSA)?",
     "mode": "typed", "answers": ["cefalosporyna II generacji, działa m.in. na gronkowca złocistego wrażliwego na metycylinę (MSSA)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Nifuroksazyd — jak działa i na co jest stosowany?",
     "mode": "typed", "answers": ["antybiotyk jelitowy niewchłaniający się z przewodu pokarmowego, stosowany w bakteryjnych biegunkach (np. wywołanych E. coli)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Azytromycyna — na jakiego patogena klasycznie działa w zakażeniach przenoszonych drogą płciową?",
     "mode": "typed", "answers": ["Chlamydia trachomatis"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Metronidazol dopochwowo — w jakiej chorobie jest stosowany?",
     "mode": "typed", "answers": ["rzęsistkowica (Trichomonas vaginalis)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Tetracykliny — jakie są ich charakterystyczne działania niepożądane u dzieci i dlaczego są u nich przeciwwskazane?",
     "mode": "typed", "answers": ["przebarwienia i hipoplazja zębów, hamowanie wzrostu kości — wskutek chelatacji wapnia"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Jaki jest mechanizm działania metronidazolu?",
     "mode": "typed", "answers": ["fragmentacja DNA bakterii/pierwotniaków w warunkach niskiej zawartości tlenu (redukcja grupy nitrowej do reaktywnych metabolitów)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Jaki jest mechanizm działania tetracyklin?",
     "mode": "typed", "answers": ["nieodwracalne wiązanie z podjednostką 30S rybosomu, hamowanie syntezy białek bakteryjnych"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Wankomycyna, aminoglikozydy — jakie mają charakterystyczne działanie niepożądane dotyczące narządu słuchu i nerek?",
     "mode": "typed", "answers": ["ototoksyczność (i nefrotoksyczność)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Doksycyklina — jakie ma charakterystyczne działanie niepożądane skórne?",
     "mode": "typed", "answers": ["fototoksyczność (nadwrażliwość na światło słoneczne)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Penicylina prokainowa — jakie charakterystyczne (rzadkie) działanie niepożądane neuropsychiatryczne może wywołać po wstrzyknięciu?",
     "mode": "typed", "answers": ["zespół Hoigne'a (reakcja psychomimetyczna/lękowa bezpośrednio po wstrzyknięciu domięśniowym)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Fluorochinolony, metronidazol, linezolid — jakie wspólne działanie niepożądane neurologiczne mogą wywoływać?",
     "mode": "typed", "answers": ["neuropatię obwodową"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Ceftriakson — czym się wyróżnia spośród cefalosporyn pod względem przenikania?",
     "mode": "typed", "answers": ["dobrze przenika do ośrodkowego układu nerwowego (stosowany m.in. w bakteryjnym zapaleniu opon mózgowo-rdzeniowych)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Kotrimoksazol (trimetoprim/sulfametoksazol) — na jakiego charakterystycznego patogena oportunistycznego działa?",
     "mode": "typed", "answers": ["Pneumocystis jirovecii"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Zanamiwir — w jakiej postaci (drodze podania) jest podawany jako lek na grypę?",
     "mode": "typed", "answers": ["wziewnie (inhalacja)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Jaki antybiotyk podamy na boreliozę pacjentowi z alergią na beta-laktamy typu natychmiastowego (I rzut)?",
     "mode": "typed", "answers": ["doksycyklina"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Lewofloksacyna/moksyfloksacyna — kiedy stosowane są w leczeniu skorygowanym zapalenia płuc wywołanego przez S. pneumoniae?",
     "mode": "typed", "answers": ["gdy leczenie pierwszego rzutu jest nieskuteczne lub przeciwwskazane (fluorochinolony oddechowe jako terapia alternatywna)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Jaki jest lek z wyboru na toksoplazmozę w ciąży?",
     "mode": "typed", "answers": ["spiramycyna"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Gentamycyna — czy jej działanie zależy od stężenia czy od czasu powyżej MIC, i jak to wpływa na dawkowanie?",
     "mode": "typed", "answers": ["działanie zależne od stężenia (Cmax) — dlatego podaje się ją rzadziej, w wyższych dawkach jednorazowych"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Klindamycyna i beta-laktamy — czy ich działanie zależy od stężenia czy od czasu powyżej MIC, i jak to wpływa na dawkowanie?",
     "mode": "typed", "answers": ["działanie zależne od czasu powyżej MIC — podaje się je częściej, w stałych odstępach czasu"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Cefiderokol — jaki jest jego unikalny mechanizm wnikania do komórki bakteryjnej?",
     "mode": "typed", "answers": ["wiąże jony Fe3+ i udaje siderofor (\"koń trojański\") — bakteria sama aktywnie go wciąga do wnętrza"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Które cefalosporyny działają na Pseudomonas aeruginosa?",
     "mode": "typed", "answers": ["cefepim, ceftazydym"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Który makrolid ma najdłuższy okres półtrwania i wyraźny efekt poantybiotykowy?",
     "mode": "typed", "answers": ["azytromycyna"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Cefadroksyl/cefaklor — kiedy stosowane są w anginie paciorkowcowej?",
     "mode": "typed", "answers": ["u pacjentów z alergią na penicylinę typu NIENATYCHMIASTOWEGO (cefalosporyny I/II generacji jako alternatywa)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Które inhibitory beta-laktamaz działają szeroko na ESBL, karbapenemazy i cefalosporynazy?",
     "mode": "typed", "answers": ["awibaktam, relebaktam"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Wankomycyna, metronidazol, fidaksomycyna — w jakim zakażeniu są stosowane?",
     "mode": "typed", "answers": ["zakażenie Clostridioides difficile"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Bacytracyna (stosowana na skórę) — na jakie bakterie działa?",
     "mode": "typed", "answers": ["ziarenkowce Gram-dodatnie (paciorkowce, gronkowce)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Kolistyna/tobramycyna wziewnie — na jakiego patogena stosowane są u chorych na mukowiscydozę?",
     "mode": "typed", "answers": ["Pseudomonas aeruginosa"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Które antybiotyki NIE wchłaniają się z przewodu pokarmowego (działają wyłącznie miejscowo w jelicie)?",
     "mode": "typed", "answers": ["bacytracyna, nifuroksazyd, ryfaksymina (w odróżnieniu np. od limecykliny, która się wchłania ogólnoustrojowo)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Imipenem — jaki enzym go rozkłada w nerkach i dlaczego łączy się go z cylastatyną? A które karbapenemy nie wymagają tej ochrony?",
     "mode": "typed", "answers": ["dehydropeptydaza I nerkowa rozkłada imipenem; cylastatyna ją hamuje; ertapenem i meropenem nie są rozkładane przez ten enzym"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Piwmecylinam — z jakiej grupy antybiotyków pochodzi i w jakim wskazaniu urologicznym jest stosowany?",
     "mode": "typed", "answers": ["penicylina, stosowana w niepowikłanym zapaleniu pęcherza moczowego"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Fenoksymetylopenicylina — w jakiej chorobie zakaźnej wieku dziecięcego jest lekiem naturalnym z wyboru?",
     "mode": "typed", "answers": ["szkarlatyna (płonica)"]},
    {"category": "Antybiotyki i chemioterapeutyki przeciwbakteryjne", "q": "Sulfasalazyna — jakie ma potrójne działanie i w jakich 2 chorobach jest stosowana?",
     "mode": "typed", "answers": ["działanie przeciwzapalne, przeciwbakteryjne i immunosupresyjne; stosowana w reumatoidalnym zapaleniu stawów (RZS) i wrzodziejącym zapaleniu jelita grubego (WZJG)"]},

    # --- Układ nerwowy — leki psychotropowe i neurologiczne (uzupełnienie) ---
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Rysperydon — jaki neuroleptyk II generacji najczęściej powoduje ginekomastię i zaburzenia miesiączkowania, i dlaczego?",
     "mode": "typed", "answers": ["silny antagonista receptorów D2 (i 5-HT2A) — blokada D2 w szlaku guzkowo-lejkowym znosi hamowanie wydzielania prolaktyny"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Ondansetron — jaki jest mechanizm i główne wskazanie?",
     "mode": "typed", "answers": ["antagonista receptora 5-HT3 — stosowany w wymiotach po chemioterapii i radioterapii"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Dimenhydrynat i metoklopramid — jaki jest ich mechanizm i na jakie wymioty działają?",
     "mode": "typed", "answers": ["dimenhydrynat — antagonista H1/M; metoklopramid — antagonista D2; stosowane w chorobie lokomocyjnej i wymiotach pooperacyjnych"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Trójpierścieniowe leki przeciwdepresyjne (TLPD) — na jakie receptory działają, powodując odruchową tachykardię i hipotonię ortostatyczną?",
     "mode": "typed", "answers": ["blokada receptorów muskarynowych M1 (tachykardia) i α1-adrenergicznych (hipotonia ortostatyczna)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "TLPD — na jakie kanały jonowe działają w sercu i jakie z tego wynikają działania niepożądane?",
     "mode": "typed", "answers": ["kanały sodowe (zaburzenia przewodzenia, bradyarytmie) i kanały potasowe (wydłużenie odstępu QT)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Lorazepam, oksazepam, temazepam — dlaczego są najbezpieczniejszymi benzodiazepinami dla osób starszych?",
     "mode": "typed", "answers": ["są metabolizowane bezpośrednio przez sprzęganie z kwasem glukuronowym (bez udziału CYP450 wątrobowego), więc nie obciążają wątroby i nie kumulują się przy jej niewydolności"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Arypiprazol — jaki jest jego mechanizm poprawy objawów negatywnych schizofrenii?",
     "mode": "typed", "answers": ["częściowy agonista receptora D2 — w szlaku mezokortykalnym (gdzie występuje niedobór dopaminy w objawach negatywnych) pobudza receptory, zwiększając aktywność dopaminergiczną w korze przedczołowej"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Aprepitant/netupitant — jaki jest ich mechanizm przeciwwymiotny?",
     "mode": "typed", "answers": ["antagoniści receptora NK1 (neurokininowego)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Tietylperazyna i skopolamina — jaki jest ich mechanizm przeciwwymiotny?",
     "mode": "typed", "answers": ["antagoniści receptorów muskarynowych"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Fluoksetyna — w jakim zaburzeniu odżywiania jest stosowana i jakie ma 2 działania niepożądane z różnych układów?",
     "mode": "typed", "answers": ["bulimia; DN: hiponatremia oraz zaburzenia funkcji seksualnych"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Objawy pozapiramidowe po neuroleptykach — jaki jest mechanizm (receptor i miejsce) i który lek ma największe ryzyko?",
     "mode": "typed", "answers": ["blokada receptorów D2 w prążkowiu; największe ryzyko ma haloperidol (neuroleptyk I generacji) — ostre dystonie, akatyzja, parkinsonizm polekowy, późne dyskinezy"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Buspiron — jaki jest jego mechanizm i zastosowanie?",
     "mode": "typed", "answers": ["częściowy agonista receptora 5-HT1A i antagonista D2 — lek przeciwlękowy o opóźnionym początku działania"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Buspiron vs alprazolam — czy działają od razu przeciwlękowo i czy można je stosować doraźnie/długotrwale?",
     "mode": "typed", "answers": ["alprazolam działa od razu, można doraźnie, ale NIE długotrwale (ryzyko uzależnienia); buspiron NIE działa od razu i NIE stosuje się go doraźnie, ale MOŻNA długotrwale (brak uzależnienia)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Opipramol — jaki jest jego mechanizm i zastosowanie?",
     "mode": "typed", "answers": ["agonista receptorów sigma-1 i sigma-2 — stosowany w depresji i zaburzeniach lękowych"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Tianeptyna — jaki jest jej nietypowy mechanizm działania na wychwyt serotoniny?",
     "mode": "typed", "answers": ["paradoksalnie ZWIĘKSZA wychwyt zwrotny serotoniny (w odróżnieniu od SSRI); ma działanie neuroprotekcyjne, stosowana w depresji"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Prometazyna — jaki jest jej mechanizm i typowe zastosowanie poza alergią?",
     "mode": "typed", "answers": ["antagonista receptora H1 — stosowana w chorobie lokomocyjnej (a także jako lek uspokajający/nasenny)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Które leki przeciwdepresyjne (z różnych grup) są jednocześnie silnymi antagonistami receptora H1?",
     "mode": "typed", "answers": ["amitryptylina (TLPD) i mirtazapina (NaSSA)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Biperiden — w jakim wskazaniu neurologicznym jest stosowany?",
     "mode": "typed", "answers": ["parkinsonizm polekowy (np. po haloperidolu) — cholinolityk ośrodkowy"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Doksylamina i difenhydramina — jakie jest ich zastosowanie i przewaga nad lekami przeciwdepresyjnymi nasennymi?",
     "mode": "typed", "answers": ["leki przeciwhistaminowe I generacji stosowane na bezsenność — nie są antydepresantami i nie powodują uzależnienia (w odróżnieniu np. od benzodiazepin)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Bupropion — dlaczego jest lekiem przeciwdepresyjnym w najmniejszym stopniu zaburzającym funkcje seksualne?",
     "mode": "typed", "answers": ["działa jako inhibitor wychwytu zwrotnego noradrenaliny i dopaminy (NDRI), nie wpływając na przekaźnictwo serotoninowe odpowiedzialne za dysfunkcje seksualne w SSRI"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Który lek przeciwdepresyjny (SSRI) ma największy negatywny wpływ na popęd/funkcje seksualne?",
     "mode": "typed", "answers": ["paroksetyna (choć efekt dotyczy całej grupy SSRI)"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Cyproheptadyna — jaki jest jej mechanizm i zastosowanie w stanach nagłych?",
     "mode": "typed", "answers": ["antagonista receptora 5-HT2A (lek przeciwhistaminowy) — stosowana w leczeniu zespołu serotoninowego"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Donepezil i rywastygmina — jaki jest ich mechanizm w chorobie Alzheimera?",
     "mode": "typed", "answers": ["inhibitory acetylocholinoesterazy — zwiększają stężenie acetylocholiny w OUN"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Reboksetyna — jaki jest jej mechanizm działania?",
     "mode": "typed", "answers": ["selektywny inhibitor wychwytu zwrotnego noradrenaliny (NRI); DN: tachykardia, zatrzymanie moczu"]},
    {"category": "Układ nerwowy — leki psychotropowe i neurologiczne", "q": "Jaki jest lek I wyboru na napad padaczkowy podawany dojelitowo (doodbytniczo) oraz alternatywa dojelitowa/donosowa?",
     "mode": "typed", "answers": ["diazepam (wlewka doodbytnicza) — alternatywnie midazolam (podanie donosowe/dopoliczkowe)"]},
]

with open('farmakologia_raw.json', encoding='utf-8') as f:
    existing = json.load(f)

before = len(existing)
existing.extend(NEW_ITEMS)
with open('farmakologia_raw.json', 'w', encoding='utf-8') as f:
    json.dump(existing, f, ensure_ascii=False, indent=2)

print(f"farmakologia_raw.json: {before} -> {len(existing)} (+{len(NEW_ITEMS)})")

by_cat = {}
for it in NEW_ITEMS:
    by_cat[it['category']] = by_cat.get(it['category'], 0) + 1
for c, n in sorted(by_cat.items()):
    print(n, '-', c)
