import fs from 'fs';

// UWAGA: plik źródłowy nazwany był "wyklad 24 - ktos ewidentnie pomylil pojecia
// XDDD.pdf" (Wykład 24 to cukrzyca) - ale realna treść dotyczy równowagi
// kwasowo-zasadowej (RKZ), czyli tematu Wykładu 25. Kategoryzuję więc pod
// właściwy, już istniejący temat "Wykład 25 — Równowaga kwasowo-zasadowa (RKZ)".
const GIELDA_CATEGORY = 'Giełda z sesji 2024/2025 (Moodle, wykłady)';

const items = [
  { targetCategory: 'Wykład 25 — Równowaga kwasowo-zasadowa (RKZ)', q: 'Które ZŁOŻONE zaburzenie równowagi kwasowo-zasadowej jest FIZJOLOGICZNIE NIEMOŻLIWE?', o: ['Współwystępowanie zasadowicy oddechowej i kwasicy oddechowej', 'Współwystępowanie zasadowicy metabolicznej i kwasicy oddechowej', 'Współwystępowanie kwasicy metabolicznej i zasadowicy oddechowej', 'Współwystępowanie kwasicy metabolicznej i kwasicy oddechowej', 'Współwystępowanie zasadowicy metabolicznej i zasadowicy oddechowej'], a: 0, rationale: 'Współwystępowanie zasadowicy oddechowej (hiperwentylacja, spadek PaCO2) i kwasicy oddechowej (hipowentylacja, wzrost PaCO2) jest fizjologicznie NIEMOŻLIWE — organizm nie może jednocześnie hiper- i hipowentylować, bo PaCO2 może w danym momencie mieć tylko jeden kierunek zmiany (albo rośnie, albo maleje). Pozostałe kombinacje (opcje B, C, D, E) łączą zaburzenie ODDECHOWE (dotyczące PaCO2) z zaburzeniem METABOLICZNYM (dotyczącym HCO3-) lub dwa zaburzenia METABOLICZNE naraz — te kombinacje SĄ możliwe klinicznie, bo dotyczą niezależnych mechanizmów (płucnego i nerkowo-metabolicznego) lub przeciwstawnych procesów metabolicznych mogących współistnieć (np. wymioty + biegunka).' },
  { targetCategory: 'Wykład 25 — Równowaga kwasowo-zasadowa (RKZ)', q: 'Czym jest LUKA ANIONOWA (anion gap)?', o: ['Wartością obliczaną, pomocną w różnicowaniu przyczyn kwasicy metabolicznej — w rzeczywistości nie jest realną różnicą ładunków w płynie zewnątrzkomórkowym', 'Rzeczywistą różnicą stężenia kationów i anionów w płynie zewnątrzkomórkowym', 'Parametrem niezbędnym do oceny wentylacji pęcherzykowej', 'Wskaźnikiem używanym wyłącznie do oceny funkcji nerek, niezwiązanym z kwasicą', 'Wartością, która zawsze pozostaje w normie, niezależnie od rodzaju kwasicy metabolicznej'], a: 0, rationale: 'Luka anionowa to wartość OBLICZANA (z różnicy zmierzonych kationów i anionów w surowicy), pomocna klinicznie w różnicowaniu przyczyn kwasicy metabolicznej (np. typowo zwiększa się w kwasicy ketonowej) — ale w RZECZYWISTOŚCI nie odzwierciedla prawdziwej różnicy ładunków elektrycznych w płynie zewnątrzkomórkowym (bo w organizmie liczba dodatnich i ujemnych ładunków zawsze się bilansuje — "luka" to artefakt wynikający z tego, że rutynowo mierzymy tylko NIEKTÓRE jony). Opcja B jest wprost sprzeczna z tą naturą luki anionowej jako wielkości obliczeniowej, nie realnej różnicy ładunków. Opcja C błędnie łączy lukę anionową z oceną WENTYLACJI, podczas gdy to parametr METABOLICZNY, niezwiązany bezpośrednio z wentylacją pęcherzykową. Opcja D niepotrzebnie zawęża zastosowanie luki anionowej wyłącznie do nerek, pomijając jej główne zastosowanie w różnicowaniu kwasic metabolicznych. Opcja E jest nieprawdziwa — luka anionowa WŁAŚNIE zmienia się (typowo rośnie) w niektórych rodzajach kwasicy metabolicznej, np. ketonowej.' },
  { targetCategory: 'Wykład 25 — Równowaga kwasowo-zasadowa (RKZ)', q: 'Na czym polega KOMPENSACJA oddechowa w kwasicy metabolicznej wywołanej zatruciem metanolem?', o: ['Zwiększenie częstości oddechów i obniżenie PaCO2', 'Zwiększenie PaCO2 przy niezmienionej częstości oddechów', 'Oliguria (zmniejszone wydalanie moczu)', 'Obniżenie PaO2 przy prawidłowym PaCO2', 'Zwolnienie częstości oddechów w celu zatrzymania CO2'], a: 0, rationale: 'Kompensacja oddechowa w kwasicy metabolicznej polega na ZWIĘKSZENIU częstości i głębokości oddechów (hiperwentylacja), co prowadzi do OBNIŻENIA PaCO2 — organizm "wypłukuje" dwutlenek węgla, zmniejszając jego wkład kwasowy i częściowo kompensując metaboliczne obniżenie pH. Zwiększenie PaCO2 (opcja B) to kierunek PRZECIWNY do rzeczywistej kompensacji — zatrzymywanie CO2 pogłębiałoby kwasicę, nie kompensowało jej. Oliguria (opcja C) to zmniejszone wydalanie moczu — mechanizm nerkowy, niezwiązany z kompensacją ODDECHOWĄ, o którą pyta polecenie. Obniżenie PaO2 (opcja D) nie jest mechanizmem kompensacji kwasicy — kompensacja oddechowa dotyczy PaCO2, nie natlenienia. Zwolnienie oddechów (opcja E) jest wprost przeciwne do prawidłowej, obserwowanej kompensacji — zwolnienie oddechów zatrzymywałoby CO2, pogłębiając kwasicę zamiast ją kompensować.' },
  { targetCategory: 'Wykład 25 — Równowaga kwasowo-zasadowa (RKZ)', q: 'Które zmienne gazometryczne są POTRZEBNE do podstawowej oceny równowagi kwasowo-zasadowej (RKZ)?', o: ['pH, PaCO2, HCO3-', 'Wyłącznie PaO2 i stężenie jonów Cl-', 'Wyłącznie stężenie jonów Cl-', 'Wyłącznie PaO2', 'Hematokryt i stężenie hemoglobiny'], a: 0, rationale: 'Do podstawowej oceny równowagi kwasowo-zasadowej potrzebne są: pH (określa kierunek zaburzenia — kwasica czy zasadowica), PaCO2 (składowa oddechowa) oraz HCO3- (składowa metaboliczna/nerkowa) — te trzy parametry razem pozwalają rozpoznać rodzaj zaburzenia (oddechowe czy metaboliczne) i ocenić stopień kompensacji. PaO2 (opcje B, D) informuje o UTLENOWANIU krwi, nie bezpośrednio o równowadze kwasowo-zasadowej — jest ważnym parametrem gazometrii, ale nie jest kluczowy do samej oceny RKZ. Stężenie jonów Cl- (opcje B, C) bywa pomocne przy dalszym RÓŻNICOWANIU przyczyn (np. w ocenie luki anionowej), ale nie jest podstawowym, niezbędnym parametrem samej oceny RKZ. Hematokryt i hemoglobina (opcja E) to parametry morfologii krwi, niezwiązane bezpośrednio z równowagą kwasowo-zasadową.' },
  { targetCategory: 'Wykład 25 — Równowaga kwasowo-zasadowa (RKZ)', q: 'Wynik gazometrii: pH = 7,3 oraz PaCO2 = 55 mmHg (podwyższone). Jakie zaburzenie sugerują te wartości?', o: ['Kwasicę oddechową', 'Zasadowicę oddechową', 'Kwasicę metaboliczną', 'Zasadowicę metaboliczną', 'Podwyższoną lukę anionową (samodzielnie, bez określenia rodzaju zaburzenia)'], a: 0, rationale: 'Obniżone pH (7,3, poniżej normy ~7,35-7,45) wskazuje na KWASICĘ, a jednocześnie PODWYŻSZONE PaCO2 (55 mmHg, powyżej normy ~35-45 mmHg) wskazuje, że przyczyna jest ODDECHOWA (retencja CO2 = hipowentylacja) — razem dają rozpoznanie kwasicy ODDECHOWEJ. Zasadowica oddechowa (opcja B) dawałaby PODWYŻSZONE pH i OBNIŻONE PaCO2 — dokładne przeciwieństwo tego wyniku. Kwasica metaboliczna (opcja C) typowo wiązałaby się z OBNIŻONYM (nie podwyższonym) PaCO2, bo w kwasicy metabolicznej dochodzi do kompensacyjnej hiperwentylacji obniżającej PaCO2 — tu PaCO2 jest podwyższone, co wskazuje na przyczynę oddechową, nie metaboliczną. Zasadowica metaboliczna (opcja D) dawałaby podwyższone, nie obniżone pH. Sama "podwyższona luka anionowa" (opcja E) nie jest odpowiedzią na pytanie o RODZAJ zaburzenia kwasowo-zasadowego sugerowanego przez pH i PaCO2 — to inny, dodatkowy parametr używany do dalszego różnicowania kwasic metabolicznych.' },
];

const raw = JSON.parse(fs.readFileSync('fizjopato_raw.json', 'utf8'));
let added = 0;
for (const item of items) {
  raw.push({ category: item.targetCategory, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  raw.push({ category: GIELDA_CATEGORY, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  added += 2;
}
fs.writeFileSync('fizjopato_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'unikalnych pytan (x2 =', added, 'wpisow). nowa dlugosc fizjopato_raw.json:', raw.length);
