import fs from 'fs';

const GIELDA_CATEGORY = 'Giełda z sesji 2024/2025 (Moodle, wykłady)';

const items = [
  { targetCategory: 'Wykład 22 — Nadkrzepliwość i zatorowość', q: 'Jak nazywa się wykrzepianie krwi PRZYŻYCIOWO, wewnątrz naczynia krwionośnego?', o: ['Zakrzep (skrzeplina)', 'Skrzep', 'Blaszka miażdżycowa', 'Tętniak', 'Naciek zapalny'], a: 0, rationale: 'Wykrzepianie krwi przyżyciowo (czyli u żyjącego organizmu) wewnątrz naczynia krwionośnego nazywa się zakrzepem, a sam twór — skrzepliną. To kluczowe rozróżnienie terminologiczne od "skrzepu" (opcja B), który powstaje POZA żywym naczyniem (np. w probówce, po śmierci, lub jako naturalny skrzep w ranie na skórze) — mylenie tych dwóch pojęć to częsty błąd egzaminacyjny. Blaszka miażdżycowa (opcja C) to przewlekła zmiana w ścianie naczynia, MOGĄCA prowadzić do powstania zakrzepu, ale nie będąca samym zakrzepem. Tętniak (opcja D) to patologiczne poszerzenie ściany naczynia, zupełnie inny proces. Naciek zapalny (opcja E) to nagromadzenie komórek zapalnych w tkance, niezwiązane bezpośrednio z definicją wykrzepiania krwi w naczyniu.' },
  { targetCategory: 'Wykład 22 — Nadkrzepliwość i zatorowość', q: 'Które z poniższych ZWIĘKSZAJĄ ryzyko zakrzepicy?', o: ['Blaszka miażdżycowa, uraz naczynia, mutacja Leiden', 'Niedobór czynnika VIII i trombocytopenia', 'Wyłącznie zaawansowany wiek, bez innych czynników', 'Hemofilia A i choroba von Willebranda', 'Leczenie przeciwpłytkowe i przeciwkrzepliwe'], a: 0, rationale: 'Blaszka miażdżycowa (uszkadza śródbłonek), uraz naczynia (aktywuje kaskadę krzepnięcia) i mutacja czynnika V Leiden (oporność na białko C, stan nadkrzepliwości wrodzonej) to udokumentowane czynniki ZWIĘKSZAJĄCE ryzyko zakrzepicy — łącznie odzwierciedlają klasyczną triadę Virchowa (uszkodzenie śródbłonka, zaburzenia przepływu, nadkrzepliwość). Niedobór czynnika VIII (opcja B) to przyczyna HEMOFILII A — stanu SKAZY KRWOTOCZNEJ (zwiększone ryzyko KRWAWIEŃ, nie zakrzepicy), a trombocytopenia (niedobór płytek) także zwiększa ryzyko krwawień, nie zakrzepów — opcja B jest więc dokładnym przeciwieństwem prawdy. Sam wiek (opcja C) jest tylko jednym z wielu czynników, nie jedynym. Hemofilia A i choroba von Willebranda (opcja D) to klasyczne skazy krwotoczne, zwiększające ryzyko krwawień, nie zakrzepicy. Leczenie przeciwpłytkowe/przeciwkrzepliwe (opcja E) z definicji ZMNIEJSZA, a nie zwiększa ryzyko zakrzepicy.' },
  { targetCategory: 'Wykład 22 — Nadkrzepliwość i zatorowość', q: 'U którego z pacjentów profilaktyczne leczenie przeciwkrzepliwe jest WSKAZANE?', o: ['U pacjenta hospitalizowanego, nieprzytomnego, unieruchomionego', 'U każdego palacza papierosów, niezależnie od innych czynników', 'Wyłącznie u pacjentów z prawidłowym wynikiem koagulogramu', 'Wyłącznie u pacjentów ambulatoryjnych, chodzących', 'Nigdy u pacjentów z migotaniem przedsionków'], a: 0, rationale: 'Profilaktyka przeciwkrzepliwa jest wskazana m.in. u pacjentów hospitalizowanych i nieprzytomnych (unieruchomienie = zastój żylny = ryzyko zakrzepicy żył głębokich), a także po zabiegach ortopedycznych (np. wymiana stawu biodrowego), z utrwalonym migotaniem przedsionków oraz przewlekle leżących po udarze mózgu — wszystkie te stany łączy UNIERUCHOMIENIE lub zwiększone ryzyko zatorowo-zakrzepowe. Samo palenie papierosów (opcja B) BEZ dodatkowych czynników ryzyka (np. unieruchomienia, zabiegu) nie jest samodzielnym wskazaniem do rutynowej profilaktyki przeciwkrzepliwej u KAŻDEGO palacza. Opcja C jest bezsensowna — prawidłowy koagulogram nie jest kryterium kwalifikacji do profilaktyki (wręcz przeciwnie, profilaktykę stosuje się mimo prawidłowych wyników, żeby zapobiec przyszłej zakrzepicy). Opcja D jest sprzeczna z materiałem — to WŁAŚNIE unieruchomieni (nie chodzący ambulatoryjnie) pacjenci są główną grupą wskazań. Opcja E jest wprost sprzeczna z materiałem, gdzie migotanie przedsionków jest jednym z wymienionych wskazań do profilaktyki.' },
  { targetCategory: 'Wykład 22 — Nadkrzepliwość i zatorowość', q: 'Jaka jest NAJCZĘSTSZA przyczyna zatorowości płucnej?', o: ['Skrzeplina żył głębokich kończyn dolnych', 'Zakrzepica tętnicy płucnej powstająca miejscowo', 'Zakrzepica tętnic wieńcowych', 'Skrzeplina żył powierzchownych kończyn dolnych', 'Zakrzepica żyły płucnej'], a: 0, rationale: 'Najczęstszą przyczyną zatorowości płucnej jest skrzeplina powstająca w żyłach głębokich kończyn dolnych (zakrzepica żył głębokich, ZŻG), która następnie ulega oderwaniu (embolizacji) i drogą krwi trafia do tętnic płucnych — stąd nazwa "zatorowość" (materiał pochodzi z INNEGO miejsca niż tam, gdzie powoduje zator), w odróżnieniu od "zakrzepicy" (opcja B), która oznaczałaby powstanie skrzepliny MIEJSCOWO, bezpośrednio w tętnicy płucnej — to nie jest typowy, najczęstszy mechanizm zatorowości płucnej. Zakrzepica tętnic wieńcowych (opcja C) prowadzi do zawału serca, nie zatorowości płucnej. Skrzeplina żył powierzchownych (opcja D) rzadko jest źródłem istotnych klinicznie zatorów płucnych (w przeciwieństwie do żył głębokich). Zakrzepica żyły płucnej (opcja E) to rzadka, odmienna patologia, nie główna przyczyna zatorowości płucnej.' },
  { targetCategory: 'Wykład 22 — Nadkrzepliwość i zatorowość', q: 'W przebiegu ostrej zatorowości płucnej dochodzi do:', o: ['Zwiększenia ciśnienia w tętnicy płucnej oraz zwiększenia przestrzeni martwej', 'Zmniejszenia ciśnienia w tętnicy płucnej', 'Zwiększenia afterloadu LEWEJ komory (nie prawej)', 'Zmniejszenia afterloadu prawej komory', 'Zmniejszenia stosunku wentylacji do perfuzji (V/Q) w obszarze zatoru'], a: 0, rationale: 'Zator w tętnicy płucnej blokuje przepływ krwi przez zajęty odcinek naczynia, co powoduje wzrost ciśnienia w tętnicy płucnej (opór dla prawej komory rośnie) oraz zwiększenie przestrzeni martwej (obszar płuca dalej jest WENTYLOWANY, ale przestaje być PERFUNDOWANY, więc "marnuje się" jako wentylacja bez wymiany gazowej). Ciśnienie w tętnicy płucnej ROŚNIE, nie maleje (opcja B jest przeciwieństwem prawdy). Zwiększone obciążenie następcze (afterload) dotyczy PRAWEJ komory (musi pompować krew przez zablokowane łożysko płucne), nie lewej (opcja C myli komory). Afterload prawej komory ROŚNIE, a nie maleje (opcja D jest przeciwieństwem prawdy). W obszarze zatoru stosunek V/Q (wentylacja/perfuzja) ROŚNIE (bo perfuzja spada przy zachowanej wentylacji), a nie maleje (opcja E jest przeciwieństwem prawdy — to klasyczna pułapka egzaminacyjna, łatwo pomylić kierunek zmiany V/Q).' },
];

const raw = JSON.parse(fs.readFileSync('fizjopato_raw.json', 'utf8'));
let added = 0;
for (const item of items) {
  raw.push({ category: item.targetCategory, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  raw.push({ category: GIELDA_CATEGORY, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  added += 2;
}
fs.writeFileSync('fizjopato_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'unikalnych pytan (x2 =', added, 'wpisow). nowa dlugosc fizjopato_raw.json:', raw.length);
