import fs from 'fs';

const GIELDA_CATEGORY = 'Giełda z sesji 2024/2025 (Moodle, wykłady)';

const items = [
  { targetCategory: 'Wykład 13 — Miażdżyca i choroba niedokrwienna serca (IHD)', q: 'W której warstwie ściany naczynia tętniczego rozwija się blaszka miażdżycowa?', o: ['Błona wewnętrzna (intima)', 'Błona środkowa (media)', 'Przydanka (adventitia)', 'Błona sprężysta zewnętrzna', 'Światło naczynia, bez kontaktu ze ścianą'], a: 0, rationale: 'Blaszka miażdżycowa rozwija się w błonie wewnętrznej (intimie) naczynia — to tam dochodzi do gromadzenia lipidów, napływu makrofagów i rozwoju przewlekłego procesu zapalnego. Błona środkowa (media, opcja B) zbudowana jest głównie z komórek mięśni gładkich i może być wtórnie zajęta w zaawansowanej chorobie, ale to NIE tam rozpoczyna się i głównie rozwija blaszka. Przydanka (opcja C) to zewnętrzna warstwa łącznotkankowa, niezaangażowana w typowy rozwój blaszki miażdżycowej. Błona sprężysta zewnętrzna (opcja D) to struktura oddzielająca media od przydanki, nie miejsce rozwoju blaszki. Opcja E jest sprzeczna z samą definicją blaszki miażdżycowej jako zmiany w ŚCIANIE naczynia, nie w jego świetle.' },
  { targetCategory: 'Wykład 13 — Miażdżyca i choroba niedokrwienna serca (IHD)', q: 'Jaka jest typowa budowa dojrzałej blaszki miażdżycowej?', o: ['Lipidowe jądro (rdzeń) otoczone włóknistą czapeczką (otoczką)', 'Włókniste jądro otoczone lipidową otoczką', 'Martwicze jądro otoczone otoczką mięśniową', 'Wapienne jądro bez żadnej otoczki', 'Krwotoczne jądro otoczone otoczką zapalną'], a: 0, rationale: 'Dojrzała blaszka miażdżycowa ma typowo lipidowe jądro (rdzeń bogaty w cholesterol i szczątki komórkowe) otoczone włóknistą czapeczką (zbudowaną z kolagenu i komórek mięśni gładkich) — to odwrotna kolejność niż w opcji B, która jest częstą pomyłką egzaminacyjną (zamiana miejscami "co jest w środku, a co na zewnątrz"). Cienka, niestabilna czapeczka włóknista jest kluczowym czynnikiem ryzyka pęknięcia blaszki. Opcje C, D i E opisują nietypowe, nierzeczywiste kombinacje budowy blaszki, niezgodne ze standardowym opisem patologicznym.' },
  { targetCategory: 'Wykład 13 — Miażdżyca i choroba niedokrwienna serca (IHD)', q: 'Który wskaźnik laboratoryjny jest podstawowym MARKEREM MARTWICY mięśnia sercowego w zawale?', o: ['Troponina', 'CRP', 'Fibrynogen', 'D-dimer', 'Albumina'], a: 0, rationale: 'Troponina (sercowa) jest podstawowym, najbardziej czułym i swoistym markerem laboratoryjnym martwicy mięśnia sercowego — jej stężenie rośnie w zawale (w tym również w postaci NSTEMI, gdzie mimo braku uniesienia odcinka ST dochodzi do wzrostu troponiny, bo martwica jednak zachodzi). CRP (opcja B) to marker ogólnego stanu zapalnego, nieswoisty dla martwicy mięśnia sercowego. Fibrynogen (opcja C) to białko krzepnięcia, nie marker martwicy serca. D-dimer (opcja D) to marker aktywacji krzepnięcia/fibrynolizy, używany głównie w diagnostyce zatorowości płucnej i zakrzepicy żylnej, nie zawału serca. Albumina (opcja E) to białko transportowe/onkotyczne, niezwiązane z diagnostyką zawału.' },
  { targetCategory: 'Wykład 13 — Miażdżyca i choroba niedokrwienna serca (IHD)', q: 'Czym różni się zawał NSTEMI od STEMI w zapisie EKG?', o: ['W NSTEMI NIE dochodzi do uniesienia odcinka ST (w przeciwieństwie do STEMI)', 'W NSTEMI zawsze występuje uniesienie odcinka ST, tak jak w STEMI', 'NSTEMI nie daje żadnych zmian w EKG w ogóle', 'NSTEMI zawsze objawia się blokiem lewej odnogi pęczka Hisa', 'NSTEMI różni się od STEMI wyłącznie brakiem bólu zamostkowego'], a: 0, rationale: 'Kluczowa różnica definicyjna: w zawale NSTEMI (Non-ST-Elevation Myocardial Infarction) NIE dochodzi do uniesienia odcinka ST — mimo to dochodzi do martwicy mięśnia sercowego (stąd wzrost troponiny), a diagnoza opiera się na innych zmianach EKG (np. obniżenie ST, ujemne załamki T) lub samych markerach biochemicznych. STEMI (ST-Elevation MI) charakteryzuje się WŁAŚNIE uniesieniem odcinka ST — to podstawowe kryterium różnicujące oba typy zawału i decydujące o trybie leczenia (pilna koronarografia w STEMI). Opcja B jest sprzeczna z samą nazwą i definicją NSTEMI ("Non-ST-Elevation"). Opcja C błędnie sugeruje brak jakichkolwiek zmian EKG w NSTEMI, co jest nieprawdą (zmiany są, tylko inne niż uniesienie ST). Opcja D błędnie wiąże NSTEMI z konkretnym, niezwiązanym bezpośrednio zaburzeniem przewodzenia. Opcja E błędnie redukuje różnicę między STEMI i NSTEMI do objawu bólowego, podczas gdy kluczowa różnica jest elektrokardiograficzna.' },
  { targetCategory: 'Wykład 6 — EKG i elektryczna czynność serca', q: 'Który element zapisu EKG reprezentuje REPOLARYZACJĘ komór?', o: ['Załamek T (oraz odcinek ST)', 'Załamek P', 'Zespół QRS', 'Odcinek PR', 'Załamek Q samodzielnie'], a: 0, rationale: 'Repolaryzację komór w EKG reprezentują odcinek ST oraz załamek T — to faza powrotu kardiomiocytów komorowych do stanu spoczynkowego po depolaryzacji. Załamek P (opcja B) reprezentuje DEPOLARYZACJĘ przedsionków, nie repolaryzację komór. Zespół QRS (opcja C) reprezentuje DEPOLARYZACJĘ komór (proces odwrotny do repolaryzacji, poprzedzający ją w cyklu pracy serca). Odcinek PR (opcja D) odzwierciedla czas przewodzenia przedsionkowo-komorowego (opóźnienie w węźle AV), nie repolaryzację komór. Załamek Q samodzielnie (opcja E) jest tylko początkowym, ujemnym wychyleniem zespołu QRS — częścią depolaryzacji komór, nie repolaryzacji.' },
];

const raw = JSON.parse(fs.readFileSync('fizjopato_raw.json', 'utf8'));
let added = 0;
for (const item of items) {
  raw.push({ category: item.targetCategory, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  raw.push({ category: GIELDA_CATEGORY, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  added += 2;
}
fs.writeFileSync('fizjopato_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'unikalnych pytan (x2 =', added, 'wpisow). nowa dlugosc fizjopato_raw.json:', raw.length);
