import fs from 'fs';

const GIELDA_CATEGORY = 'Giełda z sesji 2024/2025 (Moodle, wykłady)';

const items = [
  { targetCategory: 'Wykład 16 — Jakościowe zaburzenia wentylacji (obturacja i restrykcja)', q: 'Obturację w badaniu spirometrycznym rozpoznajemy przede wszystkim na podstawie:', o: ['Obniżonego stosunku FEV1/FVC', 'Wyłącznie obniżonej FVC', 'Wyłącznie obniżonej FRC', 'Wyłącznie obniżonej TLC', 'Podwyższonego stosunku FEV1/FVC'], a: 0, rationale: 'Obturację rozpoznajemy przede wszystkim na podstawie OBNIŻONEGO STOSUNKU FEV1/FVC (wskaźnika Tiffeneau) — sama obniżona wartość FEV1 bez odniesienia do FVC nie wystarcza do jednoznacznego rozpoznania obturacji, bo FEV1 może być obniżone również w restrykcji (gdzie stosunek FEV1/FVC pozostaje prawidłowy lub nawet podwyższony, bo oba parametry maleją proporcjonalnie). Wyłącznie obniżona FVC (opcja B) jest bardziej typowa dla restrykcji, nie obturacji. FRC (opcja C) i TLC (opcja D) to objętości/pojemności statyczne płuc, niemierzone w podstawowej spirometrii (wymagają pletyzmografii) i nie służą do podstawowego rozpoznania obturacji tą metodą. Podwyższony stosunek FEV1/FVC (opcja E) jest przeciwieństwem tego, co obserwuje się w obturacji.' },
  { targetCategory: 'Wykład 16 — Jakościowe zaburzenia wentylacji (obturacja i restrykcja)', q: 'Których objętości/pojemności płuc NIE MOŻEMY zmierzyć podstawową spirometrią (wymagają np. pletyzmografii)?', o: ['RV (objętość zalegająca) i FRC (czynnościowa pojemność zalegająca)', 'VC (pojemność życiowa) i FVC (natężona pojemność życiowa)', 'IRV (zapasowa objętość wdechowa) i ERV (zapasowa objętość wydechowa)', 'FEV1 (natężona objętość wydechowa pierwszosekundowa)', 'Wszystkie objętości i pojemności płuc można zmierzyć podstawową spirometrią'], a: 0, rationale: 'RV (objętość zalegająca — powietrze pozostające w płucach po maksymalnym wydechu) oraz FRC (czynnościowa pojemność zalegająca, która ZAWIERA w sobie RV) nie mogą być zmierzone podstawową spirometrią, ponieważ pacjent fizycznie nie może "wydmuchać" objętości zalegającej — do ich pomiaru potrzebna jest pletyzmografia całego ciała lub metody rozcieńczania gazów. VC i FVC (opcja B), IRV i ERV (opcja C) oraz FEV1 (opcja D) to WŁAŚNIE parametry standardowo mierzone podstawową spirometrią, ponieważ dotyczą powietrza, które pacjent może aktywnie wdychać i wydychać. Opcja E jest wprost sprzeczna z faktem, że RV/FRC wymagają metod wykraczających poza podstawową spirometrię.' },
  { targetCategory: 'Wykład 16 — Jakościowe zaburzenia wentylacji (obturacja i restrykcja)', q: 'Prawidłowa (niezmieniona) wartość których dwóch parametrów statycznych płuc CZYNI RESTRYKCJĘ MAŁO PRAWDOPODOBNĄ?', o: ['TLC (całkowita pojemność płuc) i VC (pojemność życiowa)', 'FEV1 i wskaźnik FEV1/FVC', 'RV samodzielnie, bez odniesienia do innych parametrów', 'Tylko FRC, niezależnie od TLC', 'Żaden pojedynczy parametr nie ma znaczenia diagnostycznego w restrykcji'], a: 0, rationale: 'Prawidłowa TLC (całkowita pojemność płuc) i prawidłowa VC (pojemność życiowa) z dużym prawdopodobieństwem WYKLUCZAJĄ restrykcję — restrykcyjne zaburzenia wentylacji charakteryzują się właśnie OBNIŻENIEM tych dwóch parametrów (płuca "mieszczą" mniej powietrza niż prawidłowo), więc ich prawidłowa wartość przemawia przeciwko restrykcji. FEV1 i wskaźnik FEV1/FVC (opcja B) to parametry kluczowe raczej dla rozpoznania OBTURACJI, nie restrykcji. Sam RV (opcja C) czy sama FRC (opcja D) analizowane w oderwaniu od reszty obrazu nie dają tak jednoznacznej informacji jak zestawienie TLC+VC. Opcja E jest nieprawdziwa — właśnie zestawienie TLC i VC ma istotne znaczenie diagnostyczne w różnicowaniu restrykcji.' },
  { targetCategory: 'Wykład 16 — Jakościowe zaburzenia wentylacji (obturacja i restrykcja)', q: 'Który z poniższych mechanizmów jest klasyczną przyczyną OBTURACJI (zaburzenia obturacyjnego) dróg oddechowych?', o: ['Skurcz oskrzeli', 'Włóknienie miąższu płucnego', 'Wysiękowe zapalenie opłucnej', 'Deformacja klatki piersiowej (np. skolioza)', 'Osłabienie mięśni oddechowych'], a: 0, rationale: 'Skurcz oskrzeli (bronchospazm, np. w astmie) jest klasycznym mechanizmem OBTURACJI — zwężenie światła dróg oddechowych utrudnia przepływ powietrza, zwłaszcza w fazie wydechu, obniżając stosunek FEV1/FVC. Włóknienie miąższu płucnego (opcja B), wysiękowe zapalenie opłucnej (opcja C), deformacje klatki piersiowej (opcja D) i osłabienie mięśni oddechowych (opcja E) to klasyczne przyczyny zaburzeń RESTRYKCYJNYCH — ograniczają zdolność płuc do rozprężania się (zmniejszają TLC/VC), a nie utrudniają przepływu powietrza przez drogi oddechowe jak w obturacji.' },
];

const raw = JSON.parse(fs.readFileSync('fizjopato_raw.json', 'utf8'));
let added = 0;
for (const item of items) {
  raw.push({ category: item.targetCategory, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  raw.push({ category: GIELDA_CATEGORY, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  added += 2;
}
fs.writeFileSync('fizjopato_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'unikalnych pytan (x2 =', added, 'wpisow). nowa dlugosc fizjopato_raw.json:', raw.length);
