import fs from 'fs';

const GIELDA_CATEGORY = 'Giełda z sesji 2024/2025 (Moodle, wykłady)';

const items = [
  { targetCategory: 'Wykład 18 — Patofizjologia nerek (zespoły nerkowe)', q: 'Które z poniższych objawów/zaburzeń występują typowo w zespole nefrytycznym?', o: ['Podwyższone ciśnienie tętnicze, wałeczki czerwonokrwinkowe w moczu, hematuria', 'Masywny białkomocz > 5 g/dobę', 'Hipotensja jako typowy objaw', 'Prawidłowy osad moczu bez wałeczków', 'Wyłącznie bezobjawowa hiperlipidemia'], a: 0, rationale: 'Zespół nefrytyczny charakteryzuje się podwyższonym ciśnieniem tętniczym (zatrzymanie sodu i wody wskutek zapalnego uszkodzenia kłębuszków), wałeczkami czerwonokrwinkowymi w moczu (świadczącymi o krwawieniu na poziomie kłębuszka) oraz hematurią. Masywny białkomocz >5 g/dobę (opcja B) jest cechą definiującą ZESPÓŁ NERCZYCOWY, nie nefrytyczny — w zespole nefrytycznym białkomocz jest zwykle umiarkowany, nienerczycowy. Hipotensja (opcja C) jest przeciwieństwem typowego obrazu — w zespole nefrytycznym ciśnienie tętnicze WZRASTA, nie spada. Osad moczu w zespole nefrytycznym jest WŁAŚNIE nieprawidłowy (aktywny, z wałeczkami erytrocytarnymi), a nie prawidłowy (opcja D). Sama bezobjawowa hiperlipidemia (opcja E) jest cechą zespołu nerczycowego, nie nefrytycznego, i nie oddaje pełnego obrazu klinicznego tego ostatniego.' },
  { targetCategory: 'Wykład 18 — Patofizjologia nerek (zespoły nerkowe)', q: 'Przyczyną obrzęków uogólnionych w zespole nerczycowym jest/są:', o: ['Obniżenie ciśnienia onkotycznego i hipoalbuminemia', 'Hiperlipidemia jako główny mechanizm', 'Przekrwienie czynne narządów', 'Uogólnione uszkodzenie śródbłonka naczyń', 'Podwyższone ciśnienie onkotyczne osocza'], a: 0, rationale: 'W zespole nerczycowym masywna utrata białka (głównie albumin) z moczem prowadzi do hipoalbuminemii, co obniża ciśnienie onkotyczne osocza — płyn przestaje być skutecznie "zatrzymywany" w naczyniach i przechodzi do przestrzeni śródmiąższowej, powodując uogólnione obrzęki. Hiperlipidemia (opcja B) jest WSPÓŁWYSTĘPUJĄCĄ cechą zespołu nerczycowego (wtórną do zwiększonej syntezy wątrobowej lipoprotein w odpowiedzi na hipoalbuminemię), ale nie jest głównym mechanizmem powstawania obrzęków. Przekrwienie czynne narządów (opcja C) to zupełnie inny proces patofizjologiczny (zwiększony dopływ krwi tętniczej), niezwiązany z mechanizmem obrzęków nerczycowych. Uogólnione uszkodzenie śródbłonka (opcja D) jest mechanizmem typowym raczej dla wstrząsu septycznego lub stanów zapalnych uogólnionych, nie klasycznego mechanizmu obrzęku nerczycowego. Ciśnienie onkotyczne w zespole nerczycowym jest OBNIŻONE, a nie podwyższone (opcja E jest przeciwieństwem prawdy).' },
  { targetCategory: 'Wykład 17 — Nadciśnienie płucne', q: 'Do powikłań nadciśnienia tętniczego płucnego można zaliczyć:', o: ['Niewydolność prawej komory, obrzęki hydrostatyczne kończyn, wodobrzusze', 'Niewydolność lewej komory', 'Obrzęk płuc jako typowe powikłanie', 'Wyłącznie bezobjawowy przebieg bez powikłań narządowych', 'Poprawę wydolności fizycznej'], a: 0, rationale: 'Nadciśnienie płucne zwiększa obciążenie następcze prawej komory serca (musi ona pompować krew przez łożysko płucne o podwyższonym oporze), prowadząc z czasem do niewydolności prawej komory (tzw. serce płucne, cor pulmonale) — a ta z kolei manifestuje się obrzękami hydrostatycznymi kończyn i wodobrzuszem (typowe objawy niewydolności PRAWOKOMOROWEJ, wynikające z zastoju żylnego systemowego). Niewydolność lewej komory (opcja B) nie jest bezpośrednim powikłaniem nadciśnienia płucnego — to odrębny proces, choć niewydolność LEWEJ komory może być z kolei PRZYCZYNĄ wtórnego nadciśnienia płucnego (odwrotna zależność). Obrzęk płuc (opcja C) jest typowym powikłaniem niewydolności LEWOKOMOROWEJ (zastój w krążeniu płucnym), nie prawokomorowej — nadciśnienie płucne prowadzi raczej do zastoju SYSTEMOWEGO (obrzęki obwodowe, wodobrzusze), nie płucnego. Nadciśnienie płucne jest poważną, postępującą chorobą z istotnymi powikłaniami narządowymi, nie przebiega bezobjawowo (opcja D). Prowadzi ono do POGORSZENIA, nie poprawy wydolności fizycznej (opcja E jest przeciwieństwem prawdy).' },
  { targetCategory: 'Wykład 17 — Nadciśnienie płucne', q: 'Które z poniższych prawidłowo opisują tętnicze nadciśnienie płucne (PAH)?', o: ['W części przypadków nie jest znana przyczyna, dochodzi do przerostu i rozrostu błony mięśniowej tętniczek, w postaci rodzinnej opisano mutację genu BMPR2', 'Zawsze ma ustaloną, znaną przyczynę', 'Dochodzi do nasilenia apoptozy mięśni gładkich tętnic płucnych', 'Nie zwiększa ryzyka zgonu', 'Nigdy nie występuje w postaci rodzinnej/dziedzicznej'], a: 0, rationale: 'Tętnicze nadciśnienie płucne w części przypadków jest idiopatyczne (nieznana przyczyna), charakteryzuje się patologicznym remodelingiem naczyniowym z przerostem i rozrostem (proliferacją) błony mięśniowej tętniczek płucnych (zwężającym ich światło), a w postaci rodzinnej opisano mutacje genu BMPR2 (receptora dla białek morfogenetycznych kości, regulującego proliferację komórek mięśni gładkich naczyń). Twierdzenie, że PAH ZAWSZE ma znaną przyczynę (opcja B) jest sprzeczne z istnieniem dobrze udokumentowanej postaci idiopatycznej. W PAH dochodzi do ZMNIEJSZENIA (nie nasilenia) apoptozy mięśni gładkich tętnic — to WŁAŚNIE nadmierna proliferacja i niedostateczna apoptoza prowadzą do przerostu ściany naczyń (opcja C jest przeciwieństwem prawdy). PAH jest poważną, postępującą chorobą znacząco ZWIĘKSZAJĄCĄ ryzyko zgonu (niewydolność prawej komory, nagły zgon sercowy), więc opcja D jest nieprawdziwa. Postać rodzinna/dziedziczna PAH jest dobrze opisana (właśnie z mutacją BMPR2), więc opcja E jest przeciwieństwem prawdy.' },
  { targetCategory: 'Wykład 15 — Niewydolność oddechowa', q: 'Tlenoterapia u pacjenta, u którego przyczyną hipoksemii są obszary płuca o obniżonym stosunku wentylacji do perfuzji (V/Q), może spowodować:', o: ['Poprawę PaO2 i zmniejszenie hipoksemicznego skurczu tętniczek płucnych, ale bez pewnego obniżenia PaCO2 — może nawet spowodować hiperkapnię', 'Zawsze wyraźne obniżenie PaCO2', 'Pogorszenie PaO2', 'Nasilenie hipoksemicznego skurczu tętniczek płucnych', 'Brak jakiegokolwiek wpływu na PaO2'], a: 0, rationale: 'Podanie tlenu poprawia PaO2 (dostarczając więcej tlenu do słabo wentylowanych, ale wciąż perfundowanych obszarów płuca) i znosi hipoksemiczny skurcz tętniczek płucnych (HPV — fizjologiczny mechanizm przekierowujący krew z obszarów słabo wentylowanych do lepiej wentylowanych; jego zniesienie przez tlenoterapię może paradoksalnie pogorszyć dopasowanie V/Q w niektórych obszarach). PaCO2 nie musi się obniżyć — u pacjentów z przewlekłą retencją CO2 tlenoterapia może osłabić hipoksyjny napęd oddechowy i nasilić hipowentylację, prowadząc do HIPERKAPNII, a nie jej obniżenia. Twierdzenie o ZAWSZE wyraźnym obniżeniu PaCO2 (opcja B) jest więc nieprawidłowe — efekt jest zmienny i może być odwrotny. Tlenoterapia poprawia, a nie pogarsza PaO2 (opcja C jest przeciwieństwem prawdy). Znosi ona, a nie nasila hipoksemiczny skurcz tętniczek płucnych (opcja D jest przeciwieństwem prawdy). Twierdzenie o braku wpływu na PaO2 (opcja E) jest sprzeczne z podstawowym, dobrze udokumentowanym efektem tlenoterapii.' },
];

const raw = JSON.parse(fs.readFileSync('fizjopato_raw.json', 'utf8'));
let added = 0;
for (const item of items) {
  raw.push({ category: item.targetCategory, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  raw.push({ category: GIELDA_CATEGORY, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  added += 2;
}
fs.writeFileSync('fizjopato_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'unikalnych pytan (x2 =', added, 'wpisow). nowa dlugosc fizjopato_raw.json:', raw.length);
