import fs from 'fs';

const GIELDA_CATEGORY = 'Giełda z sesji 2024/2025 (Moodle, wykłady)';

const items = [
  { targetCategory: 'Wykład 2 — Patofizjologia bólu', q: 'Które związki BEZPOŚREDNIO pobudzają nocyceptory i wywołują ból?', o: ['Histamina, kwas mlekowy, bradykinina', 'Wyłącznie PGE2 i substancja P', 'Wyłącznie substancja P', 'Wyłącznie PGE2', 'Żadne z wymienionych — nocyceptory pobudzane są tylko mechanicznie'], a: 0, rationale: 'Histamina, kwas mlekowy i bradykinina bezpośrednio pobudzają nocyceptory, wywołując odczucie bólu. PGE2 (prostaglandyna E2) i substancja P (opcje B, C, D) działają głównie jako mediatory UWRAŻLIWIAJĄCE (sensytyzujące) nocyceptory na inne bodźce, a nie jako związki bezpośrednio je pobudzające — subtelna, ale ważna różnica patofizjologiczna, częsty błąd egzaminacyjny. Opcja E jest nieprawdziwa — nocyceptory reagują na liczne bodźce chemiczne (jak wymienione związki), nie tylko mechaniczne.' },
  { targetCategory: 'Wykład 2 — Patofizjologia bólu', q: 'Które z poniższych sytuacji są przykładem HIPERALGEZJI?', o: ['Fala perystaltyczna jelit odczuwana jako kolka w przebiegu zapalenia jelit; dotyk oparzonej skóry wywołujący ból; kontakt poparzonej skóry z letnią wodą wywołujący ból', 'Ukłucie igłą wywołujące ból u zdrowej osoby', 'Dotyk rogówki wywołujący ból u zdrowej osoby', 'Każdy ból odczuwany przez pacjenta, niezależnie od przyczyny', 'Brak odczuwania bólu mimo silnego bodźca uszkadzającego'], a: 0, rationale: 'Hiperalgezja to NADMIERNA reakcja bólowa na bodziec, który normalnie wywołuje ból łagodny lub umiarkowany, albo odczuwanie jako bolesnych bodźców normalnie niebolesnych w danym miejscu (np. letnia woda na oparzonej skórze, prawidłowa perystaltyka odczuwana jako kolka przy zapaleniu jelit) — kluczowa cecha to NIEPROPORCJONALNIE silna reakcja bólowa względem bodźca. Ukłucie igłą (opcja B) i dotyk rogówki (opcja C) u zdrowej osoby to PRAWIDŁOWA, fizjologiczna nocycepcja — te struktury są zawsze wrażliwe na tego typu bodźce, to nie jest wzmożona reakcja, tylko normalna. Opcja D zbyt szeroko definiuje hiperalgezję jako "każdy ból", tracąc kluczowy element NADMIERNOŚCI reakcji względem bodźca. Opcja E opisuje wręcz przeciwieństwo hiperalgezji — brak reakcji bólowej (hipoalgezję/analgezję), nie jej nadmiar.' },
  { targetCategory: 'Wykład 2 — Patofizjologia bólu', q: 'Jaki jest typowy patomechanizm bólu NEUROPATYCZNEGO?', o: ['Uszkodzenie nerwu obwodowego lub uszkodzenie drogi nerwowej w obrębie OUN', 'Uwolnienie bradykininy z komórek tucznych', 'Podrażnienie wolnych zakończeń nerwowych przez mediatory zapalne', 'Uwolnienie substancji P z wolnych zakończeń nerwowych', 'Aktywacja prawidłowo funkcjonujących nocyceptorów przez silny bodziec mechaniczny'], a: 0, rationale: 'Ból neuropatyczny wynika z USZKODZENIA struktury układu nerwowego — nerwu obwodowego lub drogi przewodzącej w obrębie ośrodkowego układu nerwowego — a nie z prawidłowej aktywacji nienaruszonych nocyceptorów. To zasadnicza różnica względem bólu NOCYCEPTYWNEGO (zapalnego), gdzie mechanizmy takie jak uwolnienie bradykininy z komórek tucznych (opcja B), podrażnienie wolnych zakończeń nerwowych przez mediatory zapalne (opcja C) czy uwolnienie substancji P (opcja D) odgrywają kluczową rolę — te procesy dotyczą NIEUSZKODZONEGO układu nerwowego reagującego na bodziec zapalny/uszkadzający tkankę, a nie samego uszkodzenia nerwu. Opcja E opisuje prawidłową nocycepcję fizjologiczną, przeciwieństwo patologicznego bólu neuropatycznego.' },
  { targetCategory: 'Wykład 2 — Patofizjologia bólu', q: 'Które struktury organizmu są unerwione przez włókna bólowe A-delta (dające ból dobrze zlokalizowany)?', o: ['Skóra, otrzewna ścienna, okostna', 'Miąższ wątroby i opłucna trzewna', 'Wyłącznie narządy miąższowe jamy brzusznej', 'Wyłącznie mózg i rdzeń kręgowy', 'Wyłącznie mięsień sercowy'], a: 0, rationale: 'Skóra, otrzewna ścienna (parietalna) i okostna są unerwione przez włókna A-delta, dające ostry, dobrze zlokalizowany ból — to struktury SOMATYCZNE. Miąższ wątroby i opłucna trzewna (opcja B) to struktury TRZEWNE, generalnie POZBAWIONE gęstego unerwienia A-delta — stąd ból trzewny (np. wątrobowy) jest zwykle rozlany, źle zlokalizowany, w przeciwieństwie do bólu somatycznego. Opcja C nadmiernie uogólnia do wszystkich narządów miąższowych brzucha, co jest niezgodne z zasadą słabego unerwienia trzewnego A-delta. Opcje D i E niepotrzebnie zawężają odpowiedź do pojedynczych, niewymienionych w materiale struktur, pomijając prawidłowy zestaw (skóra/otrzewna ścienna/okostna).' },
  { targetCategory: 'Wykład 3 — Termoregulacja: gorączka i zaburzenia temperatury', q: 'Które z poniższych są czynnikami ryzyka HIPOTERMII?', o: ['Upojenie alkoholowe, hipoglikemia, niedoczynność tarczycy, zatrucie barbituranami', 'Otyłość, nadczynność tarczycy, hiperglikemia', 'Wyłącznie młody wiek, bez innych czynników', 'Gorączka i infekcja bakteryjna', 'Nadmierna aktywność fizyczna w ciepłym otoczeniu'], a: 0, rationale: 'Czynnikami ryzyka hipotermii są: upojenie alkoholowe (zaburza termoregulację i odczuwanie zimna), hipoglikemia (zmniejsza produkcję ciepła metabolicznego), niedoczynność tarczycy (obniżony metabolizm podstawowy) oraz zatrucie barbituranami (depresja OUN, w tym ośrodka termoregulacji). Otyłość (opcja B) jest raczej czynnikiem OCHRONNYM przed hipotermią (izolacja termiczna tkanki tłuszczowej), a nadczynność tarczycy i hiperglikemia nie są typowymi czynnikami ryzyka hipotermii wymienionymi w materiale. Sam młody wiek (opcja C) nie jest samodzielnym czynnikiem ryzyka — to raczej BARDZO MŁODY (niemowlęta) lub podeszły wiek zwiększają ryzyko, nie młody wiek ogólnie. Gorączka i infekcja (opcja D) to stany związane z PODWYŻSZONĄ temperaturą ciała, przeciwieństwo hipotermii. Aktywność fizyczna w cieple (opcja E) zwiększa ryzyko przegrzania/udaru cieplnego, nie hipotermii.' },
  { targetCategory: 'Wykład 3 — Termoregulacja: gorączka i zaburzenia temperatury', q: 'Jaka zmiana w zapisie EKG jest CHARAKTERYSTYCZNA dla hipotermii?', o: ['Fala J (fala Osborna)', 'Fala delta', 'Skrócenie odstępu PQ', 'Izolowany załamek Q', 'Wydłużenie odstępu QT bez innych zmian'], a: 0, rationale: 'Fala J (fala Osborna) — dodatkowe wychylenie na złączu zespołu QRS z odcinkiem ST — jest klasyczną, charakterystyczną zmianą w EKG obserwowaną w hipotermii, tym bardziej widoczną im głębsza hipotermia. Fala delta (opcja B) jest charakterystyczna dla zespołu WPW (Wolff-Parkinson-White), zupełnie innej jednostki niezwiązanej z temperaturą ciała. Skrócenie odstępu PQ (opcja C) nie jest typową, klasyczną cechą hipotermii — w hipotermii częściej obserwuje się WYDŁUŻENIE odstępów, nie skrócenie. Izolowany załamek Q (opcja D) sugeruje raczej przebyty zawał serca, nie hipotermię. Wydłużenie QT (opcja E) MOŻE towarzyszyć hipotermii, ale to fala J jest jej najbardziej rozpoznawalną, swoistą cechą w EKG, wymienioną wprost w materiale jako poprawna odpowiedź.' },
  { targetCategory: 'Wykład 4 — Patofizjologia obrzęków', q: 'Które stwierdzenia o OBRZĘKACH są prawidłowe?', o: ['Płyn w jamie opłucnej jest formą obrzęku; przyczyną może być niedrożność żyły spowodowana skrzepliną; obrzęk to zwiększenie objętości płynu w przestrzeni MIĘDZYKOMÓRKOWEJ', 'Obrzęk to zawsze zwiększenie objętości płynu w przestrzeni NACZYNIOWEJ', 'Płyn w jamie otrzewnej nigdy nie jest formą obrzęku', 'Obrzęk może powstać wyłącznie z przyczyn zapalnych', 'Obrzęk dotyczy wyłącznie kończyn dolnych'], a: 0, rationale: 'Obrzęk to zwiększenie ilości/objętości płynu w przestrzeni MIĘDZYKOMÓRKOWEJ (śródmiąższowej) — dotyczy to również płynu gromadzącego się patologicznie w jamach ciała, np. w jamie opłucnej (wysięk/przesięk opłucnowy jest formą obrzęku), a jedną z przyczyn może być zastój żylny spowodowany niedrożnością żyły przez skrzeplinę (wzrost ciśnienia hydrostatycznego za przeszkodą). Opcja B błędnie umiejscawia obrzęk w przestrzeni NACZYNIOWEJ zamiast międzykomórkowej — to podstawowy błąd definicyjny. Opcja C jest nieprawdziwa — płyn w jamie otrzewnej (wodobrzusze/puchlina brzuszna) TEŻ jest klasyczną formą obrzęku, analogicznie do płynu w opłucnej. Opcja D niepotrzebnie zawęża przyczyny obrzęku wyłącznie do zapalnych, pomijając np. przyczyny hydrostatyczne (zastój żylny) czy onkotyczne (hipoalbuminemia). Opcja E błędnie ogranicza obrzęk wyłącznie do kończyn dolnych, podczas gdy może dotyczyć dowolnej lokalizacji w organizmie, w tym jam ciała.' },
  { targetCategory: 'Wykład 4 — Patofizjologia obrzęków', q: 'Różnica jakiego ciśnienia jest bezpośrednią przyczyną powstawania PRZESĄCZU (transudatu)?', o: ['Hydrostatycznego', 'Parcjalnego', 'Atmosferycznego', 'Onkotycznego', 'Osmotycznego'], a: 0, rationale: 'Wzrost różnicy ciśnienia HYDROSTATYCZNEGO (np. przy zastoju żylnym, niewydolności serca) jest klasycznym mechanizmem powstawania przesięku (transudatu) — nadmierne ciśnienie w naczyniach "wypycha" płyn do przestrzeni śródmiąższowej ponad zdolność jego wchłaniania zwrotnego. Ciśnienie parcjalne (opcja B) dotyczy gazów (np. w gazometrii), niezwiązane z mechanizmem powstawania przesięku. Ciśnienie atmosferyczne (opcja C) nie jest czynnikiem różnicującym powstawanie przesięku w tkankach organizmu. Ciśnienie onkotyczne (opcja D) rzeczywiście również uczestniczy w bilansie Starlinga (jego OBNIŻENIE, np. przy hipoalbuminemii, też sprzyja obrzękom), ale w tym konkretnym pytaniu z materiału wskazano jednoznacznie ciśnienie HYDROSTATYCZNE jako poprawną odpowiedź. Ciśnienie osmotyczne (opcja E) jest pojęciem bliskim onkotycznemu, ale to nie ono zostało wskazane jako bezpośrednia przyczyna w tym pytaniu.' },
];

const raw = JSON.parse(fs.readFileSync('fizjopato_raw.json', 'utf8'));
let added = 0;
for (const item of items) {
  raw.push({ category: item.targetCategory, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  raw.push({ category: GIELDA_CATEGORY, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  added += 2;
}
fs.writeFileSync('fizjopato_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'unikalnych pytan (x2 =', added, 'wpisow). nowa dlugosc fizjopato_raw.json:', raw.length);
