# -*- coding: utf-8 -*-
# Genetyka kliniczna (Rok 3) - nowy przedmiot od zera.
# Źródła: "Genetyka kliniczna - zaliczenie końcowe 2025-2026.pdf" (recall z wielu
# terminów w roku) + GIEŁDY TEGOROCZNE/Genetyka (EGZAMIN 18.06.2026, 2 tury).
import json

ITEMS = [
    # --- Podstawy dziedziczenia i wzory dziedziczenia ---
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Czym jest niepełna penetracja genu?",
     "mode": "typed", "answers": ["brakiem objawów klinicznych choroby mimo posiadania wariantu patogennego (mutacji), który tę chorobę wywołuje"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Jak w rodowodzie uwidacznia się zjawisko niepełnej penetracji (dziedziczenie autosomalne dominujące)?",
     "mode": "typed", "answers": ["przeskokiem (skokiem) pokoleniowym"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Czym jest zmienna ekspresja (ekspresywność) genu?",
     "mode": "typed", "answers": ["różnym nasileniem fenotypu (objawów) tej samej mutacji u różnych osób"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "W neurofibromatozie typu 1 obserwuje się różny stopień nasilenia objawów. Z czym się to wiąże?",
     "mode": "typed", "answers": ["ze zmienną ekspresją (ekspresywnością)"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Jakiej mutacji NIE przekaże chory ojciec swojemu synowi?",
     "mode": "typed", "answers": ["recesywnej sprzężonej z chromosomem X (syn otrzymuje od ojca chromosom Y)"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Ojciec choruje na chorobę recesywną sprzężoną z chromosomem X. Jaką cechę ma jego potomstwo?",
     "mode": "typed", "answers": ["wszyscy synowie są zdrowi, wszystkie córki są nosicielkami"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Na choroby dziedziczone autosomalnie recesywnie chorują najczęściej:",
     "mode": "typed", "answers": ["tak samo często mężczyźni, jak i kobiety"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Delecja tego samego fragmentu chromosomu daje różny fenotyp w zależności od tego, czy pochodzi od matki czy od ojca. Jak nazywa się to zjawisko?",
     "mode": "typed", "answers": ["piętno rodzicielskie / imprinting genomowy"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Jak nazywa się zjawisko, w którym w kolejnych pokoleniach dana choroba zaczyna się coraz wcześniej i przebiega coraz ciężej?",
     "mode": "typed", "answers": ["antycypacja"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Jakiego podłoża molekularnego dotyczy najczęściej antycypacja?",
     "mode": "typed", "answers": ["ekspansji (namnożenia) powtórzeń trójnukleotydowych"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Które zjawisko obserwuje się w chorobie Huntingtona (choroba zaczyna się coraz wcześniej w kolejnych pokoleniach)?",
     "mode": "typed", "answers": ["antycypacja"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Jak nazywa się zjawisko otrzymania obu kopii danego chromosomu od jednego rodzica (a żadnej od drugiego)?",
     "mode": "typed", "answers": ["disomia jednorodzicielska (uniparentalna)"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Czym są mutacje somatyczne?",
     "mode": "typed", "answers": ["mutacje powstające w komórkach somatycznych, niededziczone (nieprzekazywane potomstwu)"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Zjawisko występowania różnic w genotypie między łożyskiem a płodem to:",
     "mode": "typed", "answers": ["mozaicyzm łożyskowy"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Czym jest heteroplazmia mitochondrialna?",
     "mode": "typed", "answers": ["współwystępowaniem w jednej komórce (mitochondrium) zarówno prawidłowego, jak i zmutowanego mtDNA"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Matka ma mutację w mtDNA i troje dzieci (dwoje chorych, jedno zdrowe), ojciec zdrowy. Jaki to typ dziedziczenia?",
     "mode": "typed", "answers": ["dziedziczenie mitochondrialne (matczyne)"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Co jest konieczne, by przeprowadzić badanie genetyczne u pacjenta?",
     "mode": "typed", "answers": ["pisemna, świadoma zgoda pacjenta"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Jakie wytyczne są przydatne przy klasyfikowaniu patogenności wariantów liczby kopii DNA (CNV)?",
     "mode": "typed", "answers": ["wytyczne ACMG (American College of Medical Genetics and Genomics)"]},
    {"category": "Podstawy dziedziczenia — pojęcia i wzorce", "q": "Ojciec ma translokację robertsonowską. Jakie jest prawdopodobieństwo, że kolejno urodzi się dwoje zdrowych dzieci (bez translokacji i bez zespołu wad)?",
     "mode": "typed", "answers": ["0%"]},

    # --- Terminologia dysmorfologii ---
    {"category": "Terminologia dysmorfologii", "q": "Co to jest deformacja (w dysmorfologii)?",
     "mode": "typed", "answers": ["zniekształcenie już prawidłowo zróżnicowanej tkanki pod wpływem działania czynników mechanicznych"]},
    {"category": "Terminologia dysmorfologii", "q": "Co to jest malformacja?",
     "mode": "typed", "answers": ["pierwotne zaburzenie prawidłowego rozwoju (morfogenezy) narządu lub tkanki"]},
    {"category": "Terminologia dysmorfologii", "q": "Co to jest dysrupcja?",
     "mode": "typed", "answers": ["przerwanie prawidłowego procesu rozwojowego przez inny, nieprawidłowy proces"]},

    # --- Cytogenetyka, techniki i aberracje liczbowe ---
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Co to jest tetraploidia?",
     "mode": "typed", "answers": ["poczwórny (4n) garnitur chromosomowy w komórce"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Co charakteryzuje triploidię?",
     "mode": "typed", "answers": ["potrójny (3n) garnitur chromosomowy w komórkach somatycznych"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Trisomia to sytuacja, w której w danej parze chromosomów jest:",
     "mode": "typed", "answers": ["jeden dodatkowy chromosom (łącznie trzy zamiast dwóch)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Który kariotyp/zestaw chromosomów jest LETALNY?",
     "mode": "typed", "answers": ["69,XXX (triploidia)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Nondysjunkcja (brak rozdziału chromosomów) może doprowadzić do:",
     "mode": "typed", "answers": ["trisomii (i może zachodzić także w II podziale mejotycznym)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Kariotyp zawierający i(17)(q10) oznacza obecność:",
     "mode": "typed", "answers": ["izochromosomu złożonego z ramion długich chromosomu 17"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Kolcemid (kolchicyna) w cytogenetyce służy do:",
     "mode": "typed", "answers": ["zatrzymania podziału komórkowego w metafazie poprzez zablokowanie wrzeciona kariokinetycznego (podziałowego)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Jaki jest złoty standard w diagnostyce rdzeniowego zaniku mięśni (SMA)?",
     "mode": "typed", "answers": ["MLPA (Multiplex Ligation-dependent Probe Amplification)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Czego NIE wykryjemy metodą aCGH, a klasycznym kariotypowaniem już tak?",
     "mode": "typed", "answers": ["translokacji wzajemnej (zrównoważonej — aCGH nie wykrywa zmian bez utraty/zysku materiału genetycznego)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Czym wykryjemy aberracje strukturalne często występujące w regionach subtelomerowych?",
     "mode": "typed", "answers": ["metodą aCGH (mikromacierze)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Jak wykryjemy poliploidię?",
     "mode": "typed", "answers": ["metodą FISH oraz klasycznym kariotypowaniem"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Jakie badanie (prążki G) wykryje delecję w zespole Cri du Chat?",
     "mode": "typed", "answers": ["klasyczne prążkowanie G (kariotyp)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "LCR (low copy repeats) to:",
     "mode": "typed", "answers": ["miejsca w genomie podatne na pękanie chromosomów i rearanżacje (np. mikrodelecje/mikroduplikacje)"]},
    {"category": "Cytogenetyka i aberracje chromosomowe", "q": "Prawidłowy kariotyp w zespole Patau to (jeden z możliwych zapisów):",
     "mode": "typed", "answers": ["47,+13 (lub 46,+13,der(13;14)(q10;q10) przy translokacji robertsonowskiej)"]},

    # --- Zespoły z liczbowymi aberracjami chromosomów płciowych i autosomów ---
    {"category": "Zespoły aneuploidii i wad wrodzonych", "q": "Jaki kariotyp jest typowy dla zespołu Turnera?",
     "mode": "typed", "answers": ["45,X"]},
    {"category": "Zespoły aneuploidii i wad wrodzonych", "q": "Pacjent z ginekomastią, hipogonadyzmem i atrofią kanalików nasiennych — jaki to zespół?",
     "mode": "typed", "answers": ["zespół Klinefeltera (47,XXY)"]},
    {"category": "Zespoły aneuploidii i wad wrodzonych", "q": "Pacjent z częstymi infekcjami układu oddechowego, dymorfizmem twarzy, małymi szerokimi stopami i zmarszczką nakątną — jaki to zespół?",
     "mode": "typed", "answers": ["zespół Downa (trisomia 21)"]},

    # --- Zespoły mikrodelecyjne i inne zespoły genetyczne ---
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "W jaki sposób dziedziczone są zespoły mikrodelecyjne (np. zespół DiGeorge'a)?",
     "mode": "typed", "answers": ["autosomalnie dominująco"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "W którym zespole mikrodelecyjnym występują wady stożka naczyniowego serca?",
     "mode": "typed", "answers": ["zespół DiGeorge'a (delecja 22q11.2)"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "W zespole Crouzona przedwcześnie zarasta który szew czaszkowy?",
     "mode": "typed", "answers": ["szew wieńcowy"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Jakie wady mogą powodować kraniosynostozy?",
     "mode": "typed", "answers": ["niedosłuch, upośledzenie rozwoju, małogłowie i inne wady wynikające z przedwczesnego zarośnięcia szwów czaszki"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Cecha charakterystyczna zespołu Retta to:",
     "mode": "typed", "answers": ["regres rozwojowy (utrata nabytych umiejętności, stereotypowe ruchy rąk)"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Który zespół dziedziczony jest dominująco, sprzężony z chromosomem X?",
     "mode": "typed", "answers": ["zespół Retta"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Powtórzenie sekwencji CGG w genie FMR1 jest przyczyną jakiej choroby?",
     "mode": "typed", "answers": ["zespołu łamliwego chromosomu X (zespół Fragile X)"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Jakie objawy typowe są dla zespołu łamliwego chromosomu X?",
     "mode": "typed", "answers": ["opóźnienie rozwojowe (oraz wydłużona twarz, duże odstające uszy, makroorchidyzm)"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Makrosomia, makroglosja, przepuklina pępkowa i hemihiperplazja to objawy jakiego zespołu?",
     "mode": "typed", "answers": ["zespół Beckwitha-Wiedemanna"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Do jakiego wieku dziecka utrzymuje się podwyższone ryzyko nowotworów w zespole Beckwitha-Wiedemanna?",
     "mode": "typed", "answers": ["do ok. 8. roku życia"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Jakie są objawy zespołu Beckwitha-Wiedemanna w okresie noworodkowym?",
     "mode": "typed", "answers": ["duży język (makroglosja), przepuklina pępowinowa, hipoglikemia"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Prawidłowe stwierdzenie o zespole Angelmana (podłoże genetyczne):",
     "mode": "typed", "answers": ["ok. 3-7% przypadków spowodowane jest disomią jednorodzicielską ojcowską"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Wymień zespoły genetyczne przebiegające z otyłością.",
     "mode": "typed", "answers": ["zespół Pradera-Williego, zespół Alstroma, zespół Bardeta-Biedla"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Jakie są objawy neurofibromatozy typu 1?",
     "mode": "typed", "answers": ["plamy typu café-au-lait, guzki Lischa (w tęczówce), glejak nerwu wzrokowego"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "W jakiej chorobie występują naczyniaki zarodkowe (hemangioblastoma)?",
     "mode": "typed", "answers": ["choroba von Hippel-Lindau"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Jak wykrywamy zespół Peutza-Jeghersa (badanie genetyczne)?",
     "mode": "typed", "answers": ["badanie genu STK11 z krwi"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Które cechy dysplazji tanatoforycznej (TD II) NIE są charakterystyczne?",
     "mode": "typed", "answers": ["wady serca (charakterystyczne są za to: makrocefalia, czaszka w kształcie koniczyny, mikromelia)"]},
    {"category": "Zespoły mikrodelecyjne i zespoły wad wrodzonych", "q": "Achondroplazja charakteryzuje się:",
     "mode": "typed", "answers": ["pełną penetracją"]},

    # --- Choroby jednogenowe częste w populacji polskiej ---
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Jaka jest najczęstsza choroba monogenowa dziedziczona autosomalnie DOMINUJĄCO w populacji polskiej?",
     "mode": "typed", "answers": ["hipercholesterolemia rodzinna"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Jaka jest najczęstsza choroba monogenowa dziedziczona autosomalnie RECESYWNIE w populacji polskiej?",
     "mode": "typed", "answers": ["mukowiscydoza"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Jaka jest częstość nosicielstwa mukowiscydozy w populacji polskiej?",
     "mode": "typed", "answers": ["ok. 1:25"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Pacjent z częstymi infekcjami układu oddechowego, u którego wykryto zwłóknienie trzustki — jaka choroba?",
     "mode": "typed", "answers": ["mukowiscydoza"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Mężczyzna z żółtakami (xanthoma) — jaką chorobę należy podejrzewać?",
     "mode": "typed", "answers": ["rodzinną hipercholesterolemię"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Które stwierdzenie prawidłowo opisuje hemofilię A?",
     "mode": "typed", "answers": ["mutacje powodujące przesunięcie ramki odczytu dają ciężką postać choroby"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Co jest FAŁSZYWE w opisie hemofilii A?",
     "mode": "typed", "answers": ["zmniejszona aktywność płytek krwi (hemofilia A to niedobór czynnika VIII krzepnięcia, nie zaburzenie płytek)"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "20-letnia kobieta ma torbiele w nerkach, tak samo jak jej matka. Jaką chorobę należy podejrzewać?",
     "mode": "typed", "answers": ["autosomalną dominującą wielotorbielowatość nerek (ADPKD)"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Jaki gen odpowiada za wielotorbielowatość nerek typu recesywnego?",
     "mode": "typed", "answers": ["PKHD1"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Która choroba dziedziczona jest recesywnie, sprzężona z chromosomem X?",
     "mode": "typed", "answers": ["dystrofia mięśniowa Duchenne'a (DMD)"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Dziecko w wieku późnoszkolnym z przerostem łydek i osłabieniem mięśni, wykryto mutację w genie DMD z delecją 10-25 eksonów. Jaka to choroba?",
     "mode": "typed", "answers": ["dystrofia mięśniowa Beckera (nie Duchenne'a — ten ujawnia się znacznie wcześniej)"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Jaka jest zmiana białka charakterystyczna dla dystrofii miotonicznej (podłoże molekularne)?",
     "mode": "typed", "answers": ["nieprawidłowy splicing (alternatywne składanie mRNA) wskutek ekspansji powtórzeń nukleotydowych"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Pacjent po 40. roku życia: postępujące osłabienie mięśni kończyn dolnych, zaćma. Jaka choroba?",
     "mode": "typed", "answers": ["dystrofia miotoniczna typu 2"]},
    {"category": "Choroby jednogenowe częste w populacji polskiej", "q": "Która choroba jest związana z mutacją dynamiczną (ekspansją powtórzeń)?",
     "mode": "typed", "answers": ["dystrofia miotoniczna"]},

    # --- Zespoły nowotworowe dziedziczne ---
    {"category": "Dziedziczne zespoły nowotworowe", "q": "Jak dziedziczony jest dziedziczny rak piersi i jajnika (mutacje BRCA1/BRCA2)?",
     "mode": "typed", "answers": ["autosomalnie dominująco"]},
    {"category": "Dziedziczne zespoły nowotworowe", "q": "Z jakim ryzykiem nowotworów wiąże się mutacja w genach BRCA1/BRCA2?",
     "mode": "typed", "answers": ["z rakiem piersi u kobiet i mężczyzn, rakiem jajnika oraz rakiem prostaty (wszystkie wymienione)"]},
    {"category": "Dziedziczne zespoły nowotworowe", "q": "Jak dziedziczony jest zespół Lyncha (dziedziczny niepolipowaty rak jelita grubego, HNPCC)?",
     "mode": "typed", "answers": ["autosomalnie dominująco"]},
    {"category": "Dziedziczne zespoły nowotworowe", "q": "Z jakim ryzykiem nowotworów wiąże się zespół Lyncha (HNPCC)?",
     "mode": "typed", "answers": ["z rakiem jelita grubego, endometrium i innymi nowotworami — wszystkie wymienione"]},
    {"category": "Dziedziczne zespoły nowotworowe", "q": "Zespół Cowden wiąże się z mutacją germinalną w genie:",
     "mode": "typed", "answers": ["PTEN"]},
    {"category": "Dziedziczne zespoły nowotworowe", "q": "Czym są geny TSC1 i TSC2 (stwardnienie guzowate)?",
     "mode": "typed", "answers": ["genami supresorowymi nowotworów"]},
    {"category": "Dziedziczne zespoły nowotworowe", "q": "Jaka choroba nowotworowa jest charakterystyczna dla zespołu MEN2?",
     "mode": "typed", "answers": ["rak rdzeniasty tarczycy"]},

    # --- Choroby endokrynne/metaboliczne o podłożu genetycznym ---
    {"category": "Choroby metaboliczne i endokrynne o podłożu genetycznym", "q": "Jak leczy się hemochromatozę?",
     "mode": "typed", "answers": ["upustami krwi (flebotomią)"]},
    {"category": "Choroby metaboliczne i endokrynne o podłożu genetycznym", "q": "Jaka jest najczęstsza mutacja odpowiedzialna za cukrzycę noworodkową?",
     "mode": "typed", "answers": ["mutacja genu kanału potasowego"]},
    {"category": "Choroby metaboliczne i endokrynne o podłożu genetycznym", "q": "Jak dziedziczona jest cukrzyca MODY (związana z genem HNF)?",
     "mode": "typed", "answers": ["autosomalnie dominująco"]},
    {"category": "Choroby metaboliczne i endokrynne o podłożu genetycznym", "q": "Pacjent 35 lat: cukrzyca od 28. roku życia, niedosłuch od dzieciństwa, matka ma te same objawy. Jaka choroba?",
     "mode": "typed", "answers": ["MIDD (maternally inherited diabetes and deafness) — choroba mitochondrialna"]},

    # --- Profilaktyka prenatalna ---
    {"category": "Profilaktyka prenatalna", "q": "Jaki jest główny cel suplementacji kwasem foliowym przed planowaną ciążą?",
     "mode": "typed", "answers": ["profilaktyka wad cewy nerwowej u płodu"]},
]

with open('genetyka_raw.json', 'w', encoding='utf-8') as f:
    json.dump(ITEMS, f, ensure_ascii=False, indent=2)

by_cat = {}
for it in ITEMS:
    by_cat[it['category']] = by_cat.get(it['category'], 0) + 1
for c, n in sorted(by_cat.items()):
    print(n, '-', c)
print('TOTAL', len(ITEMS))
