import fs from 'fs';

const GIELDA_CATEGORY = 'Giełda z sesji (MSN)';

const items = [
  { targetCategory: 'Udrażnianie dróg oddechowych i tlenoterapia', q: 'Jak sprawdzamy, czy prawidłowo założona rurka ustno-gardłowa (UG) skutecznie utrzymuje drożność dróg oddechowych, bez konieczności wentylowania pacjenta workiem AMBU?', o: ['obserwujemy ruch klatki piersiowej i obecność spontanicznego oddechu pacjenta', 'wyłącznie poprzez wykonanie pełnego badania RTG klatki piersiowej', 'wyłącznie poprzez pomiar temperatury ciała pacjenta', 'nie da się w żaden sposób ocenić skuteczności rurki UG bez podłączenia respiratora', 'wyłącznie poprzez ocenę koloru oczu pacjenta'], a: 0, rationale: "Poprawnie: skuteczność prawidłowo założonej rurki ustno-gardłowej można ocenić poprzez obserwację ruchu klatki piersiowej i obecność spontanicznego oddechu pacjenta — jeśli pacjent oddycha samodzielnie, a rurka utrzymuje drożność, klatka piersiowa unosi się i opada w rytm oddechu, bez konieczności aktywnego wentylowania workiem AMBU (rurka UG sama w sobie nie wymaga wentylacji, jedynie podtrzymuje drożność u oddychającego pacjenta). RTG klatki piersiowej nie jest praktyczną, standardową metodą szybkiej oceny funkcji rurki UG przy łóżku pacjenta w warunkach nagłych. Temperatura ciała nie ma związku z oceną skuteczności udrożnienia dróg oddechowych rurką UG. Skuteczność rurki UG MOŻNA ocenić prostymi metodami klinicznymi (obserwacja oddechu/ruchu klatki) bez konieczności podłączania respiratora — stwierdzenie przeciwne jest nieprawdziwe. Kolor oczu pacjenta nie jest metodą oceny drożności dróg oddechowych." },
  { targetCategory: 'Udrażnianie dróg oddechowych i tlenoterapia', q: 'Przy wymienianiu przeciwwskazań do rurki krtaniowej, dlaczego astma i skurcz oskrzeli NIE liczą się jako dwa osobne, odrębne przeciwwskazania (mimo że są wymieniane osobno na liście)?', o: ['ponieważ oba należą do tej samej kategorii przyczynowej — chorób z obturacją/nadreaktywnością dróg oddechowych — więc stanowią jedno wspólne przeciwwskazanie, a osobnym, drugim przeciwwskazaniem jest np. brak ochrony przed aspiracją treści pokarmowej (wymioty)', 'ponieważ astma i skurcz oskrzeli w ogóle nie są przeciwwskazaniami do rurki krtaniowej', 'ponieważ liczba przeciwwskazań nie ma żadnego znaczenia podczas egzaminu praktycznego', 'ponieważ astma zawsze eliminuje możliwość wystąpienia jakiegokolwiek skurczu oskrzeli', 'ponieważ rurka krtaniowa nigdy nie ma żadnych przeciwwskazań'], a: 0, rationale: "Poprawnie: astma i skurcz oskrzeli należą do TEJ SAMEJ, wspólnej kategorii przyczynowej — chorób obturacyjnych/nadreaktywności dróg oddechowych — dlatego liczą się jako JEDNO wspólne przeciwwskazanie do rurki krtaniowej, a nie dwa osobne; aby wymienić DWA rzeczywiście odrębne przeciwwskazania, należy podać tę kategorię (obturacja/nadreaktywność, np. astma LUB POChP LUB skurcz oskrzeli) ORAZ osobną, kategorycznie inną przyczynę, np. brak ochrony przed aspiracją treści pokarmowej (ryzyko wymiotów) — to typowy błąd egzaminacyjny, gdy student wymienia dwa przykłady tej samej kategorii, myśląc że to dwa różne przeciwwskazania. Astma i skurcz oskrzeli SĄ rzeczywistymi przeciwwskazaniami do rurki krtaniowej (należącymi do tej samej kategorii obturacyjnej) — stwierdzenie o ich całkowitym braku znaczenia jest nieprawdziwe. Liczba i kategoryzacja przeciwwskazań MA istotne znaczenie przy odpowiedzi na tego typu pytanie egzaminacyjne — nie jest nieistotna. Astma nie eliminuje możliwości wystąpienia (dodatkowego) skurczu oskrzeli — te pojęcia są ze sobą blisko związane, ale nie wykluczają się wzajemnie. Rurka krtaniowa MA udokumentowane, istotne przeciwwskazania (jak omówione) — stwierdzenie o ich całkowitym braku jest nieprawdziwe." },
];

const raw = JSON.parse(fs.readFileSync('msn_raw.json', 'utf8'));
let added = 0;
for (const item of items) {
  raw.push({ category: item.targetCategory, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  raw.push({ category: GIELDA_CATEGORY, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
  added += 2;
}
fs.writeFileSync('msn_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'unikalnych pytan (x2 =', added, 'wpisow). nowa dlugosc msn_raw.json:', raw.length);
