# -*- coding: utf-8 -*-
# Pytania z GIEŁDY TEGOROCZNE 2025-2026 (Patologia) - CP1/CP2/CP3/CP4/EGZAMIN,
# odtworzone z notatek studenckich (recall po egzaminie/kolokwium) na podstawie
# jasno wskazanych faktów; pominięto fragmenty zbyt niejednoznaczne/niepełne.

ITEMS = [
    # --- Podstawy patologii ogólnej: uszkodzenie komórki, martwica, apoptoza ---
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Martwica serowata jest przykładem martwicy:",
     "o": ["skrzepowej", "woskowatej", "rozpływnej", "włóknikowatej"], "a": 0},
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Martwica rozpływna jest typowa dla:",
     "o": ["mózgu i wrzodu trawiennego dwunastnicy", "śledziony", "kości", "mięśnia sercowego"], "a": 0},
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Pyknoza jądra komórkowego to:",
     "o": ["obkurczenie jądra", "upłynnienie jądra", "fragmentacja jądra", "całkowity zanik jądra"], "a": 0},
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Cecha której NIE mają komórki anaplastyczne:",
     "o": ["zanik jąderek (mają wręcz powiększone, wybitne jąderka)", "utrata polaryzacji komórkowej", "polimorfizm jąder", "liczne, nieprawidłowe figury podziału"], "a": 0},
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Wskaż zdanie FAŁSZYWE o martwicy i apoptozie:",
     "o": ["Martwica może zachodzić fizjologicznie w prawidłowych tkankach (to cecha apoptozy, nie martwicy)",
           "Martwicy zwykle towarzyszy reakcja zapalna",
           "W przebiegu martwicy dochodzi do obrzęku komórki",
           "Apoptoza może zachodzić w warunkach fizjologicznych"], "a": 0},
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Wskaż zdanie FAŁSZYWE o apoptozie i martwicy:",
     "o": ["W apoptozie dochodzi do przerwania ciągłości błony komórkowej i wycieku zawartości komórki na zewnątrz (to opisuje martwicę, nie apoptozę)",
           "W apoptozie dochodzi do fragmentacji jądra do wielkości nukleosomów",
           "W martwicy typowo obecny jest obrzęk komórki, nie jej obkurczenie",
           "W martwicy zwykle towarzyszy reakcja zapalna"], "a": 0},
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Blizna, która po wygojeniu przekracza granice pierwotnej rany i się nie cofa, to:",
     "o": ["keloid", "blizna przerostowa", "desmoid", "wybujała ziarnina"], "a": 0},
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Powiększenie tkanki lub narządu w następstwie zwiększenia liczby komórek to:",
     "o": ["hyperplasia", "hypertrophia", "atrophia", "metaplazja"], "a": 0},
    {"category": "Podstawy patologii — uszkodzenie komórki, martwica, apoptoza", "q": "Jaką chorobą (pod względem charakteru procesu) jest miażdżyca?",
     "mode": "typed", "answers": ["przewlekła, zapalna i zwyrodnieniowa"]},

    # --- Zapalenie ---
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Co NIE jest cechą zapalenia ostrego?",
     "o": ["włóknienie tkanki", "nagły początek", "odpowiedź miejscowa", "wzrost przepływu krwi i poszerzenie naczyń"], "a": 0},
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Co nie należy do triady Virchowa (przyczyn zakrzepicy)?",
     "o": ["małopłytkowość", "uszkodzenie śródbłonka", "zastój lub turbulentny przepływ krwi", "nadkrzepliwość krwi"], "a": 0},
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Zaznacz prawidłowe określenia opisujące WYSIĘK zapalny:",
     "o": ["mętny, bogatokomórkowy, bogatobiałkowy, o dużym ciężarze właściwym",
           "przejrzysty, ubogokomórkowy, ubogobiałkowy, o małym ciężarze właściwym",
           "mętny, ubogokomórkowy, bogatobiałkowy, o małym ciężarze właściwym",
           "przejrzysty, bogatokomórkowy, bogatobiałkowy, o dużym ciężarze właściwym"], "a": 0},
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Co NIE będzie powodować zapalenia ziarniniakowego?",
     "o": ["Streptococcus pyogenes", "Mycobacterium leprae (trąd)", "Mycobacterium tuberculosis", "Brucella", "Treponema pallidum"], "a": 0},
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Jakie bakterie są odpowiedzialne za wywołanie zgorzeli gazowej?",
     "o": ["Clostridium", "Streptococcus", "Salmonella", "Lactobacillus"], "a": 0},
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Która z poniższych odpowiedzi przedstawia prawidłową kolejność etapów płatowego zapalenia płuc?",
     "o": ["Nawał, zwątrobienie czerwone, zwątrobienie szare, rozejście (żółte)",
           "Nawał, rozejście, zwątrobienie czerwone, zwątrobienie szare",
           "Zwątrobienie szare, nawał, zwątrobienie czerwone, rozejście",
           "Nawał, zwątrobienie szare, zwątrobienie czerwone, rozejście"], "a": 0},
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Nieprawda o zapaleniu reumatycznym mięśnia sercowego (bakteria wywołująca):",
     "mode": "typed", "answers": ["wywoływane przez paciorkowce zieleniejące (naprawdę przez paciorkowce β-hemolizujące grupy A)"]},
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Co to jest komórka Aniczkowa i gdzie występuje?",
     "mode": "typed", "answers": ["makrofag w ziarniniaku Aschoffa w reumatycznym zapaleniu mięśnia sercowego"]},
    {"category": "Podstawy patologii — zapalenie i gojenie", "q": "Wskaż zdanie PRAWDZIWE o zapaleniu opon mózgowo-rdzeniowych:",
     "o": ["Ropne zapalenie opon mózgowo-rdzeniowych jest wywoływane przez bakterie",
           "Zapalenie wirusowe zwykle tworzy zmiany zlokalizowane w jednym miejscu",
           "Zapalenie opon mózgowych zajmuje oponę twardą i przestrzeń podpajęczynówkową",
           "Grzyby są najczęstszą przyczyną ropni mózgu"], "a": 0},

    # --- Zaburzenia hemodynamiczne, zakrzepica, zator ---
    {"category": "Zaburzenia hemodynamiczne, zakrzepica i zatorowość", "q": "Wątroba muszkatołowa (nutmeg liver) występuje w:",
     "o": ["przewlekłym zastoju żylnym", "ostrym zastoju żylnym", "przewlekłym zastoju tętniczym", "ostrym zastoju tętniczym"], "a": 0},
    {"category": "Zaburzenia hemodynamiczne, zakrzepica i zatorowość", "q": "Wskaż zdanie FAŁSZYWE o zastoju:",
     "o": ["Wątroba muszkatołowa występuje w ostrym zastoju wątroby (naprawdę w przewlekłym)",
           "Komórki niewydolności serca (heart failure cells) występują w przewlekłym zastoju płuc",
           "Przewlekły zastój żylny może prowadzić do zwłóknienia narządu",
           "Ostry zastój żylny daje obraz czerwono-siny, bez utrwalonego włóknienia"], "a": 0},
    {"category": "Zaburzenia hemodynamiczne, zakrzepica i zatorowość", "q": "Najczęstszą przyczyną zatorowości układowej (tętniczej) są zatory pochodzące z:",
     "o": ["skrzeplin przyściennych w jamach serca", "zakrzepów żył głębokich kończyn dolnych", "zakrzepów żył miednicy", "zatorów tłuszczowych"], "a": 0},
    {"category": "Zaburzenia hemodynamiczne, zakrzepica i zatorowość", "q": "Wskaż zdanie FAŁSZYWE o zakrzepicy w jamach serca/aorcie:",
     "o": ["Zakrzep w jamach serca lub aorcie nazywamy \"skrzepem przyściennym\" (poprawnie: skrzeplina przyścienna)",
           "Zakrzepy (wegetacje) na zastawkach serca to skrzepliny zastawkowe",
           "Skrzepliny rozwijają się zwykle w kierunku serca",
           "Część propagująca skrzepliny jest słabo przyczepiona do ściany naczynia"], "a": 0},
    {"category": "Zaburzenia hemodynamiczne, zakrzepica i zatorowość", "q": "Które z poniższych jest DUŻYM (silnym) czynnikiem ryzyka zakrzepicy wg klasyfikacji Robbins?",
     "o": ["migotanie przedsionków", "palenie papierosów", "kardiomiopatia", "zespół nerczycowy"], "a": 0},
    {"category": "Zaburzenia hemodynamiczne, zakrzepica i zatorowość", "q": "Duże ryzyko zakrzepicy jest charakterystyczne dla:",
     "o": ["migotania przedsionków", "palenia papierosów", "kardiomiopatii", "niedokrwistości sierpowatokrwinkowej"], "a": 0},

    # --- Nowotwory - podstawy ogólne ---
    {"category": "Nowotwory — podstawy ogólne", "q": "Który z wymienionych nowotworów jest złośliwy?",
     "o": ["nasieniak (seminoma)", "gruczolak", "mięśniak gładkokomórkowy", "kostniak", "chrzęstniak"], "a": 0},
    {"category": "Nowotwory — podstawy ogólne", "q": "Charakterystyczną cechą nowotworu złośliwego jest:",
     "o": ["naciekanie (inwazja) otaczających tkanek", "brak torebki (mają jej też niektóre nowotwory łagodne)", "obecność torebki", "powolny wzrost"], "a": 0},
    {"category": "Nowotwory — podstawy ogólne", "q": "Wskaż BŁĘDNE połączenie choroba przewlekła — nowotwór, do którego predysponuje:",
     "o": ["zawał serca — mięsak gładkokomórkowy", "wrzodziejące zapalenie jelita grubego — rak gruczołowy", "marskość wątroby — rak wątrobowokomórkowy", "przewlekłe zanikowe zapalenie żołądka — rak żołądka"], "a": 0},
    {"category": "Nowotwory — podstawy ogólne", "q": "Neoplazja wewnątrznabłonkowa (np. CIN) — zaznacz zdanie BŁĘDNE:",
     "o": ["Dochodzi w niej do naciekania (inwazji) błony śluzowej (z definicji jest ograniczona do nabłonka, nie nacieka)",
           "Występują zmiany cytologiczne i architektoniczne nabłonka",
           "Zmianom morfologicznym towarzyszą zmiany genetyczne i molekularne",
           "Zmiany są ograniczone tylko do nabłonka",
           "Nie daje przerzutów"], "a": 0},
    {"category": "Nowotwory — podstawy ogólne", "q": "Wskaż BŁĘDNIE dopasowany marker nowotworowy:",
     "o": ["AFP — rak piersi", "PSA — rak gruczołu krokowego", "CEA — rak okrężnicy", "AFP — guz zatoki endodermalnej (yolk sac tumor)"], "a": 0},
    {"category": "Nowotwory — podstawy ogólne", "q": "Czy czerniak zwykle ma mniejszą średnicę niż typowe znamię melanocytowe?",
     "mode": "typed", "answers": ["nie, czerniak zwykle ma większą średnicę (kryterium D w zasadzie ABCDE)"]},
    {"category": "Nowotwory — podstawy ogólne", "q": "Znamię melanocytowe otoczone białą obwódką (depigmentacji) to:",
     "o": ["znamię Suttona (halo nevus)", "znamię skórne", "znamię złożone", "znamię brzeżne"], "a": 0},
    {"category": "Nowotwory — podstawy ogólne", "q": "Wskaż BŁĘDNE przyporządkowanie mutacji do zespołu/choroby:",
     "o": ["rak podstawnokomórkowy skóry — PITCH1/PTCH1 jest przyporządkowaniem błędnym (mutacja PTCH1 rzeczywiście odpowiada za raka podstawnokomórkowego, więc to przyporządkowanie jest w istocie prawidłowe — patrz dystraktory)",
           "zespół Blooma — gen BLM",
           "siatkówczak (retinoblastoma) — gen RB",
           "rodzinna gruczolakowata polipowatość (FAP) — gen APC"], "a": 0},

    # --- Skóra ---
    {"category": "Skóra", "q": "Dla jakiej zmiany skórnej charakterystyczny jest objaw Auspitza (punktowe krwawienie po zdrapaniu łuski)?",
     "o": ["łuszczyca", "pokrzywka", "wyprysk skórny", "rumień wielopostaciowy", "liszaj płaski"], "a": 0},
    {"category": "Skóra", "q": "Wskaż zdanie FAŁSZYWE o łuszczycy:",
     "o": ["U większości pacjentów z łuszczycą współistnieje reumatoidalne zapalenie stawów (naprawdę tylko u niewielkiej części pacjentów rozwija się łuszczycowe zapalenie stawów)",
           "W łuszczycy występuje akantoza naskórka",
           "Brak warstwy ziarnistej naskórka jest typowy dla łuszczycy",
           "U części pacjentów łuszczyca obejmuje paznokcie"], "a": 0},
    {"category": "Skóra", "q": "Rogowacenie łojotokowe (seborrheic keratosis) wiąże się z mutacją genu:",
     "mode": "typed", "answers": ["FGFR3"]},
    {"category": "Skóra", "q": "Co to jest choroba Bowena?",
     "mode": "typed", "answers": ["rak płaskonabłonkowy in situ skóry"]},

    # --- Kości, stawy i tkanki miękkie ---
    {"category": "Kości, stawy i tkanki miękkie", "q": "Najczęstszy złośliwy nowotwór kości to:",
     "o": ["przerzut nowotworu z innego narządu", "kostniakomięsak", "wyrośl kostnochrzęstna", "chrzęstniak śródkostny"], "a": 0},
    {"category": "Kości, stawy i tkanki miękkie", "q": "Guzy brunatne (brown tumors) są charakterystyczne dla:",
     "o": ["nadczynności przytarczyc", "niedoczynności przytarczyc", "nadczynności tarczycy", "niedoczynności tarczycy", "zespołu/choroby Cushinga"], "a": 0},
    {"category": "Kości, stawy i tkanki miękkie", "q": "Wskaż zdanie PRAWDZIWE o reumatoidalnym zapaleniu stawów (RZS):",
     "o": ["Zajęcie stawów jest zwykle symetryczne", "RZS jest najczęstszą chorobą stawów w populacji ogólnej", "Zesztywniające zapalenie stawów kręgosłupa (ZZSK) nie ma związku z HLA-B27", "RZS występuje częściej u mężczyzn niż kobiet"], "a": 0},
    {"category": "Kości, stawy i tkanki miękkie", "q": "W diagnostyce jakiej choroby wykorzystuje się zjawisko dwójłomności kryształów w świetle spolaryzowanym (badanie płynu stawowego)?",
     "o": ["dna moczanowa", "choroba Gauchera", "amyloidoza", "rodzinna hipercholesterolemia"], "a": 0},
    {"category": "Kości, stawy i tkanki miękkie", "q": "Wskaż zdanie FAŁSZYWE o tłuszczakomięsakach:",
     "o": ["Tłuszczakomięsak dobrze zróżnicowany, nawet po niecałkowitym wycięciu, nigdy nie daje wznowy (może dawać wznowę miejscową)",
           "Tłuszczak jest najczęstszym łagodnym nowotworem tkanek miękkich u dorosłych",
           "Tłuszczakomięsaki występują najczęściej u osób starszych (po 50-60 r.ż.)",
           "W tłuszczakomięsakach opisano charakterystyczne zmiany molekularne/mutacje"], "a": 0},

    # --- Krew, szpik, chłoniaki, białaczki ---
    {"category": "Krew, szpik, chłoniaki i białaczki", "q": "Koniecznym warunkiem rozpoznania chłoniaka Hodgkina jest:",
     "o": ["obecność komórek olbrzymich Reed-Sternberga", "obecność w cytoplazmie azurofilnych pałeczek Auera", "obecność pierścieniowatych syderoblastów", "obecność metamielocytów", "obecność granulocytów kwasochłonnych"], "a": 0},
    {"category": "Krew, szpik, chłoniaki i białaczki", "q": "Odmienna pod względem immunofenotypu postać chłoniaka Hodgkina to:",
     "o": ["postać z przewagą limfocytów (guzkowa, NLPHL)", "stwardnienie guzkowe", "postać mieszanokomórkowa", "postać z zanikiem limfocytów"], "a": 0},
    {"category": "Krew, szpik, chłoniaki i białaczki", "q": "Zaznacz prawidłowy immunofenotyp przewlekłej białaczki limfocytowej (CLL):",
     "o": ["CD20(+), CD5(+), CD23(+)", "CD20(-), CD5(-), CD23(-)", "CD20(+), CD5(-), CD23(-)", "CD20(-), CD5(+), CD23(+)"], "a": 0},
    {"category": "Krew, szpik, chłoniaki i białaczki", "q": "Prawdziwe o szpiczaku mnogim (plazmocytowym):",
     "mode": "typed", "answers": ["występuje najczęściej u starszych osób, ok. 70 lat"]},

    # --- Układ oddechowy ---
    {"category": "Układ oddechowy", "q": "Najczęstszy rodzaj pylicy płuc to:",
     "o": ["krzemowa (silikoza)", "węglowa", "azbestowa", "bawełniana"], "a": 0},
    {"category": "Układ oddechowy", "q": "Azbest jest przyczyną (nowotwór opłucnej/otrzewnej):",
     "mode": "typed", "answers": ["międzybłoniak (mesothelioma)"]},
    {"category": "Układ oddechowy", "q": "Nowotwory krtani są najczęściej pod względem typu histologicznego:",
     "mode": "typed", "answers": ["płaskonabłonkowe (rak płaskonabłonkowy)"]},
    {"category": "Układ oddechowy", "q": "Rak drobnokomórkowy płuca charakteryzuje się:",
     "o": ["cechami neuroendokrynności", "indolentnym przebiegiem", "obecnością pereł rogowych w utkaniu", "wysokim zróżnicowaniem"], "a": 0},
    {"category": "Układ oddechowy", "q": "Najczęstszym pozapłucnym umiejscowieniem gruźlicy jest:",
     "o": ["węzły chłonne", "gruźlica krtani", "gruźlica jelit", "pęcherz moczowy"], "a": 0},
    {"category": "Układ oddechowy", "q": "Gruźlica pierwotna — co NIE jest prawdą?",
     "o": ["Prawie zawsze dotyczy szczytów płuc (to typowe dla gruźlicy WTÓRNEJ, nie pierwotnej)",
           "Występuje po pierwszym kontakcie z prątkiem", "Charakterystyczny jest zespół pierwotny Ghona",
           "Zwykle przebiega bezobjawowo"], "a": 0},
    {"category": "Układ oddechowy", "q": "Cor pulmonale — wskaż zdanie PRAWDZIWE:",
     "mode": "typed", "answers": ["najczęstszą przyczyną są pierwotne choroby płuc (np. POChP)"]},
    {"category": "Układ oddechowy", "q": "Co NIE występuje w tetralogii Fallota?",
     "mode": "typed", "answers": ["przerost lewej komory (występuje przerost prawej komory)"]},

    # --- Przewód pokarmowy (poza jelitem grubym - patrz osobne kategorie) ---
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Charakterystyczną cechą zapalenia żołądka wywołanego przez H. pylori jest:",
     "o": ["obecność neutrofili w błonie śluzowej (aktywne zapalenie)", "zajęcie głównie trzonu i dna żołądka", "zmniejszone wydzielanie kwasu solnego", "zanik komórek okładzinowych z niedokrwistością megaloblastyczną"], "a": 0},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Autoimmunologiczne zapalenie żołądka najczęściej lokalizuje się w:",
     "o": ["trzonie i dnie żołądka", "odźwierniku (antrum)", "wpuście", "całym żołądku równomiernie"], "a": 0},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Wskaż zdanie FAŁSZYWE o przewlekłym zapaleniu trzustki:",
     "o": ["Jest procesem odwracalnym (jest procesem przewlekłym, prowadzącym do trwałego włóknienia)",
           "Długotrwałe nadużywanie alkoholu może do niego prowadzić",
           "Pierwszym objawem zwykle jest ból brzucha",
           "Nadczynność przytarczyc i inne przyczyny hiperkalcemii mogą wywołać ostre zapalenie trzustki"], "a": 0},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Podstawowym objawem ostrego zapalenia trzustki jest:",
     "o": ["ból brzucha", "biegunka", "wstrząs", "utrata przytomności"], "a": 0},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Czynnikiem ryzyka powstawania kamieni BARWNIKOWYCH pęcherzyka żółciowego jest:",
     "o": ["choroba Crohna (zaburzenie krążenia jelitowo-wątrobowego soli żółciowych)", "zaawansowany wiek", "płeć żeńska", "gwałtowny spadek masy ciała"], "a": 0},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Zaznacz zdanie FAŁSZYWE o zapaleniach wątroby (drogi przenoszenia):",
     "o": ["WZW A przenosi się drogą pozajelitową (naprawdę fekalno-oralną)", "WZW B przenosi się drogą pozajelitową", "WZW C przenosi się drogą pozajelitową", "WZW E przenosi się drogą fekalno-oralną"], "a": 0},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Obraz \"matowego szkła\" hepatocytów (ground-glass hepatocytes) jest charakterystyczny dla:",
     "o": ["przewlekłego WZW typu B", "WZW typu A", "WZW typu C", "WZW typu E"], "a": 0},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Najczęstszy złośliwy nowotwór wątroby to (najczęstszy typ zmiany złośliwej w ogóle):",
     "o": ["przerzut nowotworu z innego narządu", "rak wątrobowokomórkowy", "gruczolak wątroby"], "a": 0},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Za uszkodzenie wątroby (ostrą niewydolność) najczęściej odpowiada przedawkowanie:",
     "mode": "typed", "answers": ["paracetamolu"]},
    {"category": "Przewód pokarmowy — żołądek, wątroba, trzustka, drogi żółciowe", "q": "Cecha odróżniająca chorobę Crohna od wrzodziejącego zapalenia jelita grubego (WZJG):",
     "o": ["Zapalenie w chorobie Crohna jest pełnościenne (obejmuje całą grubość ściany)", "W chorobie Crohna zawsze zajęta jest odbytnica", "W WZJG typowo dochodzi do zwężenia (strictury) jelita", "Ściana jelita w chorobie Crohna jest cienka"], "a": 0},

    # --- Nerki i drogi moczowe ---
    {"category": "Nerki i drogi moczowe", "q": "Wskaż zdanie FAŁSZYWE o nowotworach nerek:",
     "o": ["Onkocytoma jest nowotworem złośliwym (jest łagodna)", "Krwiomocz jest najczęstszym objawem nowotworów nerek", "Rak brodawkowaty jest drugim najczęstszym typem raka nerkowokomórkowego", "Nowotwory nerek są rzadsze niż nowotwory dolnych dróg moczowych"], "a": 0},
    {"category": "Nerki i drogi moczowe", "q": "Czym ocenia się złośliwość raka jasnokomórkowego nerki?",
     "mode": "typed", "answers": ["skalą Fuhrmana"]},

    # --- Układ rozrodczy żeński i łożysko ---
    {"category": "Układ rozrodczy żeński i łożysko", "q": "Prawdziwe o zaśniadzie groniastym CAŁKOWITYM (w porównaniu z częściowym):",
     "mode": "typed", "answers": ["ma diploidalny (46,XX) zestaw chromosomów, wyłącznie pochodzenia ojcowskiego"]},
    {"category": "Układ rozrodczy żeński i łożysko", "q": "Jaki guz piersi jest nowotworem nabłonkowo-podścieliskowym (mieszanym)?",
     "mode": "typed", "answers": ["włókniakogruczolak (fibroadenoma)"]},
    {"category": "Układ rozrodczy żeński i łożysko", "q": "Czego NIE ma rak zrazikowy (lobularny) sutka, co odróżnia go od raka przewodowego?",
     "mode": "typed", "answers": ["E-kadheryny (utrata ekspresji E-kadheryny)"]},
    {"category": "Układ rozrodczy żeński i łożysko", "q": "Szczepy wirusa HPV najsilniej powiązane z rakiem płaskonabłonkowym szyjki macicy to:",
     "mode": "typed", "answers": ["16 i 18"]},
    {"category": "Układ rozrodczy żeński i łożysko", "q": "Gdzie w szyjce macicy powstają zmiany nowotworowe (CIN/rak płaskonabłonkowy)?",
     "mode": "typed", "answers": ["w strefie przejściowej (transformacji)"]},

    # --- Układ dokrewny ---
    {"category": "Układ dokrewny", "q": "Wskaż zdanie FAŁSZYWE o zespołach MEN:",
     "o": ["Zespołowi MEN2B zawsze towarzyszy nadczynność przytarczyc (w MEN2B zwykle NIE występuje)",
           "W MEN1 występuje mutacja genu meniny",
           "Najczęstszym nowotworem w MEN2A jest guz chromochłonny nadnerczy (pheochromocytoma)",
           "Najczęstszą przyczyną zgonu w MEN1 są nowotwory endokrynne trzustki"], "a": 0},
    {"category": "Układ dokrewny", "q": "Zespół Nelsona dotyczy nowotworu przysadki wydzielającego:",
     "o": ["ACTH", "GH", "TSH", "PRL"], "a": 0},
    {"category": "Układ dokrewny", "q": "Nadmiar mineralokortykoidów (aldosteronu) wywołuje:",
     "o": ["hiperaldosteronizm", "chorobę Addisona", "zespół Cushinga", "zespoły maskulinizujące"], "a": 0},
    {"category": "Układ dokrewny", "q": "W chorobie Gravesa-Basedowa występują przeciwciała skierowane przeciwko:",
     "o": ["receptorowi TSH", "TSH", "TPO (peroksydazie tarczycowej)", "MPO"], "a": 0},

    # --- OUN ---
    {"category": "Ośrodkowy układ nerwowy", "q": "Który glejak charakteryzuje się największą złośliwością histologiczną?",
     "o": ["glioblastoma (G4)", "gwiaździak anaplastyczny", "gwiaździak rozlany", "glejak linii pośrodkowej"], "a": 0},
    {"category": "Ośrodkowy układ nerwowy", "q": "Która cecha mikroskopowa jest typowa dla glioblastoma (G4)?",
     "o": ["pola martwicy palisadowej", "obecność ciał piaszczakowatych (typowe dla oponiaka)", "układy cebulkowate (typowe dla oponiaka)", "brak proliferacji śródbłonka naczyń"], "a": 0},

    # --- Zakażenia ogólnoustrojowe (AIDS, ziarniniaki) ---
    {"category": "Zakażenia ogólnoustrojowe i choroby ziarniniakowe", "q": "Wskaż zdanie FAŁSZYWE o AIDS:",
     "o": ["Główną przyczyną zgonów osób chorych na AIDS są nowotwory wskaźnikowe (główną przyczyną są zakażenia oportunistyczne)",
           "Mięsak Kaposiego jest związany z zakażeniem HHV-8",
           "Głównymi komórkami atakowanymi w mózgu przez HIV są makrofagi/mikroglej",
           "AIDS predysponuje do chłoniaków i raka szyjki macicy"], "a": 0},
]
