# -*- coding: utf-8 -*-
# Propedeutyka chorób wewnętrznych (Rok 3) - nowy przedmiot od zera.
# Źródła: własny folder Giełdy tegoroczne — "wejściówka 2025_2026.docx" i
# "zaliczenie końcowe 2025_2026.docx" (recall z wielu terminów/grup w ciągu roku,
# bardzo bogaty bank pytań z jasnymi odpowiedziami). Brak tego przedmiotu w
# GIEŁDY TEGOROCZNE (folder osobny, ogólnouczelniany).
import json

ITEMS = [
    # --- Badanie podmiotowe i wywiad ---
    {"category": "Badanie podmiotowe i wywiad", "q": "Czy wywiad lekarski zawsze można przeprowadzić z pacjentem?",
     "mode": "typed", "answers": ["nie zawsze bezpośrednio z pacjentem, ale zawsze się go przeprowadza (uzupełniając wywiadem od rodziny/opiekuna) — uzupełnia się go badaniem przedmiotowym i badaniami dodatkowymi"]},
    {"category": "Badanie podmiotowe i wywiad", "q": "Co to jest dysfagia?",
     "mode": "typed", "answers": ["trudność/utrudnienie w przełykaniu pokarmu"]},
    {"category": "Badanie podmiotowe i wywiad", "q": "Co oznacza ortopnoe?",
     "mode": "typed", "answers": ["duszność nasilająca się w pozycji leżącej, ustępująca lub zmniejszająca się w pozycji siedzącej"]},
    {"category": "Badanie podmiotowe i wywiad", "q": "Jaki objaw jest NIETYPOWY dla dusznicy bolesnej (stabilnej choroby wieńcowej)?",
     "mode": "typed", "answers": ["ustępowanie bólu po oddychaniu lub podczas aktywności fizycznej (typowa dusznica ustępuje po ODPOCZYNKU lub nitroglicerynie, nie w trakcie wysiłku)"]},
    {"category": "Badanie podmiotowe i wywiad", "q": "Dla zapalenia jakiego narządu typowy jest ból opasujący?",
     "mode": "typed", "answers": ["trzustki"]},

    # --- Skale kliniczne i stany świadomości ---
    {"category": "Skale kliniczne i ocena stanu pacjenta", "q": "Jak nazywamy stan chorego, którego obudzić można jedynie pod wpływem silnych bodźców bólowych?",
     "mode": "typed", "answers": ["stupor (sopor)"]},
    {"category": "Skale kliniczne i ocena stanu pacjenta", "q": "Ile punktów w skali Glasgow (GCS) uzyska pacjent, który samodzielnie otwiera oczy, pojękuje (odpowiedź słowna niezrozumiała) i wykazuje reakcję obronną na ból?",
     "mode": "typed", "answers": ["12 punktów (oczy 4 + słowna 3 + ruchowa 5, lub odpowiednio wg wariantu pytania — liczyć wg schematu E+V+M)"]},
    {"category": "Skale kliniczne i ocena stanu pacjenta", "q": "Ile punktów w skali Glasgow uzyska pacjent, który NIE otwiera oczu, pojękuje i broni się przed bólem?",
     "mode": "typed", "answers": ["7 punktów (oczy 1 + słowna 2 + ruchowa 4 = 7)"]},
    {"category": "Skale kliniczne i ocena stanu pacjenta", "q": "Jaka jest klasa CCS (Canadian Cardiovascular Society) u pacjenta, który odczuwa dusznicę bolesną i zmęczenie już w spoczynku?",
     "mode": "typed", "answers": ["klasa IV"]},
    {"category": "Skale kliniczne i ocena stanu pacjenta", "q": "Jaka jest klasa CCS, jeśli objawy dusznicy pojawiają się po przejściu ponad 200 metrów?",
     "mode": "typed", "answers": ["klasa II"]},
    {"category": "Skale kliniczne i ocena stanu pacjenta", "q": "Która skala kliniczna NIE dotyczy oceny duszności: NYHA, skala Levine'a, skala Borga, mMRC?",
     "mode": "typed", "answers": ["skala Levine'a (służy do oceny natężenia szmeru sercowego, nie duszności)"]},
    {"category": "Skale kliniczne i ocena stanu pacjenta", "q": "Odleżyna zajmująca naskórek i skórę właściwą, z widocznym gojeniem i żółtym wysiękiem — jaki to stopień odleżyny?",
     "mode": "typed", "answers": ["III stopień"]},

    # --- Badanie przedmiotowe ogólne — objawy i odruchy ---
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Uszkodzeniem jakiego nerwu jest tzw. \"ręka opadająca\"?",
     "mode": "typed", "answers": ["nerwu promieniowego"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Uszkodzeniem jakiego nerwu jest \"ręka szponiasta\"?",
     "mode": "typed", "answers": ["nerwu łokciowego"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Który objaw oponowy: Brudzińskiego, czy inny?",
     "mode": "typed", "answers": ["objaw Brudzińskiego (bierne zgięcie karku wywołuje zgięcie kończyn dolnych w stawach biodrowych i kolanowych)"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Na czym polega objaw Graefego?",
     "mode": "typed", "answers": ["opóźnianie się powieki górnej za gałką oczną poruszającą się w dół (lid lag) — objaw oczny w nadczynności tarczycy"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Na czym polega objaw Stellwaga?",
     "mode": "typed", "answers": ["rzadkie mruganie — objaw oczny w nadczynności tarczycy"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Na czym polega objaw Moebiusa?",
     "mode": "typed", "answers": ["niezdolność oka do zbieżnego ustawienia (osłabienie konwergencji) — oko nie nadąża za zbliżającym się palcem, objaw w nadczynności tarczycy"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Czym jest wybroczyna (petocja)?",
     "mode": "typed", "answers": ["drobny wylew krwi do skóry, który NIE blednie pod wpływem ucisku"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Guzki Heberdena (stawy międzypaliczkowe dalsze) są charakterystyczne dla:",
     "mode": "typed", "answers": ["choroby zwyrodnieniowej stawów"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Guzki Boucharda (stawy międzypaliczkowe bliższe) są charakterystyczne dla:",
     "mode": "typed", "answers": ["choroby zwyrodnieniowej stawów"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Starsza pacjentka zgłasza bóle stawów i poranne zesztywnienie stawów. Jaka to najbardziej prawdopodobna choroba?",
     "mode": "typed", "answers": ["reumatoidalne zapalenie stawów"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Kiedy mogą występować palce pałeczkowate?",
     "mode": "typed", "answers": ["we wrodzonych wadach serca, wrzodziejącym zapaleniu jelit oraz w przewlekłych chorobach układu oddechowego"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "72-letnia pacjentka zgłasza ból nóg; w badaniu widoczne brązowe przebarwienia skóry na podudziach. Najbardziej prawdopodobna przyczyna?",
     "mode": "typed", "answers": ["przewlekła niewydolność żylna kończyn dolnych"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Jakie są objawy skazy małopłytkowej?",
     "mode": "typed", "answers": ["obfite krwawienia miesiączkowe, obfite krwawienia po urazie, zmiany skórne (wybroczyny), które nie blednące przy ucisku"]},
    {"category": "Badanie przedmiotowe ogólne — objawy", "q": "Pacjentka leczona heparyną z powodu zatorowości płucnej nagle ma spadek liczby płytek krwi. Co podejrzewasz?",
     "mode": "typed", "answers": ["małopłytkowość poheparynową (HIT)"]},

    # --- Badanie klatki piersiowej — osłuchiwanie i opukiwanie płuc ---
    {"category": "Badanie klatki piersiowej — płuca", "q": "Co obejmuje osłuchiwanie SZCZEGÓŁOWE płuc?",
     "mode": "typed", "answers": ["dołki nadobojczykowe, okolice nadgrzebieniowe, okolicę międzyłopatkową (górną/środkową/dolną) oraz okolice podłopatkowe — symetrycznie"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Jakie szmery oddechowe są PRAWIDŁOWE przy osłuchiwaniu płuc?",
     "mode": "typed", "answers": ["szmer pęcherzykowy nad większością pól płucnych, szmer oskrzelowy nad tchawicą i dużymi oskrzelami"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Czym jest stridor?",
     "mode": "typed", "answers": ["świst wdechowy (zwężenie górnych dróg oddechowych)"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "W jakiej fazie oddychania słyszalne są trzeszczenia i w jakich chorobach występują?",
     "mode": "typed", "answers": ["na wdechu; w obrzęku płuc i zapaleniach płuc"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Pacjent z osłabioną ruchomością klatki piersiowej, stłumionym odgłosem opukowym, wzmożonym drżeniem piersiowym i rzężeniami nad lewym płucem, odkrztusza żółtą wydzielinę. Jaka to choroba?",
     "mode": "typed", "answers": ["zapalenie (lewego) płuca"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Jakie są cechy osłuchowo-opukowe płynu w jamie opłucnej?",
     "mode": "typed", "answers": ["stłumiony (ściszony) odgłos opukowy oraz ściszony/zniesiony szmer pęcherzykowy, osłabione drżenie piersiowe"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Osłuchujemy klatkę piersiową: ściszenie szmeru pęcherzykowego w lewym polu płucnym, poniżej dolnej łopatki. Co to najpewniej jest?",
     "mode": "typed", "answers": ["płyn w lewej jamie opłucnej"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Jakie są cechy niedodmy z zatkania (obturacyjnej) w badaniu przedmiotowym?",
     "mode": "typed", "answers": ["stłumiony odgłos opukowy, osłabione drżenie piersiowe i osłabiony (zniesiony) szmer oddechowy"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Co może powodować jednostronne ograniczenie ruchomości oddechowej klatki piersiowej?",
     "mode": "typed", "answers": ["włóknienie płuca, wysięk/płyn w jamie opłucnej"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Gdzie typowo znajduje się dolna granica prawego płuca w linii środkowoobojczykowej?",
     "mode": "typed", "answers": ["na wysokości VI żebra w linii środkowoobojczykowej (linia mostkowa/przymostkowa V żebro)"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Czym charakteryzuje się oddech Kussmaula i kiedy występuje?",
     "mode": "typed", "answers": ["głęboki, przyspieszony, miarowy oddech — typowy dla kwasicy metabolicznej (np. cukrzycowej kwasicy ketonowej)"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Czym charakteryzuje się oddech Biota?",
     "mode": "typed", "answers": ["szybki, płytki oddech przerywany okresami bezdechu (nieregularny), spotykany w uszkodzeniach OUN"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Jakie objawy alarmowe przy gorączce wymagają pilnej uwagi?",
     "mode": "typed", "answers": ["ciśnienie skurczowe <90 mmHg (i inne cechy niestabilności hemodynamicznej)"]},
    {"category": "Badanie klatki piersiowej — płuca", "q": "Jakie są objawy alarmowe przewlekłego kaszlu wymagające pogłębionej diagnostyki?",
     "mode": "typed", "answers": ["krwioplucie, duszność, chudnięcie, wymioty i inne objawy ogólne"]},

    # --- Badanie układu krążenia — osłuchiwanie serca, tętno ---
    {"category": "Badanie układu krążenia", "q": "Gdzie osłuchujemy zastawkę aortalną?",
     "mode": "typed", "answers": ["II międzyżebrze przy prawym brzegu mostka"]},
    {"category": "Badanie układu krążenia", "q": "Gdzie osłuchujemy zastawkę pnia płucnego?",
     "mode": "typed", "answers": ["II międzyżebrze przy lewym brzegu mostka"]},
    {"category": "Badanie układu krążenia", "q": "Co to jest uderzenie koniuszkowe i gdzie typowo je wyczuwamy?",
     "mode": "typed", "answers": ["wyczuwalne palpacyjnie uderzenie koniuszka serca, typowo w V międzyżebrzu w linii środkowoobojczykowej lewej"]},
    {"category": "Badanie układu krążenia", "q": "Jaki szmer daje stenoza (zwężenie) zastawki aortalnej i dokąd promieniuje?",
     "mode": "typed", "answers": ["szmer skurczowy, najgłośniejszy w II międzyżebrzu prawym przy mostku, promieniujący do tętnic szyjnych"]},
    {"category": "Badanie układu krążenia", "q": "Jaki szmer daje niedomykalność zastawki aortalnej?",
     "mode": "typed", "answers": ["szmer rozkurczowy, najlepiej słyszalny wzdłuż lewego brzegu mostka (punkt Erba)"]},
    {"category": "Badanie układu krążenia", "q": "Jakie tętno jest charakterystyczne dla niedomykalności zastawki aortalnej?",
     "mode": "typed", "answers": ["tętno chybkie i wysokie (tętno Corrigana)"]},
    {"category": "Badanie układu krążenia", "q": "Co oznacza bardzo głośny szmer nad zastawką mitralną?",
     "mode": "typed", "answers": ["wadę zastawki mitralnej (np. niedomykalność lub zwężenie)"]},
    {"category": "Badanie układu krążenia", "q": "Kiedy fizjologicznie może wystąpić bradykardia?",
     "mode": "typed", "answers": ["podczas snu, u wytrenowanych sportowców, przy zwiększonym napięciu nerwu błędnego"]},
    {"category": "Badanie układu krążenia", "q": "Na czym polega paradoksalne tętno żylne (objaw Kussmaula)? W jakich chorobach występuje?",
     "mode": "typed", "answers": ["wzrost wypełnienia żył szyjnych podczas wdechu (zamiast spadku) — występuje w zaciskającym zapaleniu osierdzia oraz zwężeniu zastawki trójdzielnej"]},
    {"category": "Badanie układu krążenia", "q": "Jakie są przyczyny nadmiernego wypełnienia żył szyjnych?",
     "mode": "typed", "answers": ["niewydolność serca prawokomorowa, tamponada serca, zaciskające zapalenie osierdzia, odma prężna"]},
    {"category": "Badanie układu krążenia", "q": "Jakie są swoiste objawy niewydolności serca w badaniu przedmiotowym?",
     "mode": "typed", "answers": ["rytm cwałowy, wypełnione (poszerzone) żyły szyjne, dodatni objaw wątrobowo-szyjny, przemieszczone uderzenie koniuszkowe"]},

    # --- Badanie jamy brzusznej ---
    {"category": "Badanie jamy brzusznej", "q": "Co ocenia orientacyjne obmacywanie (palpacja) jamy brzusznej?",
     "mode": "typed", "answers": ["stopień napięcia powłok brzusznych, obecność płynu i gazów w jamie otrzewnej, opory patologiczne oraz zaburzenia czucia skórnego"]},
    {"category": "Badanie jamy brzusznej", "q": "Kiedy stwierdzamy wzmożone (napięte) powłoki brzuszne w badaniu palpacyjnym?",
     "mode": "typed", "answers": ["w zapaleniu otrzewnej oraz przy obecności gazów i płynu w jamie otrzewnej"]},
    {"category": "Badanie jamy brzusznej", "q": "Na czym polega objaw Blumberga?",
     "mode": "typed", "answers": ["ból przy nagłym zwolnieniu ucisku powłok brzusznych (objaw otrzewnowy)"]},
    {"category": "Badanie jamy brzusznej", "q": "Jakie objawy są charakterystyczne dla ostrego zapalenia wyrostka robaczkowego?",
     "mode": "typed", "answers": ["objaw Rovsinga, objaw Jaworskiego, objaw kaszlowy, objaw Blumberga"]},
    {"category": "Badanie jamy brzusznej", "q": "Objaw Chełmońskiego (bolesność przy opukiwaniu prawego łuku żebrowego) wskazuje na:",
     "mode": "typed", "answers": ["zapalenie pęcherzyka żółciowego"]},
    {"category": "Badanie jamy brzusznej", "q": "Objaw Cullena wskazuje na:",
     "mode": "typed", "answers": ["ostre zapalenie trzustki (zasinienie w okolicy pępka)"]},
    {"category": "Badanie jamy brzusznej", "q": "Jakie objawy są charakterystyczne dla ostrego zapalenia trzustki?",
     "mode": "typed", "answers": ["objaw Cullena i objaw Grey-Turnera"]},
    {"category": "Badanie jamy brzusznej", "q": "Co oznacza ból w lewym dolnym kwadrancie brzucha?",
     "mode": "typed", "answers": ["najczęściej ostre zapalenie uchyłków esicy"]},
    {"category": "Badanie jamy brzusznej", "q": "Młoda kobieta z bólem w lewym podbrzuszu — co należy najpierw wykluczyć?",
     "mode": "typed", "answers": ["ciążę ektopową (a także zapalenie uchyłków)"]},
    {"category": "Badanie jamy brzusznej", "q": "Jednostronny dodatni objaw Goldflama (bolesność przy opukiwaniu okolicy lędźwiowej) wskazuje na:",
     "mode": "typed", "answers": ["kamicę moczową lub odmiedniczkowe zapalenie nerek"]},
    {"category": "Badanie jamy brzusznej", "q": "Jaki zestaw objawów opisuje dolegliwości dyzuryczne?",
     "mode": "typed", "answers": ["ból podczas oddawania moczu, częste oddawanie moczu, bolesne parcie na pęcherz"]},
    {"category": "Badanie jamy brzusznej", "q": "Zatrzymanie gazów i stolca wskazuje na:",
     "mode": "typed", "answers": ["niedrożność przewodu pokarmowego"]},
    {"category": "Badanie jamy brzusznej", "q": "Jakie schorzenia POZABRZUSZNE mogą powodować ból brzucha?",
     "mode": "typed", "answers": ["zapalenie płuc, ostry zespół wieńcowy, półpasiec"]},
    {"category": "Badanie jamy brzusznej", "q": "Kiedy występuje wodobrzusze — jakie są jego przyczyny?",
     "mode": "typed", "answers": ["rak jajnika, rak trzustki, alkoholowa marskość wątroby, niewydolność serca prawokomorowa, zespół nerczycowy"]},
    {"category": "Badanie jamy brzusznej", "q": "Jakie są objawy marskości wątroby?",
     "mode": "typed", "answers": ["rumień dłoniowy, pajączki naczyniowe, wodobrzusze"]},
    {"category": "Badanie jamy brzusznej", "q": "Mężczyzna 60 lat, silny ból w nadbrzuszu promieniujący do kręgosłupa po obfitym posiłku, blady, spocony, BP 160/70. Jaka powinna być diagnostyka różnicowa?",
     "mode": "typed", "answers": ["zawał serca, rozwarstwienie aorty, perforacja wrzodu żołądka, ostre zapalenie trzustki (wszystkie wymienione)"]},
    {"category": "Badanie jamy brzusznej", "q": "Jakie są objawy rozwarstwienia aorty?",
     "mode": "typed", "answers": ["nagły, silny, rozdzierający ból w klatce piersiowej/plecach, promieniujący wzdłuż przebiegu aorty"]},
    {"category": "Badanie jamy brzusznej", "q": "Ból opłucnowy — jakie ma cechy i co go łagodzi?",
     "mode": "typed", "answers": ["kłujący, ostry, nasila się przy oddychaniu; ustępuje/łagodnieje przy leżeniu na stronie bolesnej"]},
    {"category": "Badanie jamy brzusznej", "q": "Co pogarsza (nasila) ból osierdziowy?",
     "mode": "typed", "answers": ["leżenie na plecach oraz oddychanie/kaszel; łagodzi go pochylenie do przodu"]},

    # --- EKG — podstawy i interpretacja ---
    {"category": "EKG — podstawy i interpretacja", "q": "Jak mierzymy odstęp PQ w EKG i co on obejmuje?",
     "mode": "typed", "answers": ["od początku załamka P do początku zespołu QRS; obejmuje depolaryzację przedsionków i przewodzenie przez węzeł AV, prawidłowo trwa 120-200 ms"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jakie są cechy prawidłowego rytmu zatokowego w EKG?",
     "mode": "typed", "answers": ["załamek P dodatni w odprowadzeniach I, II, aVF, ujemny w aVR; każdemu załamkowi P odpowiada zespół QRS"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Wskaż grupy odprowadzeń EKG sąsiadujących ze sobą.",
     "mode": "typed", "answers": ["II, III, aVF (ściana dolna) oraz I, aVL, V5, V6 (ściana boczna); a także V1-V6 (przednia)"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jaka jest typowa cecha EKG w migotaniu przedsionków?",
     "mode": "typed", "answers": ["brak załamków P (obecność fali migotania) oraz niemiarowa czynność komór"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Co świadczy o częstoskurczu przedsionkowym (trzepotaniu przedsionków) w EKG?",
     "mode": "typed", "answers": ["fale trzepotania (brak typowych załamków P) i częstość rytmu przedsionków ok. 240-300/min"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Ile wynosi typowa częstość rytmu przedsionków (HR) w trzepotaniu przedsionków?",
     "mode": "typed", "answers": ["ok. 300/min"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Gdzie typowo obserwujemy poszerzony zespół QRS?",
     "mode": "typed", "answers": ["w bloku lewej odnogi pęczka Hisa (LBBB)"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jakie są cechy EKG bloku lewej odnogi pęczka Hisa (LBBB)?",
     "mode": "typed", "answers": ["poszerzony zespół QRS oraz odcinek ST i załamek T przeciwstawne (dyskordantne) do głównego wychylenia zespołu QRS"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jakie są cechy EKG przerostu lewej komory serca?",
     "mode": "typed", "answers": ["wysoki załamek R w odprowadzeniach lewokomorowych (np. V5-V6) i głęboki S w V1-V2, spełniające odpowiednie wskaźniki napięciowe (np. wskaźnik Sokołowa-Lyona)"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jakie są cechy EKG przerostu prawej komory serca?",
     "mode": "typed", "answers": ["R w V1 ≥ 7 mm, R/S w V1 > 1 (dominujący załamek R w V1, np. R w V1 = 8mm, aVR = 7mm)"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Odstęp PQ przy bloku przedsionkowo-komorowym I stopnia wynosi:",
     "mode": "typed", "answers": ["powyżej 200 ms (np. ok. 220 ms — stały, wydłużony odstęp PQ)"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jakie są kryteria rozpoznania przebytego zawału serca w EKG?",
     "mode": "typed", "answers": ["jakikolwiek załamek Q w V2-V3 ≥0,02s lub zespół QS w V2-V3; załamek Q ≥0,03s i głębokości ≥1mm (lub QS) w co najmniej 2 sąsiadujących odprowadzeniach (I, aVL, V4-V6, II, III, aVF); załamek R ≥0,04s w V1-V2 z R/S≥1 i dodatnim załamkiem T bez zaburzeń przewodzenia"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jaki obraz EKG sugeruje ostrą zatorowość płucną (poza tachykardią i dusznością)?",
     "mode": "typed", "answers": ["prawogram, zespół S1Q3T3, blok prawej odnogi pęczka Hisa (RBBB)"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jakie są cechy EKG preekscytacji (zespołu WPW)?",
     "mode": "typed", "answers": ["skrócenie odstępu PQ, poszerzenie zespołu QRS, fala delta na ramieniu WSTĘPUJĄCYM zespołu QRS"]},
    {"category": "EKG — podstawy i interpretacja", "q": "Jakie są cechy p pulmonale w EKG?",
     "mode": "typed", "answers": ["wysoki, spiczasty załamek P (>2,5 mm) w odprowadzeniach II, III, aVF — cecha przerostu prawego przedsionka"]},

    # --- Choroby układu krążenia — obraz kliniczny ---
    {"category": "Choroby układu krążenia — obraz kliniczny", "q": "Pacjent z obniżoną tolerancją wysiłku, obrzękami, nykturią, trzeszczeniami nad płucami, dusznością i kołataniem serca. Jaka to najpewniej choroba?",
     "mode": "typed", "answers": ["niewydolność serca"]},
    {"category": "Choroby układu krążenia — obraz kliniczny", "q": "Pacjent z przebytym zawałem, utrwalonym migotaniem przedsionków, obniżoną tolerancją wysiłku, obrzękami nóg i dusznością nocną — jakie wstępne rozpoznanie?",
     "mode": "typed", "answers": ["niewydolność serca"]},
    {"category": "Choroby układu krążenia — obraz kliniczny", "q": "Jaka jest najbardziej prawdopodobna przyczyna nagłej duszności z bólem zamostkowym?",
     "mode": "typed", "answers": ["zatorowość płucna"]},
    {"category": "Choroby układu krążenia — obraz kliniczny", "q": "Kiedy mogą wystąpić kołatanie serca i tachykardia?",
     "mode": "typed", "answers": ["w nadczynności tarczycy i w hipoglikemii (a także w guzie chromochłonnym nadnerczy)"]},
    {"category": "Choroby układu krążenia — obraz kliniczny", "q": "Pierwotna nadczynność tarczycy — jakie wyniki hormonalne?",
     "mode": "typed", "answers": ["obniżone TSH, podwyższone FT4"]},
    {"category": "Choroby układu krążenia — obraz kliniczny", "q": "Pacjentka: duszność, młody wiek, palenie tytoniu, podwyższone NT-proBNP, zespół S1Q3T3 w EKG. Co podejrzewasz?",
     "mode": "typed", "answers": ["zatorowość płucną"]},
    {"category": "Choroby układu krążenia — obraz kliniczny", "q": "Pacjent z dusznością, podwyższoną troponiną i NT-proBNP, prawogramem w EKG i blokiem RBBB — jakie badanie krwi wykonasz w pierwszej kolejności?",
     "mode": "typed", "answers": ["D-dimery (i morfologię) — podejrzenie zatorowości płucnej"]},
    {"category": "Choroby układu krążenia — obraz kliniczny", "q": "Jaka jest docelowa wartość LDL-C u pacjenta po udarze niedokrwiennym mózgu?",
     "mode": "typed", "answers": ["poniżej 55 mg/dl"]},

    # --- Choroby układu oddechowego — obraz kliniczny ---
    {"category": "Choroby układu oddechowego — obraz kliniczny", "q": "Mężczyzna leczony amoksycyliną z powodu zapalenia płuc nagle się pogarsza, wysoka gorączka i CRP. Co podejrzewasz?",
     "mode": "typed", "answers": ["zakażenie Clostridioides difficile (rzekomobłoniaste zapalenie jelit po antybiotykoterapii)"]},
    {"category": "Choroby układu oddechowego — obraz kliniczny", "q": "Kiedy może wystąpić wysoka prokalcytonina?",
     "mode": "typed", "answers": ["w ciężkich infekcjach bakteryjnych i sepsie (a także w niektórych nowotworach neuroendokrynnych, np. raku rdzeniastym tarczycy i raku drobnokomórkowym płuca)"]},

    # --- Choroby przewodu pokarmowego i wątroby — obraz kliniczny ---
    {"category": "Choroby przewodu pokarmowego i wątroby", "q": "Pacjent 76 lat: obniżone MCV i hemoglobina, utrata masy ciała, zaparcia. Co podejrzewasz?",
     "mode": "typed", "answers": ["raka jelita grubego"]},
    {"category": "Choroby przewodu pokarmowego i wątroby", "q": "Świeża krew w stolcu najczęściej wskazuje na:",
     "mode": "typed", "answers": ["nowotwór jelita grubego (lub inne źródło krwawienia z dolnego odcinka przewodu pokarmowego)"]},
    {"category": "Choroby przewodu pokarmowego i wątroby", "q": "Czego NIE oczekujemy przy wrzodach żołądka (w odróżnieniu od wrzodu dwunastnicy)?",
     "mode": "typed", "answers": ["szybkiego uczucia sytości nie jest typową cechą — częściej ból nasila się po jedzeniu, a nie ustępuje"]},
    {"category": "Choroby przewodu pokarmowego i wątroby", "q": "U pacjenta z żółtą skórą, co zmierzysz w pierwszej kolejności?",
     "mode": "typed", "answers": ["bilirubinę w surowicy"]},
    {"category": "Choroby przewodu pokarmowego i wątroby", "q": "Żółtaczka wątrobowokomórkowa — jaki obraz moczu, kału i bilirubiny?",
     "mode": "typed", "answers": ["mocz ciemny, bilirubina w moczu dodatnia, kał o prawidłowym zabarwieniu"]},
    {"category": "Choroby przewodu pokarmowego i wątroby", "q": "Wzrost bilirubiny pośredniej i zażółcenie skóry — możliwe przyczyny?",
     "mode": "typed", "answers": ["niedokrwistość hemolityczna (bilirubina pośrednia rośnie przy nasilonej hemolizie)"]},
    {"category": "Choroby przewodu pokarmowego i wątroby", "q": "Kiedy może wystąpić żółtaczka mechaniczna (zastoinowa)?",
     "mode": "typed", "answers": ["przy raku głowy trzustki i kamicy dróg żółciowych (utrudniony odpływ żółci)"]},

    # --- Choroby nerek i układu moczowego — obraz kliniczny ---
    {"category": "Choroby nerek i układu moczowego", "q": "Co przemawia za przewlekłą chorobą nerek (w morfologii krwi)?",
     "mode": "typed", "answers": ["niedokrwistość normocytowa normobarwliwa"]},
    {"category": "Choroby nerek i układu moczowego", "q": "Jakie są objawy obrzęków pochodzenia nerkowego?",
     "mode": "typed", "answers": ["obrzęki nóg, pienisty mocz (białkomocz), nadciśnienie tętnicze, żółtaki powiek"]},
    {"category": "Choroby nerek i układu moczowego", "q": "Ból w okolicy L5 kręgosłupa, niewydolność nerek i hiperkalcemia — co podejrzewasz?",
     "mode": "typed", "answers": ["szpiczaka mnogiego"]},

    # --- Hematologia kliniczna ---
    {"category": "Hematologia kliniczna", "q": "Co świadczy o niedoborze czynników krzepnięcia?",
     "mode": "typed", "answers": ["podwyższone APTT"]},
    {"category": "Hematologia kliniczna", "q": "Jakie są cechy niedokrwistości w przebiegu chorób przewlekłych?",
     "mode": "typed", "answers": ["niedokrwistość normocytarna, normobarwliwa; obniżone stężenie żelaza we krwi (przy prawidłowym lub obniżonym TIBC)"]},
    {"category": "Hematologia kliniczna", "q": "Jakie zmiany w morfologii występują przy niedoborze żelaza?",
     "mode": "typed", "answers": ["podwyższone TIBC (całkowita zdolność wiązania żelaza) i obniżona ferrytyna"]},
    {"category": "Hematologia kliniczna", "q": "Przy niedoborze jakich witamin/pierwiastków wystąpi obniżenie MCH, MCV, MCHC?",
     "mode": "typed", "answers": ["niedobór żelaza (niedokrwistość mikrocytarna, niedobarwliwa)"]},
    {"category": "Hematologia kliniczna", "q": "Pacjentka: Hb=18 g/dl, Hct=52%, bolesny rumień dłoniowy po kąpieli. Co podejrzewasz?",
     "mode": "typed", "answers": ["czerwienicę prawdziwą (erytromelalgia po ciepłej kąpieli jest charakterystyczna)"]},
    {"category": "Hematologia kliniczna", "q": "Gorączka i nocne pocenie się razem z powiększeniem węzłów chłonnych sugerują:",
     "mode": "typed", "answers": ["chłoniaka"]},
    {"category": "Hematologia kliniczna", "q": "Pacjent z powiększonymi, niebolesnymi, nieprzesuwalnymi węzłami chłonnymi i wodobrzuszem — co podejrzewasz?",
     "mode": "typed", "answers": ["nowotwór (np. chłoniaka lub przerzuty)"]},

    # --- Gorączka i objawy ogólnoustrojowe ---
    {"category": "Gorączka i objawy ogólnoustrojowe", "q": "Jakie mogą być przyczyny gorączki nawracającej (pojawiającej się i znikającej cyklicznie)?",
     "mode": "typed", "answers": ["zapalenie płuc, zakażenie HIV, chłoniak, infekcyjne zapalenie wsierdzia, nowotwory (np. rak nerki, rak płuca, rak jelita grubego)"]},
    {"category": "Gorączka i objawy ogólnoustrojowe", "q": "Kiedy możemy rozpoznać cukrzycę na podstawie glikemii na czczo?",
     "mode": "typed", "answers": ["gdy dwukrotnie na czczo stężenie glukozy wynosi ≥126 mg/dl (podawane w giełdzie jako ok. 130 mg/dl)"]},
]

with open('propedeutyka_cw_raw.json', 'w', encoding='utf-8') as f:
    json.dump(ITEMS, f, ensure_ascii=False, indent=2)

by_cat = {}
for it in ITEMS:
    by_cat[it['category']] = by_cat.get(it['category'], 0) + 1
for c, n in sorted(by_cat.items()):
    print(n, '-', c)
print('TOTAL', len(ITEMS))
