# -*- coding: utf-8 -*-
# Propedeutyka pediatrii (Rok 3) - nowy przedmiot od zera.
# Źródło: GIEŁDY TEGOROCZNE - EGZAMIN PEDIATRIA 30.01.2026 (zima) i 12.06.2026
# (lato), oba bardzo bogate w treść, dobra jakość recall.
import json

ITEMS = [
    # --- Badanie noworodka i okres noworodkowy ---
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Jaka jest charakterystyczna cecha ułożenia ciała zdrowego noworodka?",
     "mode": "typed", "answers": ["ułożenie zgięciowe, przypominające literę C"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Kiedy fizjologicznie odpada kikut pępowinowy?",
     "mode": "typed", "answers": ["ok. 18. dnia życia"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Kiedy występuje fizjologiczny ubytek masy ciała noworodka?",
     "mode": "typed", "answers": ["w pierwszych dniach po urodzeniu"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Jakim przyrządem mierzymy długość ciała noworodka?",
     "mode": "typed", "answers": ["liberometrem"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Jaka skala służy do oceny dojrzałości narządowej i neurologicznej noworodków urodzonych przedwcześnie?",
     "mode": "typed", "answers": ["skala Ballard"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Jakie oceniamy czynności życiowe w skali Apgar?",
     "mode": "typed", "answers": ["zabarwienie skóry, częstość akcji serca, oddychanie, reakcję na cewnik (odruchy), napięcie mięśniowe"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Kiedy zachodzi PIERWSZE skrzyżowanie immunologiczne (przewaga limfocytów nad neutrofilami)?",
     "mode": "typed", "answers": ["ok. 2. tygodnia życia"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Kiedy zachodzi DRUGIE skrzyżowanie immunologiczne (powrót przewagi neutrofili)?",
     "mode": "typed", "answers": ["ok. 4.-6. roku życia"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Jaki obraz morfologii (neutrofile pałeczkowate ~7%, neutrofile podzielone ~55%, mniej limfocytów, leukocytoza) jest typowy dla którego okresu?",
     "mode": "typed", "answers": ["dla noworodka w pierwszych dniach życia (fizjologiczna przewaga neutrofili przed pierwszym skrzyżowaniem)"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Co dzieje się fizjologicznie w 3.-6. miesiącu życia dotyczące morfologii krwi?",
     "mode": "typed", "answers": ["fizjologiczna niedokrwistość niedobarwliwa (spadek Hb, tzw. niedokrwistość fizjologiczna niemowląt)"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Kiedy wykształca się (dojrzewa) odruch ssania u płodu?",
     "mode": "typed", "answers": ["ok. 32. tygodnia ciąży (hbd)"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Ile procent stanowi białko w mleku matki?",
     "mode": "typed", "answers": ["ok. 1%"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Czym różni się mleko kobiece od krowiego?",
     "mode": "typed", "answers": ["mleko kobiece ma korzystniejszy stosunek białek serwatkowych do kazeiny"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Kiedy może wystąpić hipernatremia u niemowlęcia karmionego nieprawidłowo?",
     "mode": "typed", "answers": ["przy karmieniu wyłącznie mlekiem krowim i dużą ilością słonych pokarmów"]},
    {"category": "Badanie noworodka i okres noworodkowy", "q": "Kiedy powinniśmy zbadać dno oka u wcześniaka?",
     "mode": "typed", "answers": ["ok. 4. tygodnia życia (badanie w kierunku retinopatii wcześniaków)"]},

    # --- Szczepienia ochronne ---
    {"category": "Szczepienia ochronne", "q": "Jakie szczepienia podaje się w pierwszej dobie życia noworodka?",
     "mode": "typed", "answers": ["BCG (przeciw gruźlicy) i szczepionka przeciw WZW typu B"]},
    {"category": "Szczepienia ochronne", "q": "W jaki sposób podaje się szczepionkę BCG (przeciwgruźliczą)?",
     "mode": "typed", "answers": ["śródskórnie"]},
    {"category": "Szczepienia ochronne", "q": "Kiedy podajemy pierwszą dawkę szczepionki MMR (odra-świnka-różyczka)?",
     "mode": "typed", "answers": ["ok. 13.-15. miesiąca życia"]},
    {"category": "Szczepienia ochronne", "q": "Ile dawek obejmuje szczepienie przeciw HPV (wirusowi brodawczaka ludzkiego) w wieku 9-14 lat?",
     "mode": "typed", "answers": ["2 dawki"]},
    {"category": "Szczepienia ochronne", "q": "Wcześniak urodzony w 28. tygodniu ciąży — jak go szczepimy?",
     "mode": "typed", "answers": ["zgodnie z wiekiem metrykalnym (kalendarzowym), nie skorygowanym"]},
    {"category": "Szczepienia ochronne", "q": "Która ze szczepionek jest zalecana (nieobowiązkowa) w polskim kalendarzu szczepień?",
     "mode": "typed", "answers": ["szczepionka przeciw ospie wietrznej"]},

    # --- Żywienie niemowląt i dzieci ---
    {"category": "Żywienie niemowląt i dzieci", "q": "Jak długo wg WHO zaleca się karmienie piersią?",
     "mode": "typed", "answers": ["tak długo, jak chce tego matka i jak długo służy to dziecku (WHO zaleca co najmniej do 2. roku życia)"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jakie jest bezwzględne przeciwwskazanie do karmienia naturalnego ze strony dziecka?",
     "mode": "typed", "answers": ["galaktozemia"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jakie jest bezwzględne przeciwwskazanie do karmienia piersią ze strony matki (choroba zakaźna)?",
     "mode": "typed", "answers": ["czynna gruźlica"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jaką mieszankę podajemy niemowlęciu z alergią na białko mleka krowiego (przy chęci przejścia z diety eliminacyjnej matki na mieszankę modyfikowaną)?",
     "mode": "typed", "answers": ["hydrolizat (mieszankę hydrolizowaną) z kazeiną"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jaką mieszankę podajemy dziecku z niewydolnością trzustki (np. w mukowiscydozie)?",
     "mode": "typed", "answers": ["mieszankę z tłuszczami MCT (trójglicerydy średniołańcuchowe)"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jaką mieszankę podajemy niemowlęciu z refluksem żołądkowo-przełykowym?",
     "mode": "typed", "answers": ["mieszankę typu AR (antyrefluksową, zagęszczaną)"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Co to jest BLW (Baby-Led Weaning)?",
     "mode": "typed", "answers": ["metoda rozszerzania diety, w której dziecko samodzielnie je rączkami różne pokarmy o różnej konsystencji, bez karmienia łyżeczką papkami"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Od kiedy można podawać dziecku soki (soczki)?",
     "mode": "typed", "answers": ["po 12. miesiącu życia"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Czego NIE należy podawać niemowlęciu?",
     "mode": "typed", "answers": ["miodu (ryzyko botulizmu dziecięcego), a we wczesnym okresie także np. surowego jogurtu czy szpinaku w nadmiarze"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jaka jest zalecana dawka witaminy D dla dziecka w wieku 6-12 miesięcy?",
     "mode": "typed", "answers": ["ok. 400-600 IU/dobę (w zależności od ekspozycji na słońce i diety)"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jaka jest zalecana dawka witaminy D dla dzieci w wieku 1-10 lat?",
     "mode": "typed", "answers": ["ok. 600-1000 IU/dobę"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jaka jest zalecana dawka witaminy D3 dla wcześniaka urodzonego przed 32. tygodniem ciąży?",
     "mode": "typed", "answers": ["ok. 800 IU/dobę"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Ile i jaką drogą podajemy witaminę K noworodkowi po porodzie?",
     "mode": "typed", "answers": ["1 mg domięśniowo (i.m.)"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Kiedy możemy przerwać suplementację żelaza u niemowlęcia?",
     "mode": "typed", "answers": ["6-8 tygodni po uzyskaniu prawidłowych wyników morfologii"]},
    {"category": "Żywienie niemowląt i dzieci", "q": "Jaka jest najczęstsza alergia pokarmowa u dzieci?",
     "mode": "typed", "answers": ["alergia na białko mleka krowiego"]},

    # --- Rozwój fizyczny i psychomotoryczny ---
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Kiedy pojawia się doskonały chwyt pęsetowy?",
     "mode": "typed", "answers": ["ok. 10.-12. miesiąca życia"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Kiedy wykształca się chwyt łokciowo-dłoniowy?",
     "mode": "typed", "answers": ["ok. 4.-5. miesiąca życia"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Do kiedy dziecko powinno osiągnąć umiejętność samodzielnego chodzenia (kamień milowy)?",
     "mode": "typed", "answers": ["do ok. 18. miesiąca życia"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Jaki okres życia charakteryzuje się największym tempem wzrastania dziecka?",
     "mode": "typed", "answers": ["okres płodowy"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Wskaż prawdziwe zdanie o głużeniu.",
     "mode": "typed", "answers": ["pojawia się w 2.-3. miesiącu życia, jest czynnością nieświadomą (poprzedza gaworzenie)"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Wskaż prawdziwe zdanie o gruchaniu.",
     "mode": "typed", "answers": ["gruchanie jest aktem nieświadomym (wczesna forma wokalizacji niemowlęcej)"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Co charakteryzuje zabawę typowego 2-latka?",
     "mode": "typed", "answers": ["zabawa równoległa — bawi się obok innych dzieci, ale nie wspólnie z nimi"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "18-miesięczne dziecko ma problem z osiąganiem kamieni milowych rozwoju. Jaki zakres opóźnienia możemy przyjąć jako niepokojący dla tego wieku?",
     "mode": "typed", "answers": ["ok. 3 miesiące"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "6-miesięczne dziecko nie osiągnęło kamieni milowych rozwoju. O ile miesięcy jest opóźnione, jeśli przyjmiemy niepokojący próg dla tego wieku?",
     "mode": "typed", "answers": ["ok. 1 miesiąc"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Co powinno zaniepokoić pediatrę w rozwoju płciowym 15-letniej dziewczyny?",
     "mode": "typed", "answers": ["brak jakichkolwiek cech rozpoczęcia dojrzewania płciowego"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Jakiego przyrządu używa pediatra przy ocenie dojrzewania płciowego chłopców w skali Tannera?",
     "mode": "typed", "answers": ["orchidometru (do oceny objętości jąder)"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Co charakteryzuje okres niemowlęcy pod względem wzrastania?",
     "mode": "typed", "answers": ["bardzo szybkie tempo wzrastania — masa ciała rośnie nawet o kilkaset % w pierwszym roku, przyrost długości ciała ok. 25 cm w pierwszym roku"]},
    {"category": "Rozwój fizyczny i psychomotoryczny", "q": "Czym różni się BMI u dzieci od BMI u dorosłych w interpretacji?",
     "mode": "typed", "answers": ["u dzieci BMI interpretuje się w odniesieniu do siatek centylowych dla wieku i płci, a nie jako wartość bezwzględną"]},

    # --- Badanie przedmiotowe pediatryczne — układ krążenia i oddechowy ---
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Gdzie u dzieci lokalizuje się uderzenie koniuszkowe serca w zależności od wieku?",
     "mode": "typed", "answers": ["im młodsze dziecko, tym bardziej ku górze i bocznie (na lewo) w stosunku do pozycji u dorosłych"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Gdzie osłuchujemy zastawkę trójdzielną?",
     "mode": "typed", "answers": ["przy przyczepie V-VI żebra z prawej strony mostka (dolna część mostka)"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Co świadczy o szmerze maszynowym w osłuchiwaniu serca u dziecka?",
     "mode": "typed", "answers": ["przetrwały przewód tętniczy (PDA)"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Dziecko ze szmerem skurczowo-rozkurczowym (ciągłym) w II przestrzeni międzyżebrowej lewej — jaka wada?",
     "mode": "typed", "answers": ["przetrwały przewód tętniczy (PDA)"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Co dzieje się fizjologicznie w układzie krążenia bezpośrednio po urodzeniu?",
     "mode": "typed", "answers": ["zamyka się otwór owalny — ustaje przepływ krwi z prawego do lewego przedsionka"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Gdzie i kiedy słyszalny jest łagodny (niewinny) szmer buczenia żylnego u dzieci?",
     "mode": "typed", "answers": ["nad i pod prawym obojczykiem"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Jaki jest klasyczny opis szmeru niewinnego Stilla?",
     "mode": "typed", "answers": ["muzyczny, wibrujący szmer skurczowy, najlepiej słyszalny w dolnej części mostka/koniuszku, znika w pozycji stojącej"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "7-letnie dziecko: zaburzenia oddychania, osłabione drżenie piersiowe, gorączka, stłumiony odgłos opukowy. Co podejrzewasz?",
     "mode": "typed", "answers": ["zapalenie płuc z towarzyszącym płynem w jamie opłucnej"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Jaki jest odgłos opukiwania nad fizjologicznie powietrznym płucem u dziecka?",
     "mode": "typed", "answers": ["odgłos jawny (bębenkowy)"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Kiedy stwierdzimy stłumiony odgłos opukowy nad płucami u dziecka?",
     "mode": "typed", "answers": ["przy płynie w jamie opłucnej, niedodmie, zrostach opłucnowych (nie przy astmie ani rozedmie — tam odgłos jest jawniejszy)"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Kiedy podniesie się dolna granica płuca u dziecka?",
     "mode": "typed", "answers": ["przy powiększeniu narządów jamy brzusznej (np. hepatosplenomegalii, wodobrzuszu)"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Czym jest stridor?",
     "mode": "typed", "answers": ["głośny, niski dźwięk (świst) podczas wdechu, świadczący o zwężeniu górnych dróg oddechowych"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Jakie badanie jest najbardziej przydatne w pierwszej kolejności u dziecka z przewlekłym kaszlem?",
     "mode": "typed", "answers": ["dokładny wywiad i badanie przedmiotowe"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Gorączkujące dziecko z kaszlem przypominającym \"pianie koguta\" — jaką chorobę podejrzewasz?",
     "mode": "typed", "answers": ["krztusiec"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Dziewczynka: krótkie, przerywane szmery na szczycie wdechu u podstawy płuca, znikające po kilku głębokich oddechach. Co to za zjawisko osłuchowe?",
     "mode": "typed", "answers": ["trzeszczenia (rzekome, znikające po głębokich oddechach — nieistotne klinicznie)"]},
    {"category": "Badanie przedmiotowe — krążenie i oddychanie", "q": "Jaki jest mechanizm powstawania sinicy OBWODOWEJ?",
     "mode": "typed", "answers": ["zwiększony pobór (zużycie) tlenu przez tkanki obwodowe na skutek wychłodzenia dystalnych części ciała"]},

    # --- Odruchy noworodkowe i badanie neurologiczne ---
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Co wywołuje odruch Moro?",
     "mode": "typed", "answers": ["nagły bodziec (np. hałas, głośny dźwięk) lub nagła zmiana pozycji głowy"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Kiedy zanika fizjologicznie odruch Moro?",
     "mode": "typed", "answers": ["ok. 4.-6. miesiąca życia"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Kiedy zanika odruch chwytny (dłoniowy)?",
     "mode": "typed", "answers": ["ok. 4. miesiąca życia"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Na czym polega test (chwyt) Barlowa w badaniu stawu biodrowego niemowlęcia?",
     "mode": "typed", "answers": ["prowokacyjne wywichnięcie (wysunięcie) głowy kości udowej z panewki stawu biodrowego"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Co oznacza dodatni objaw Ortolaniego?",
     "mode": "typed", "answers": ["przemieszczenie (repozycję) głowy kości udowej z powrotem do panewki, słyszalne jako charakterystyczny trzask"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Na czym polega objaw Brudzińskiego wywoływany uciskiem na spojenie łonowe?",
     "mode": "typed", "answers": ["silny ucisk na spojenie łonowe skutkuje zgięciem kończyn dolnych w kolanach i ich odwiedzeniem w biodrach"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "6-letnie dziecko z gorączką od 2 dni, światłowstrętem, bólem głowy, trudnością przygięcia brody do mostka i niemożnością wyprostowania nogi uprzednio zgiętej w biodrze i kolanie. Jakie objawy oponowe stwierdzono?",
     "mode": "typed", "answers": ["objaw Kerniga dolny oraz sztywność karku (objaw Brudzińskiego karkowy)"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Jak wygląda prawidłowy płyn mózgowo-rdzeniowy (PMR)?",
     "mode": "typed", "answers": ["klarowny, wodojasny"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Ile maksymalnie punktów można uzyskać w skali Glasgow (GCS)?",
     "mode": "typed", "answers": ["15 punktów"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Dlaczego u dziecka ocenionego przez zespół ratownictwa na 7 punktów w skali Glasgow, w szpitalu przyznano 13 punktów?",
     "mode": "typed", "answers": ["ponieważ nie oceniono dziecka odpowiednią (pediatryczną) skalą Glasgow dla dzieci, tylko skalą dla dorosłych"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Jaki jest zakres punktacji poszczególnych komponent skali Glasgow?",
     "mode": "typed", "answers": ["4 punkty za reakcję otwierania oczu, 5 punktów za reakcję słowną, 6 punktów za reakcję ruchową"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Krótkotrwała utrata przytomności to najczęściej:",
     "mode": "typed", "answers": ["omdlenie (a nie drgawki, apatia czy śpiączka)"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Co to jest stupor?",
     "mode": "typed", "answers": ["stan przedśpiączkowy — reakcja pacjenta zachodzi tylko na silne bodźce (np. bólowe)"]},
    {"category": "Odruchy noworodkowe i badanie neurologiczne", "q": "Jakiej wadzie neurologicznej towarzyszy chód spastyczny (nożycowy)?",
     "mode": "typed", "answers": ["mózgowemu porażeniu dziecięcemu / uszkodzeniu górnego neuronu ruchowego"]},

    # --- Skale oceny stanu dziecka ---
    {"category": "Skale oceny stanu dziecka", "q": "Co oceniamy w skali Apgar (5 elementów)?",
     "mode": "typed", "answers": ["zabarwienie skóry, częstość akcji serca, oddychanie, odruchy (reakcję na cewnik), napięcie mięśniowe"]},
    {"category": "Skale oceny stanu dziecka", "q": "Jaka jest maksymalna liczba punktów w skali Tannera dla owłosienia łonowego/piersi (etapy)?",
     "mode": "typed", "answers": ["skala 5-stopniowa (etapy P1-P5 / B1-B5)"]},
    {"category": "Skale oceny stanu dziecka", "q": "Dziewczynka 10 lat: delikatnie wykształcone piersi i delikatne owłosienie łonowe. Jaki to stopień w skali Tannera?",
     "mode": "typed", "answers": ["stopień 2"]},
    {"category": "Skale oceny stanu dziecka", "q": "Jaka skala ocenia dojrzałość narządową i neurologiczną wcześniaków?",
     "mode": "typed", "answers": ["skala Ballard"]},
    {"category": "Skale oceny stanu dziecka", "q": "Jak nazywa się badanie oceniające zeza za pomocą naprzemiennego zasłaniania oczu?",
     "mode": "typed", "answers": ["cover-test"]},
    {"category": "Skale oceny stanu dziecka", "q": "Na czym polega test Hirschberga?",
     "mode": "typed", "answers": ["ocena zeza na podstawie położenia odbicia światła latarki na rogówce obu oczu"]},
    {"category": "Skale oceny stanu dziecka", "q": "Jak prawidłowo wykonuje się badanie nawrotu kapilarnego (CRT)?",
     "mode": "typed", "answers": ["uciska się skórę z umiarkowaną siłą przez ok. 5 sekund; wynik ≥3 sekundy jest nieprawidłowy (patologiczny)"]},

    # --- Choroby wieku dziecięcego — obraz kliniczny ---
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Plamki Koplika są charakterystyczne dla jakiej choroby?",
     "mode": "typed", "answers": ["odry"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "\"Mysi\" zapach dziecka jest charakterystyczny dla jakiej choroby metabolicznej?",
     "mode": "typed", "answers": ["fenyloketonurii"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Plamy typu café-au-lait są charakterystyczne dla jakiej choroby?",
     "mode": "typed", "answers": ["nerwiakowłókniakowatości typu 1 (choroba von Recklinghausena)"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Objaw \"oliwki\" w badaniu palpacyjnym brzucha niemowlęcia wskazuje na jaką chorobę?",
     "mode": "typed", "answers": ["przerostowe zwężenie odźwiernika"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Jakie czynniki wchodzą w skład zakażeń TORCH?",
     "mode": "typed", "answers": ["toksoplazmoza, różyczka (rubella), cytomegalowirus (CMV), a także opryszczka (HSV) i inne"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Chłopiec z żółtaczką i podwyższonymi enzymami wątrobowymi (GGTP) — co najbardziej prawdopodobne?",
     "mode": "typed", "answers": ["zapalenie dróg żółciowych (cholangitis) — możliwe też wirusowe zapalenie wątroby"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Triada Charcota (ból w nadbrzuszu, żółtaczka, gorączka) wskazuje na:",
     "mode": "typed", "answers": ["ostre zapalenie dróg żółciowych"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Chłopiec z obustronnie dodatnim objawem Goldflama i zaczerwienieniem ujścia cewki moczowej — co podejrzewasz?",
     "mode": "typed", "answers": ["ostre odmiedniczkowe zapalenie nerek (możliwe też zapalenie pęcherza moczowego)"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "17-letni chłopiec: ból brzucha promieniujący do prawej pachwiny, wymioty, zatrzymanie stolca, gazów i moczu. Jakie diagnozy różnicowe?",
     "mode": "typed", "answers": ["kamica moczowodowa, zapalenie wyrostka robaczkowego, uwięźnięta przepuklina"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Dziecko z problemem oddawania stolca, guzek 3 cm od odbytu — jakie jest pierwsze postępowanie?",
     "mode": "typed", "answers": ["badanie per rectum"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Charakterystyczne cechy bólów wzrostowych u dzieci to:",
     "mode": "typed", "answers": ["prawidłowe wyniki badań, występowanie rano i wieczorem, symetrycznie w udach, dołach podkolanowych i przedramionach"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Dziewczynka niska, z płetwiastą szyją (karkiem), koarktacją aorty i niedorozwojem cech płciowych — jaki kariotyp podejrzewasz?",
     "mode": "typed", "answers": ["45,X (zespół Turnera)"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Jakie są typy osteogenesis imperfecta (OI) pod względem ciężkości?",
     "mode": "typed", "answers": ["typ II jest letalny, typ IV jest zwykle najcięższy z form przeżywalnych"]},
    {"category": "Choroby wieku dziecięcego — obraz kliniczny", "q": "Dziecko po ostrej białaczce z licznymi złamaniami kości (w tym w wywiadzie rodzinnym) — co należy do postępowania diagnostycznego?",
     "mode": "typed", "answers": ["wykonanie badania densytometrycznego (ocena gęstości kości, podejrzenie osteoporozy wtórnej)"]},

    # --- Zaburzenia wzrastania i układu kostnego ---
    {"category": "Zaburzenia wzrastania i układu kostnego", "q": "Czym jest koślawość kolan (genu valgum)?",
     "mode": "typed", "answers": ["kolana układają się w kształt litery X"]},
    {"category": "Zaburzenia wzrastania i układu kostnego", "q": "Jaki szew czaszki zarasta przedwcześnie w czaszce trójkątnej (trigonocefalii)?",
     "mode": "typed", "answers": ["szew czołowy"]},
    {"category": "Zaburzenia wzrastania i układu kostnego", "q": "Kiedy fizjologicznie zarasta ciemiączko przednie?",
     "mode": "typed", "answers": ["ok. 9.-18. miesiąca życia"]},
    {"category": "Zaburzenia wzrastania i układu kostnego", "q": "O czym świadczy zapadnięte ciemiączko u niemowlęcia?",
     "mode": "typed", "answers": ["o odwodnieniu"]},
    {"category": "Zaburzenia wzrastania i układu kostnego", "q": "Jakim powikłaniem niedoboru witaminy D jest rozmiękanie kości potylicznej (craniotabes) u niemowląt?",
     "mode": "typed", "answers": ["krzywicy"]},
    {"category": "Zaburzenia wzrastania i układu kostnego", "q": "W którym okresie życia dzieci najłatwiej ulegają złamaniom kości?",
     "mode": "typed", "answers": ["ok. 11.-14. roku życia (okres skoku pokwitaniowego)"]},

    # --- Badania przesiewowe noworodków ---
    {"category": "Badania przesiewowe noworodków", "q": "Jakie choroby wykrywa się testem z suchej kropli krwi (bibułowym) u noworodków?",
     "mode": "typed", "answers": ["m.in. fenyloketonurię, mukowiscydozę, wrodzoną niedoczynność tarczycy, rdzeniowy zanik mięśni (SMA) — NIE achondroplazję (choroba niewykrywalna tym testem)"]},
    {"category": "Badania przesiewowe noworodków", "q": "Wrodzona niedoczynność tarczycy wykryta w teście bibułkowym wiąże się najczęściej z jaką przyczyną?",
     "mode": "typed", "answers": ["agenezją (brakiem/niedorozwojem) tarczycy"]},
]

with open('propedeutyka_ped_raw.json', 'w', encoding='utf-8') as f:
    json.dump(ITEMS, f, ensure_ascii=False, indent=2)

by_cat = {}
for it in ITEMS:
    by_cat[it['category']] = by_cat.get(it['category'], 0) + 1
for c, n in sorted(by_cat.items()):
    print(n, '-', c)
print('TOTAL', len(ITEMS))
