# -*- coding: utf-8 -*-
# Radiologia (Rok 3) - nowy przedmiot od zera.
# Źródła: własny folder "Radiologia-giełda-z-zaliczeń-semestralnych" (144 pozycje,
# bardzo bogate, pytania czysto tekstowe + wiele pytań obrazkowych "RTG/TK – X"
# BEZ załączonych obrazów - te pominięto) + GIEŁDY TEGOROCZNE/Radiologia (4 egzaminy,
# w większości powtarzają tę samą pulę pytań tekstowych - potwierdzają odpowiedzi).
# NIE wykorzystano: "5 rok - TESTER Radiologia" (849 pytań, ale to interaktywny quiz
# CAŁKOWICIE obrazkowy - każde pytanie wymaga 1-2 obrazów RTG/TK/MRI do interpretacji,
# tekst PDF nie zawiera treści obrazów, tylko chrome UI - wymaga osobnej rundy z
# renderowaniem stron PDF do obrazów i wizualnym przeglądem, zbyt czasochłonne teraz).
import json

ITEMS = [
    # --- Fizyka obrazowania: RTG, dawki, efekty biologiczne ---
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Promieniowanie elektromagnetyczne to strumień jakich cząstek?",
     "mode": "typed", "answers": ["fotonów"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "W lampie RTG obraz uzyskiwany jest w wyniku uderzenia czego w anodę?",
     "mode": "typed", "answers": ["elektronów"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Czy zwiększenie natężenia promieniowania w aparacie RTG zwiększy rozdzielczość obrazu?",
     "mode": "typed", "answers": ["nie — zwiększenie natężenia promieniowania nie wpływa na rozdzielczość"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Jaka jest funkcja kratki przeciwrozproszeniowej w lampie rentgenowskiej?",
     "mode": "typed", "answers": ["zapobiega zamazywaniu obrazu przez promieniowanie rozproszone, poprawiając rozdzielczość przestrzenną"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "RTG, mimo zastosowania matryc cyfrowych, nadal charakteryzuje się stosunkowo dobrą rozdzielczością:",
     "mode": "typed", "answers": ["przestrzenną"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Wskaż zdanie PRAWDZIWE o efektach biologicznych promieniowania:",
     "mode": "typed", "answers": ["efekty deterministyczne są czasami korzystne, a efekty stochastyczne są zawsze niepożądane"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Jaka jest zależność między nasileniem skutków deterministycznych a dawką promieniowania?",
     "mode": "typed", "answers": ["natężenie skutków deterministycznych rośnie wraz z dawką (efekt progowy)"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Z zestawu: białaczka, niepłodność, zmętnienie soczewki, upośledzenie hematopoezy, wypadanie włosów — który skutek jest STOCHASTYCZNY (probabilistyczny)?",
     "mode": "typed", "answers": ["białaczka (pozostałe to skutki deterministyczne, progowe)"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Jaką cechą charakteryzują się skutki stochastyczne promieniowania w odniesieniu do czasu ich ujawnienia się?",
     "mode": "typed", "answers": ["ujawniają się dopiero po wielu latach (długi okres latencji, bez progu dawki)"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Kto jest najbardziej narażony na skutki stochastyczne promieniowania?",
     "mode": "typed", "answers": ["niemowlę/dziecko (rosnące tkanki są najbardziej wrażliwe)"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "Jak można się uchronić przed promieniowaniem gamma radiofarmaceutyku (np. 700 MBq) w strzykawce?",
     "mode": "typed", "answers": ["strzykawka musi być osłonięta ołowiem lub wolframem"]},
    {"category": "Fizyka RTG i ochrona radiologiczna", "q": "W standardowej diagnostyce medycyny nuklearnej jakich skutków biologicznych można się spodziewać?",
     "mode": "typed", "answers": ["wyłącznie stochastycznych (dawki diagnostyczne są zbyt niskie na efekty deterministyczne)"]},

    # --- Fizyka i technika: TK, MRI, USG (rozdzielczości) ---
    {"category": "Fizyka TK, MRI i USG", "q": "Od czego zależy siła odbicia fali dźwiękowej na granicy dwóch ośrodków w USG?",
     "mode": "typed", "answers": ["od różnicy ich impedancji akustycznej"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Która rozdzielczość jest wysoka nawet w niskopolowym rezonansie magnetycznym (MRI)?",
     "mode": "typed", "answers": ["rozdzielczość tkankowa"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Co ma najlepszą rozdzielczość CZASOWĄ spośród metod obrazowania?",
     "mode": "typed", "answers": ["USG i fluoroskopia"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Co ma najlepszą rozdzielczość TKANKOWĄ spośród metod obrazowania?",
     "mode": "typed", "answers": ["rezonans magnetyczny (MRI)"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Co ma najlepszą rozdzielczość PRZESTRZENNĄ spośród metod obrazowania?",
     "mode": "typed", "answers": ["radiografia (RTG) i ultrasonografia"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Którą rozdzielczość poprawia zastosowanie okna diagnostycznego w TK?",
     "mode": "typed", "answers": ["rozdzielczość tkankową"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Którą rozdzielczość poprawia podanie środka kontrastowego?",
     "mode": "typed", "answers": ["rozdzielczość tkankową"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Którą rozdzielczość poprawia tomograf komputerowy dwuźródłowy?",
     "mode": "typed", "answers": ["rozdzielczość czasową"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Jak porusza się pacjent (i układ detektorów) w tomografach komputerowych generacji I-III?",
     "mode": "typed", "answers": ["pacjent przemieszcza się na stole, a układ detektorów porusza się razem z lampą wokół pacjenta"]},
    {"category": "Fizyka TK, MRI i USG", "q": "W skali Hounsfielda (HU) wartość zero oznacza pochłanianie promieniowania przez:",
     "mode": "typed", "answers": ["wodę"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Czy tkanka tłuszczowa ma więcej czy mniej jednostek Hounsfielda (HU) niż woda?",
     "mode": "typed", "answers": ["mniej (wartości ujemne)"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Endoproteza stawu (implant metalowy) charakteryzuje się jaką wartością HU?",
     "mode": "typed", "answers": ["bardzo wysoką, rzędu ok. 3000-3200 HU (metal silnie pochłania promieniowanie)"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Jaki obraz densytometryczny (HU) daje stłuszczenie wątroby w TK?",
     "mode": "typed", "answers": ["niskie, nawet ujemne wartości HU (np. ok. -34 HU) — miąższ jest hipodensyjny"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Co zapewnia przestrzenne zróżnicowanie (kodowanie) pola magnetycznego w MRI?",
     "mode": "typed", "answers": ["cewki gradientowe"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Jakie fale wykorzystywane są do wzbudzania i odbioru sygnału w MRI?",
     "mode": "typed", "answers": ["fale radiowe (dzięki temu badanie jest bezpieczne, bez promieniowania jonizującego)"]},
    {"category": "Fizyka TK, MRI i USG", "q": "W rezonansie magnetycznym znaczenie ma spin jakich cząstek?",
     "mode": "typed", "answers": ["niesparowanych protonów jąder atomowych (np. wodoru)"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Jaką głowicę USG wybierzemy, aby uzyskać większą rozdzielczość (kosztem głębokości penetracji)?",
     "mode": "typed", "answers": ["głowicę o większej częstotliwości"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Jaką głowicę USG wybierzemy, aby zbadać głębiej położone tkanki?",
     "mode": "typed", "answers": ["głowicę o niższej częstotliwości (niższej rozdzielczości, większej penetracji)"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Jaki środek kontrastujący stosuje się do oceny perfuzji w badaniu USG?",
     "mode": "typed", "answers": ["SF6 (sześciofluorek siarki, mikropęcherzyki gazu)"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Czym jest metoda \"pixel shifting\" wykorzystywana do wtórnej poprawy jakości obrazu (jeśli pacjent się poruszy)?",
     "mode": "typed", "answers": ["techniką subtrakcji cyfrowej"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Czym jest fluoroskopia?",
     "mode": "typed", "answers": ["obrazowaniem w czasie rzeczywistym, wykorzystywanym m.in. w badaniach śródoperacyjnych, angiografii i procedurach gastroenterologicznych"]},
    {"category": "Fizyka TK, MRI i USG", "q": "Na czym polega metoda Seldingera?",
     "mode": "typed", "answers": ["bezpieczne uzyskanie dostępu naczyniowego — wprowadzenie do naczynia cewnika o dużej średnicy za pomocą niewielkiej igły i prowadnika"]},

    # --- USG ogólne ---
    {"category": "Ultrasonografia — zasady interpretacji", "q": "W przypadku perforacji (obecność gazu) w badaniu USG — czy gaz będzie bardziej odbijał czy rozpraszał fale ultradźwiękowe?",
     "mode": "typed", "answers": ["będzie bardziej rozpraszał (w mniejszym stopniu odbijał)"]},
    {"category": "Ultrasonografia — zasady interpretacji", "q": "Wskaż zdanie prawdziwe o zwapnieniu w pęcherzyku żółciowym (kamicy) w badaniu USG:",
     "mode": "typed", "answers": ["bardziej odbija fale ultradźwiękowe, a w mniejszym stopniu je rozprasza (daje cień akustyczny)"]},
    {"category": "Ultrasonografia — zasady interpretacji", "q": "Jak wyglądają torbiele wątroby w badaniu USG?",
     "mode": "typed", "answers": ["są hipoechogeniczne (ciemniejsze) w stosunku do prawidłowego miąższu wątroby"]},
    {"category": "Ultrasonografia — zasady interpretacji", "q": "Jak wygląda stłuszczona wątroba w badaniu USG?",
     "mode": "typed", "answers": ["jest hiperechogeniczna (jaśniejsza) w porównaniu do prawidłowego miąższu"]},
    {"category": "Ultrasonografia — zasady interpretacji", "q": "Wskaż zdanie prawdziwe o ultradźwiękach wykorzystywanych w USG:",
     "mode": "typed", "answers": ["są rozpraszane przez powietrze i aby przeniknąć do głębszych tkanek, wymagają wzmocnienia"]},

    # --- Medycyna nuklearna ---
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Podejrzewasz wodonercze u noworodka. Jak potwierdzisz diagnozę przy jak najmniejszym napromieniowaniu dziecka?",
     "mode": "typed", "answers": ["za pomocą scyntygrafii dynamicznej"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Jakie jest zastosowanie scyntygrafii perfuzyjnej mięśnia sercowego?",
     "mode": "typed", "answers": ["wykrywanie przewlekłej choroby niedokrwiennej (wieńcowej) serca"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Jakim badaniem wykryjesz naczyniaka wątroby?",
     "mode": "typed", "answers": ["scyntygrafią metodą puli krwi (znakowanych erytrocytów)"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Jakie są wskazania do scyntygrafii puli krwi wątroby?",
     "mode": "typed", "answers": ["różnicowanie charakteru zmian ogniskowych w wątrobie (np. naczyniak wątroby)"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Jak wygląda diagnostyka nadciśnienia tętniczego przy podejrzeniu zwężenia tętnicy nerkowej?",
     "mode": "typed", "answers": ["scyntygrafia dynamiczna nerek z testem kaptoprilowym"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Jakie są wskazania do scyntygrafii dynamicznej nerek (z testem diuretycznym)?",
     "mode": "typed", "answers": ["wykrywanie uropatii/nefropatii zaporowej oraz diagnostyka nadciśnienia naczyniowo-nerkowego"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Co jest najczęściej wykorzystywanym radionuklidem w terapii medycyny nuklearnej?",
     "mode": "typed", "answers": ["jod-131"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Czy terapię radioizotopową tarczycy jodem-131 można wykonać u kobiet w ciąży?",
     "mode": "typed", "answers": ["nie — ciąża jest bezwzględnym przeciwwskazaniem"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Co może być przykładem teranostyki w medycynie nuklearnej?",
     "mode": "typed", "answers": ["połączenie diagnostyki (mniejsza dawka jodu-131) z terapią (większa dawka jodu-131) tego samego radionuklidu"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "U 75-letniej pacjentki wykryto raka tarczycy. Co należy zrobić, by zakwalifikować ją do leczenia jodem radioaktywnym?",
     "mode": "typed", "answers": ["przeprowadzić scyntygrafię tarczycy, by ocenić wychwyt i dobrać aktywną dawkę jodu"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Gdzie najczęściej w kościach lokalizują się przerzuty raka piersi?",
     "mode": "typed", "answers": ["w szkielecie osiowym, rozmieszczone niesymetrycznie"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Jak uwidaczniają się przerzuty nowotworowe do kości w scyntygrafii kości?",
     "mode": "typed", "answers": ["mocno — silnie wychwytują radiofarmaceutyk (ognisko o zwiększonym gromadzeniu)"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "U pacjenta z POChP wykonano scyntygrafię płuc i wykryto pęcherze rozedmowe pokrywające się z ubytkami wentylacji. Czy można na tej podstawie stwierdzić zatorowość płucną?",
     "mode": "typed", "answers": ["nie — wynik niewystarczający; trzeba wykonać scyntygrafię wentylacyjną, by zwiększyć swoistość badania"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Podczas badania scyntygraficznego kontrast podany do naczynia nie zatrzymał się w części płuca, a kontrast zainhalowany już tak. O czym to świadczy?",
     "mode": "typed", "answers": ["o zatorowości płucnej (ubytek perfuzji przy zachowanej wentylacji)"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "W zapaleniu płuc radiofarmaceutyk kościowy będzie występował w jakim stopniu w części dynamicznej, a w jakim w statycznej fazie badania kości?",
     "mode": "typed", "answers": ["w większym stopniu w fazie dynamicznej, w mniejszym w fazie statycznej"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Jaki związek (radiofarmaceutyk) jest wykorzystywany w badaniu PET?",
     "mode": "typed", "answers": ["fluor-18 (F-18, np. jako FDG)"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Do diagnostyki jakiego układu wykorzystywany jest izotop DaTSCAN?",
     "mode": "typed", "answers": ["układu dopaminergicznego"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Jakie są wskazania do scyntygrafii układu dopaminergicznego?",
     "mode": "typed", "answers": ["choroba Parkinsona — wykrywanie, ocena stopnia zaawansowania i skuteczności leczenia"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Scyntygrafia perfuzyjna serca: w spoczynku gromadzenie prawidłowe, w fazie wysiłkowej 25% ubytek w koniuszku, przegrodzie międzykomorowej i przedniej ścianie lewej komory. Na co wskazuje ten wynik?",
     "mode": "typed", "answers": ["chorobę wieńcową — jest to wskazanie do koronarografii (nie jest to obraz świeżego zawału)"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Co wykorzystuje się do oceny wskaźnika uwapnienia tętnic wieńcowych w badaniu angiograficznym (TK)?",
     "mode": "typed", "answers": ["bramkowanie EKG"]},
    {"category": "Medycyna nuklearna — zastosowania scyntygrafii", "q": "Czego dotyczy skala Agatstona?",
     "mode": "typed", "answers": ["oceny stopnia uwapnienia (zwapnień) tętnic wieńcowych"]},

    # --- Klatka piersiowa i układ oddechowy ---
    {"category": "Radiologia klatki piersiowej", "q": "W którą stronę przesunie się śródpiersie w niedodmie płuca?",
     "mode": "typed", "answers": ["w stronę zajętą chorobowo (chorą)"]},
    {"category": "Radiologia klatki piersiowej", "q": "Jak wpłynie odma prężna na położenie śródpiersia?",
     "mode": "typed", "answers": ["spowoduje przesunięcie śródpiersia na stronę zdrową"]},
    {"category": "Radiologia klatki piersiowej", "q": "Gdzie przesunie się śródpiersie w tamponadzie serca?",
     "mode": "typed", "answers": ["nie przesunie się (poszerzenie sylwetki serca jest symetryczne)"]},
    {"category": "Radiologia klatki piersiowej", "q": "Kiedy zwiększy się stosunek szerokości śródpiersia do szerokości klatki piersiowej na zdjęciu RTG?",
     "mode": "typed", "answers": ["przy niepełnym wdechu"]},
    {"category": "Radiologia klatki piersiowej", "q": "Jakie następstwo (poza litym zacienieniem) towarzyszy niedodmie?",
     "mode": "typed", "answers": ["zmniejszenie objętości niedodmowego odcinka płuca"]},
    {"category": "Radiologia klatki piersiowej", "q": "Wskaż zdanie FAŁSZYWE o zawale płuca w obrazie radiologicznym:",
     "mode": "typed", "answers": ["w zawale płuca nie występują zmiany objętości, ale występuje bronchogram powietrzny (to zdanie jest fałszywe — zawał zwykle NIE daje bronchogramu powietrznego, ognisko jest lite/krwotoczne)"]},
    {"category": "Radiologia klatki piersiowej", "q": "Co jest przyczyną zagęszczenia pęcherzykowatego w obrazie patomorfologicznym płuc?",
     "mode": "typed", "answers": ["zawał płuca lub stłuczenie płuca (zawał daje obraz podobny do zapalenia płatowego)"]},
    {"category": "Radiologia klatki piersiowej", "q": "Co tworzy wnękę płuc w obrazie RTG?",
     "mode": "typed", "answers": ["krążek aorty, tętnice płucne i żyły płucne"]},
    {"category": "Radiologia klatki piersiowej", "q": "Kiedy w obrazie powiększonych węzłów chłonnych pojawi się obraz \"skorupki jajka\" (zwapnienia obwodowe)?",
     "mode": "typed", "answers": ["w sarkoidozie i krzemicy (pylicy krzemowej)"]},
    {"category": "Radiologia klatki piersiowej", "q": "W jakich projekcjach wykonamy zdjęcie RTG klatki piersiowej przy podejrzeniu rozedmy płuc?",
     "mode": "typed", "answers": ["PA (tylno-przednia) i boczna"]},
    {"category": "Radiologia klatki piersiowej", "q": "Jakie kryteria radiologiczne pozwalają rozpoznać rozedmę płuc na zdjęciu RTG?",
     "mode": "typed", "answers": ["zwiększenie przejrzystości pól płucnych oraz poszerzenie przestrzeni Simona powyżej 2 cm"]},
    {"category": "Radiologia klatki piersiowej", "q": "Kiedy serce ułożone jest bardziej horyzontalnie na zdjęciu RTG (przepona wysoko ustawiona)?",
     "mode": "typed", "answers": ["na pełnym wydechu oraz przy niepełnym wdechu"]},
    {"category": "Radiologia klatki piersiowej", "q": "Czym jest \"unaczynione płuco\" w sekwestracji płucnej?",
     "mode": "typed", "answers": ["przetrwałym płodowym krążeniem systemowym zaopatrującym sekwestr"]},

    # --- Przewód pokarmowy — radiologia ---
    {"category": "Radiologia przewodu pokarmowego", "q": "Gdzie najczęściej lokalizują się wrzody w obrębie dwunastnicy?",
     "mode": "typed", "answers": ["w opuszce dwunastnicy"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Gdzie najczęściej (a gdzie najrzadziej) lokalizują się wrzody żołądka?",
     "mode": "typed", "answers": ["najczęściej w okolicy krzywizny mniejszej i odźwiernika; najrzadziej przy krzywiźnie większej i wpuście"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Na co wskazuje objaw \"ogryzka jabłka\" w badaniu obrazowym jelita grubego?",
     "mode": "typed", "answers": ["na raka jelita grubego w postaci pierścieniowatej (zwężającej światło)"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Na co wskazuje objaw \"palca wskazującego\" w badaniu żołądka?",
     "mode": "typed", "answers": ["na chorobę wrzodową żołądka (wciągnięcie krzywizny większej na poziomie wrzodu)"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Na co wskazuje objaw \"dętki rowerowej\" w badaniu jelita grubego?",
     "mode": "typed", "answers": ["na wrzodziejące zapalenie jelita grubego (WZJG) — obraz spowodowany brakiem haustracji"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Jak nazywa się przewlekła zapalna choroba jelit, która ZAWSZE obejmuje odbytnicę?",
     "mode": "typed", "answers": ["wrzodziejące zapalenie jelita grubego (WZJG)"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Gdzie najczęściej lokalizują się uchyłki jelita grubego?",
     "mode": "typed", "answers": ["w ścianie bocznej esicy"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Badanie dwukontrastowe dolnego odcinka przewodu pokarmowego (wlew doodbytniczy) wykonuje się w jakiej pozycji pacjenta?",
     "mode": "typed", "answers": ["na stojąco"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Jak nazywa się metoda podawania mieszaniny barytu i metylocelulozy przez zgłębnik bezpośrednio do jelita cienkiego?",
     "mode": "typed", "answers": ["enterokliza"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Jakie środki kontrastujące stosuje się w standardowej diagnostyce radiologicznej przewodu pokarmowego?",
     "mode": "typed", "answers": ["gastrografina oraz siarczan baru (baryt)"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Co stanowi kontrast negatywny w badaniu dwukontrastowym żołądka i jelita grubego?",
     "mode": "typed", "answers": ["w żołądku — dwutlenek węgla; w jelicie grubym — powietrze"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Podanie kontrastu barytowego jest przeciwwskazane w jakich sytuacjach?",
     "mode": "typed", "answers": ["przy podejrzeniu perforacji przewodu pokarmowego, niedrożności, krwawienia z przewodu pokarmowego oraz przed planowanym zabiegiem chirurgicznym"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Do diagnostyki czego służy przeglądowe zdjęcie RTG jamy brzusznej?",
     "mode": "typed", "answers": ["podejrzenia perforacji przewodu pokarmowego, niedrożności oraz ciała obcego w jamie brzusznej"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Jama zawierająca poziom płynu (poziom płyn-gaz) w badaniu obrazowym to zwykle obraz:",
     "mode": "typed", "answers": ["ropnia"]},
    {"category": "Radiologia przewodu pokarmowego", "q": "Czego zwykle NIE można ocenić w badaniach obrazowych przewodu pokarmowego (w odróżnieniu od endoskopii)?",
     "mode": "typed", "answers": ["bezpośredniego wyglądu (koloru, powierzchni) błony śluzowej, np. wrzodu — badania obrazowe oceniają głównie zarys/czynność"]},

    # --- Układ moczowo-płciowy ---
    {"category": "Radiologia układu moczowego", "q": "Jaki test stosuje się w diagnostyce nadciśnienia tętniczego przy podejrzeniu zwężenia tętnicy nerkowej?",
     "mode": "typed", "answers": ["test (scyntygrafia) z kaptoprilem"]},
]

with open('radiologia_raw.json', 'w', encoding='utf-8') as f:
    json.dump(ITEMS, f, ensure_ascii=False, indent=2)

by_cat = {}
for it in ITEMS:
    by_cat[it['category']] = by_cat.get(it['category'], 0) + 1
for c, n in sorted(by_cat.items()):
    print(n, '-', c)
print('TOTAL', len(ITEMS))
