# -*- coding: utf-8 -*-
# Pytania z GIEŁDY TEGOROCZNE 2025-2026 (Medycyna sądowa) - odtworzone z notatek
# studenckich (recall po egzaminie), na podstawie jasno wskazanych faktów.

ITEMS = [
    {"category": "Tanatologia", "q": "Co NIE wpływa na położenie plam opadowych?",
     "mode": "typed", "answers": ["płeć zmarłego"]},
    {"category": "Tanatologia", "q": "Cechy rany wylotowej (postrzałowej):",
     "mode": "typed", "answers": ["wywinięcie brzegów skóry na zewnątrz"]},
    {"category": "Tanatologia", "q": "Jaki kształt ma linia zaciskowa przy powieszeniu (typowo)?",
     "mode": "typed", "answers": ["kształt litery V (skośna, unosząca się ku górze w miejscu węzła)"]},
    {"category": "Tanatologia", "q": "Podaj definicję stężenia pośmiertnego.",
     "mode": "typed", "answers": ["usztywnienie mięśni po śmierci wskutek wyczerpania ATP w miocytach"]},
    {"category": "Tanatologia", "q": "Które znamiona śmierci są pewne i wczesne?",
     "mode": "typed", "answers": ["plamy opadowe i stężenie pośmiertne"]},
    {"category": "Tanatologia", "q": "Po jakim czasie od śmierci następuje spełzanie naskórka rąk/stóp (\"rękawiczki i skarpetki\") u topielca?",
     "mode": "typed", "answers": ["po kilku tygodniach"]},
    {"category": "Tanatologia", "q": "Warunek niezbędny do zajścia mumifikacji zwłok:",
     "mode": "typed", "answers": ["brak owadów i bakterii (suche, przewiewne środowisko)"]},
    {"category": "Tanatologia", "q": "Złamanie Messerera (przy uderzeniu tępym przedmiotem w kość długą) ma kształt:",
     "mode": "typed", "answers": ["klinowaty, z grotem skierowanym w stronę działania siły"]},
    {"category": "Tanatologia", "q": "Czynnikiem NIE wpływającym na szybkość rozkładu zwłok jest:",
     "mode": "typed", "answers": ["kolor skóry"]},
    {"category": "Tanatologia", "q": "Znaleziono ciało w swobodnej pozycji, lekko zielone, ze schodzącym naskórkiem kończyn, stężenie pośmiertne obecne ale już powoli ustępujące. Jaki to prawdopodobny czas od zgonu?",
     "mode": "typed", "answers": ["2-3 dni"]},
    {"category": "Tanatologia", "q": "Zwłoki wisielca: plamy opadowe znikają po lekkim ucisku i wracają po 30-60 sekundach, ciało chłodne pod ubraniem ale lekko ciepłe pod pachami, stężenie pośmiertne prawie całkowicie rozwinięte. Jaki to prawdopodobny czas od zgonu?",
     "mode": "typed", "answers": ["6-12 godzin"]},

    {"category": "Toksykologia", "q": "Barwa plam opadowych w zatruciu tlenkiem węgla (CO):",
     "mode": "typed", "answers": ["malinowa/jasnoczerwona"]},
    {"category": "Toksykologia", "q": "Gaz o zapachu gorzkich migdałów, używany dawniej do masowych zbrodni, dziś częściej powodujący zatrucia ofiar pożarów:",
     "mode": "typed", "answers": ["cyjanowodór"]},
    {"category": "Toksykologia", "q": "Jaki jest skutek połączenia benzodiazepin z alkoholem?",
     "mode": "typed", "answers": ["depresja ośrodka oddechowego (potęgowanie działania depresyjnego na OUN)"]},
    {"category": "Toksykologia", "q": "Śmiertelne stężenie alkoholu we krwi u osoby okazjonalnie pijącej wynosi w przybliżeniu:",
     "mode": "typed", "answers": ["ok. 4 promile"]},
    {"category": "Toksykologia", "q": "Jaki związek chemiczny znajduje się w konopiach indyjskich (marihuanie) i odpowiada za działanie psychoaktywne?",
     "mode": "typed", "answers": ["THC (tetrahydrokannabinol)"]},
    {"category": "Toksykologia", "q": "Test wykrywający urobilinogen w toksykologii sądowej to test:",
     "mode": "typed", "answers": ["test Edelmana"]},
    {"category": "Toksykologia", "q": "W jakich sytuacjach klinicznych dochodzi najczęściej do zatoru tłuszczowego?",
     "mode": "typed", "answers": ["złamanie trzonu kości udowej, zmiażdżenie tkanek podskórnych, masywne stłuczenia"]},
    {"category": "Toksykologia", "q": "Jak potwierdzić (histopatologicznie) śmierć z zatoru tłuszczowego?",
     "mode": "typed", "answers": ["wycinki z mózgu i płuc wybarwione Sudanem III"]},

    {"category": "Traumatologia: uraz mechaniczny", "q": "Jaka rana powstanie od uderzenia obuchem siekiery?",
     "mode": "typed", "answers": ["rana tłuczona i darta"]},
    {"category": "Traumatologia: uraz mechaniczny", "q": "Co znajduje się pomiędzy raną tłuczoną a raną ciętą pod względem mechanizmu powstania?",
     "mode": "typed", "answers": ["rana rąbana"]},
    {"category": "Traumatologia: uraz mechaniczny", "q": "Najpewniejszą cechą różnicującą ranę ciętą od rany tłuczonej jest:",
     "mode": "typed", "answers": ["obecność mostków tkanki łącznej w dnie i biegunach rany tłuczonej (w ranie ciętej ich nie ma)"]},
    {"category": "Traumatologia: uraz mechaniczny", "q": "Uraz typu contre-coup: przy uderzeniu w potylicę stłuczenie kory mózgu powstaje w:",
     "mode": "typed", "answers": ["biegunach przednich płatów czołowych i skroniowych"]},
    {"category": "Traumatologia: uraz mechaniczny", "q": "Z jakiej prędkości musi jechać samochód, by ofiara wypadku przeleciała przez pojazd lub wyleciała w powietrze bez kontaktu z przednią szybą?",
     "mode": "typed", "answers": ["od ok. 60-100 km/h i więcej"]},

    {"category": "Traumatologia: postrzały i wybuchy", "q": "Jaki wygląd ma rana wlotowa po strzale z broni gładkolufowej przyłożonej bezpośrednio do kości?",
     "mode": "typed", "answers": ["gwiaździsty (gwiazdkowaty)"]},

    {"category": "Traumatologia: przemoc", "q": "Kobiety allele 6/9 (matka), domniemany ojciec 5/7 (badanie DNA/STR). Który genotyp dziecka WYKLUCZY ojcostwo?",
     "o": ["6/6", "6/7", "5/6", "5/9", "7/9"], "a": 0},
    {"category": "Traumatologia: przemoc", "q": "Rodzaj przestępstwa: matka porzuciła noworodka w lesie (zamiar ewentualny, bez działania czynnego).",
     "mode": "typed", "answers": ["dzieciobójstwo bierne z zamiarem ewentualnym"]},
    {"category": "Traumatologia: przemoc", "q": "Na czym polega przeniesiony zespół Münchhausena?",
     "mode": "typed", "answers": ["opiekun (najczęściej matka) wymyśla lub wywołuje objawy choroby u dziecka, by uzyskać dla niego opiekę medyczną"]},
    {"category": "Traumatologia: przemoc", "q": "O czym może świadczyć obecność powietrza w przewodzie pokarmowym noworodka podczas sekcji?",
     "mode": "typed", "answers": ["dziecko urodziło się żywe i zostało nakarmione/oddychało po urodzeniu (zmarło już po porodzie)"]},
]
