import fs from 'fs';

const items = [
  { category: 'Wywiad lekarski', q: 'Jaka jest prawidłowa, ogólna struktura (kolejność głównych bloków) pełnego wywiadu lekarskiego?', o: ['przedstawienie się i dane osobowe → główne dolegliwości → dolegliwości szczegółowe wg układów → objawy ogólne → choroby przewlekłe/leki → urazy/operacje/hospitalizacje → uczulenia → wywiad rodzinny/środowiskowy → używki', 'wyłącznie pytanie o grupę krwi, bez żadnych innych elementów', 'wyłącznie badanie obrazowe, bez zadawania jakichkolwiek pytań pacjentowi', 'wywiad rodzinny jako jedyny, wystarczający element całego wywiadu', 'wyłącznie pytanie o ulubiony kolor pacjenta'], a: 0, rationale: "Poprawnie: pełny, systematyczny wywiad lekarski przebiega w logicznej kolejności: przedstawienie się i zebranie danych osobowych → pytanie o główne, obecne dolegliwości → szczegółowe dolegliwości według poszczególnych układów (krążenia, oddechowego, pokarmowego, moczowo-płciowego, ruchu, nerwowego, powłokowego) → objawy ogólne (zmęczenie, gorączka, zmiana masy ciała) → choroby przewlekłe i przyjmowane leki → przebyte urazy/operacje/hospitalizacje → uczulenia → wywiad rodzinny i środowiskowy → używki. Sama grupa krwi jest jedynie drobnym, wąskim elementem pełnej dokumentacji medycznej, dalece niewystarczającym jako całość wywiadu lekarskiego. Wywiad lekarski z definicji WYMAGA aktywnego zadawania pytań pacjentowi — nie może być zastąpiony wyłącznie badaniem obrazowym, które dostarcza innego rodzaju informacji. Sam wywiad rodzinny jest tylko JEDNYM z wielu elementów pełnego wywiadu, niewystarczającym samodzielnie do uzyskania pełnego obrazu klinicznego pacjenta. Pytanie o ulubiony kolor nie jest elementem medycznego wywiadu lekarskiego." },
  { category: 'Wywiad lekarski', q: 'O jakie objawy pytamy w ramach dolegliwości szczegółowych układu KRĄŻENIA podczas wywiadu?', o: ['ból w klatce piersiowej, kołatanie serca, duszności', 'wyłącznie problemy z węchem i smakiem', 'wyłącznie zmiany skórne i świąd', 'wyłącznie zaburzenia miesiączkowania', 'wyłącznie trudności w połykaniu'], a: 0, rationale: "Poprawnie: w ramach dolegliwości szczegółowych układu krążenia pytamy o ból w klatce piersiowej, kołatanie serca (odczuwanie nieregularnej lub przyspieszonej pracy serca) oraz duszności — te objawy są kluczowe dla wstępnej oceny funkcji układu sercowo-naczyniowego. Problemy z węchem i smakiem należą do dolegliwości układu NERWOWEGO (zmysły), nie krążenia. Zmiany skórne i świąd należą do dolegliwości układu POWŁOKOWEGO (skóry), niezwiązanego z układem krążenia. Zaburzenia miesiączkowania należą do dolegliwości układu MOCZOWO-PŁCIOWEGO, nie krążenia. Trudności w połykaniu należą do dolegliwości układu POKARMOWEGO, niezwiązanego z układem krążenia w tym podziale wywiadu." },
  { category: 'Wywiad lekarski', q: 'O jakie objawy pytamy w ramach dolegliwości szczegółowych układu POKARMOWEGO podczas wywiadu?', o: ['zgaga, pieczenie w przełyku, trudności w połykaniu, wymioty, nudności, wzdęcia, zaparcia, biegunki oraz zmiany w wyglądzie stolca (smolisty/jasny/krwisty)', 'wyłącznie ból głowy i zawroty głowy', 'wyłącznie kołatanie serca', 'wyłącznie problemy z poruszaniem się i obrzęki kończyn', 'wyłącznie objawy dotyczące wyłącznie skóry twarzy'], a: 0, rationale: "Poprawnie: dolegliwości szczegółowe układu pokarmowego obejmują zgagę, pieczenie w przełyku, trudności w połykaniu, wymioty, nudności, wzdęcia, zaparcia, biegunki oraz istotne zmiany w wyglądzie stolca (smolisty — sugerujący krwawienie z górnego odcinka przewodu pokarmowego, jasny lub krwisty — sugerujące inne patologie) — to szeroki zestaw objawów swoistych dla przewodu pokarmowego. Ból i zawroty głowy należą do dolegliwości układu NERWOWEGO, niezwiązanego z przewodem pokarmowym. Kołatanie serca należy do dolegliwości układu KRĄŻENIA, odrębnej kategorii. Problemy z poruszaniem się i obrzęki kończyn należą do dolegliwości układu RUCHU, niezwiązanego z pokarmowym. Objawy skórne twarzy należą do układu POWŁOKOWEGO, niezwiązanego z przewodem pokarmowym w tym podziale." },
  { category: 'Wywiad lekarski', q: 'Jakie objawy OGÓLNE pytamy w ramach standardowego wywiadu lekarskiego?', o: ['zmęczenie/osłabienie/apatię, gorączkę, zmianę masy ciała, zaburzony apetyt oraz zaburzenia snu i rytmu okołodobowego', 'wyłącznie ból konkretnego stawu', 'wyłącznie krwawienie z konkretnego miejsca', 'wyłącznie problemy z konkretnym zębem', 'wyłącznie kolor moczu w danym dniu'], a: 0, rationale: "Poprawnie: objawy ogólne (niezwiązane swoiście z jednym konkretnym układem) obejmują zmęczenie, osłabienie, apatię, gorączkę, zmianę masy ciała, zaburzony apetyt oraz zaburzenia snu i rytmu okołodobowego — te objawy mają charakter systemowy, mogący towarzyszyć bardzo wielu różnym schorzeniom. Ból konkretnego stawu jest objawem SZCZEGÓŁOWYM, przypisanym do układu ruchu, nie objawem ogólnym w tym rozumieniu. Krwawienie z konkretnego miejsca jest objawem szczegółowym, swoistym dla danego układu (np. pokarmowego, moczowo-płciowego), nie ogólnym. Problem z konkretnym zębem jest wąskim, swoistym objawem stomatologicznym, nie ogólnym objawem systemowym. Kolor moczu w danym dniu jest szczegółowym objawem układu moczowo-płciowego, nie ogólnym objawem systemowym." },
  { category: 'Wywiad lekarski', q: 'Które choroby przewlekłe są SZCZEGÓLNIE ważne do zapytania w standardowym wywiadzie lekarskim (jako główne, najczęstsze)?', o: ['cukrzyca i nadciśnienie tętnicze', 'wyłącznie choroby paznokci', 'wyłącznie łagodne, przejściowe przeziębienia z ostatniego tygodnia', 'wyłącznie ostatnio przeczytane książki pacjenta', 'wyłącznie kolor oczu pacjenta'], a: 0, rationale: "Poprawnie: cukrzyca i nadciśnienie tętnicze są wymieniane jako główne, szczególnie istotne choroby przewlekłe, o które należy zapytać w standardowym wywiadzie lekarskim, ze względu na ich powszechność i istotny wpływ na inne aspekty zdrowia pacjenta oraz planowane postępowanie diagnostyczno-lecznicze. Choroby paznokci nie są typowo wymienianą, kluczową kategorią chorób przewlekłych w standardowym wywiadzie ogólnym. Przejściowe, łagodne przeziębienie z ostatniego tygodnia nie jest chorobą PRZEWLEKŁĄ — to ostry, samoograniczający się stan, niepasujący do tej kategorii pytań. Ostatnio przeczytane książki nie mają żadnego związku z medycznym wywiadem o choroby przewlekłe. Kolor oczu pacjenta jest cechą fizyczną, niezwiązaną z pytaniem o choroby przewlekłe w wywiadzie." },
  { category: 'Wywiad lekarski', q: 'Co obejmuje pytanie o "wywiad środowiskowy" pacjenta?', o: ['warunki życia i pracy pacjenta mogące mieć wpływ na jego zdrowie (np. narażenie zawodowe, warunki mieszkaniowe, kontakt ze szkodliwymi czynnikami)', 'wyłącznie pytanie o ulubioną porę roku pacjenta', 'wyłącznie pytanie o markę samochodu pacjenta', 'wyłącznie pytanie o imię zwierzęcia domowego, bez związku ze zdrowiem', 'wywiad środowiskowy nigdy nie jest elementem standardowego wywiadu lekarskiego'], a: 0, rationale: "Poprawnie: wywiad środowiskowy obejmuje pytania o warunki życia i pracy pacjenta, które mogą mieć istotny wpływ na jego zdrowie — np. narażenie zawodowe na szkodliwe substancje, warunki mieszkaniowe, kontakt ze zwierzętami/alergenami czy inne czynniki środowiskowe mogące tłumaczyć obecne dolegliwości lub zwiększać ryzyko konkretnych schorzeń. Ulubiona pora roku nie ma medycznego znaczenia diagnostycznego i nie jest elementem wywiadu środowiskowego. Marka samochodu pacjenta nie ma bezpośredniego związku ze zdrowiem i nie jest standardowym elementem wywiadu medycznego. Imię zwierzęcia domowego samo w sobie nie ma znaczenia medycznego — istotny mógłby być raczej sam FAKT kontaktu ze zwierzętami (np. ryzyko zoonoz), nie imię zwierzęcia. Wywiad środowiskowy JEST standardowym, istotnym elementem pełnego wywiadu lekarskiego — stwierdzenie przeciwne jest nieprawdziwe." },
  { category: 'Wywiad lekarski', q: 'Co obejmuje pytanie o "używki" w wywiadzie lekarskim?', o: ['od kiedy, jak często i w jakiej ilości pacjent stosuje substancje takie jak alkohol, tytoń czy inne substancje psychoaktywne', 'wyłącznie pytanie o ulubioną potrawę pacjenta', 'wyłącznie pytanie o godzinę, o której pacjent się obudził danego dnia', 'wyłącznie pytanie o kolor ubrania noszonego przez pacjenta', 'używki nigdy nie są elementem standardowego wywiadu lekarskiego'], a: 0, rationale: "Poprawnie: pytanie o używki obejmuje szczegółowe informacje o stosowaniu przez pacjenta substancji takich jak alkohol, tytoń czy inne substancje psychoaktywne — istotne jest ustalenie OD KIEDY dana substancja jest stosowana, JAK CZĘSTO oraz W JAKIEJ ILOŚCI, ponieważ te dane mają istotne znaczenie dla oceny ryzyka wielu chorób i interpretacji obecnych objawów. Ulubiona potrawa pacjenta nie jest elementem pytania o używki w rozumieniu medycznym. Godzina obudzenia się danego dnia nie jest elementem wywiadu o używki (choć mogłaby być istotna w kontekście oceny snu, to odrębna kategoria pytań). Kolor ubrania pacjenta nie ma żadnego związku medycznego z pytaniem o używki. Pytanie o używki JEST standardowym, kluczowym elementem pełnego wywiadu lekarskiego — stwierdzenie przeciwne jest nieprawdziwe." },
];

const raw = JSON.parse(fs.readFileSync('wdnk_raw.json', 'utf8'));
for (const item of items) {
  raw.push({ category: item.category, q: item.q, o: item.o, a: item.a, rationale: item.rationale });
}
fs.writeFileSync('wdnk_raw.json', JSON.stringify(raw, null, 2));
console.log('dodano', items.length, 'pytan. nowa dlugosc wdnk_raw.json:', raw.length);
